//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "child_pugh_score_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub bilirubin_points: Option<i32>,
    pub albumin_points: Option<i32>,
    pub coagulation_points: Option<i32>,
    pub ascites_points: Option<i32>,
    pub encephalopathy_points: Option<i32>,
    pub total_score: Option<i32>,
    pub child_pugh_class: String,
    pub one_year_survival: String,
    pub two_year_survival: String,
    pub surgical_risk: String,
    pub graded_at: DateTimeWithTimeZone,
    pub child_pugh_score_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::child_pugh_score_grade_flags::Entity")]
    ChildPughScoreGradeFlags,
    #[sea_orm(has_many = "super::child_pugh_score_grade_rules::Entity")]
    ChildPughScoreGradeRules,
    #[sea_orm(
        belongs_to = "super::child_pugh_scores::Entity",
        from = "Column::ChildPughScoreId",
        to = "super::child_pugh_scores::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ChildPughScores,
}

impl Related<super::child_pugh_score_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChildPughScoreGradeFlags.def()
    }
}

impl Related<super::child_pugh_score_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChildPughScoreGradeRules.def()
    }
}

impl Related<super::child_pugh_scores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChildPughScores.def()
    }
}
