//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "anaesthetic_records")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub theatre: String,
    pub operation_date: Option<Date>,
    pub anaesthetist_name: String,
    pub assistant_name: String,
    pub surgeon_name: String,
    #[sea_orm(column_type = "Text")]
    pub planned_procedure: String,
    pub urgency: String,
    pub machine_checked: String,
    pub who_sign_in: String,
    pub who_time_out: String,
    pub consent_confirmed: String,
    pub fasting_confirmed: String,
    #[sea_orm(column_type = "Text")]
    pub iv_access: String,
    pub allergy_band_checked: String,
    #[sea_orm(column_type = "Text")]
    pub documented_allergies: String,
    pub asa_status: String,
    pub asa_emergency_modifier: String,
    pub mallampati_class: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub mouth_opening_cm: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub thyromental_distance_cm: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub dentition: String,
    pub anticipated_difficult_airway: String,
    pub prior_difficult_intubation: String,
    pub airway_technique: String,
    pub device_size: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub tube_depth_cm: Option<f64>,
    pub cuffed: String,
    pub cormack_lehane_grade: Option<i32>,
    pub intubation_attempts: Option<i32>,
    pub capnography_confirmed: String,
    #[sea_orm(column_type = "Text")]
    pub monitoring_modalities: String,
    pub anaesthetic_technique: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub crystalloid_ml: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub colloid_ml: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub blood_products_ml: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub estimated_blood_loss_ml: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub urine_output_ml: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cell_salvage_ml: Option<f64>,
    pub regional_technique: String,
    pub regional_level: String,
    pub regional_drug: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub regional_dose_mg: Option<f64>,
    pub block_height: String,
    #[sea_orm(column_type = "Text")]
    pub regional_complications: String,
    pub recovery_destination: String,
    #[sea_orm(column_type = "Text")]
    pub handover_airway_status: String,
    #[sea_orm(column_type = "Text")]
    pub analgesia_plan: String,
    #[sea_orm(column_type = "Text")]
    pub antiemetic_plan: String,
    #[sea_orm(column_type = "Text")]
    pub oxygen_plan: String,
    #[sea_orm(column_type = "Text")]
    pub outstanding_tasks: String,
    pub handover_at: Option<DateTimeWithTimeZone>,
    pub receiving_practitioner: String,
    #[sea_orm(column_type = "Text")]
    pub anaesthetist_signature: String,
    pub signed_at: Option<DateTimeWithTimeZone>,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::anaesthetic_record_drug_administrations::Entity")]
    AnaestheticRecordDrugAdministrations,
    #[sea_orm(has_many = "super::anaesthetic_record_grades::Entity")]
    AnaestheticRecordGrades,
    #[sea_orm(has_many = "super::anaesthetic_record_intra_operative_events::Entity")]
    AnaestheticRecordIntraOperativeEvents,
    #[sea_orm(has_many = "super::anaesthetic_record_timed_observations::Entity")]
    AnaestheticRecordTimedObservations,
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::anaesthetic_record_drug_administrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnaestheticRecordDrugAdministrations.def()
    }
}

impl Related<super::anaesthetic_record_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnaestheticRecordGrades.def()
    }
}

impl Related<super::anaesthetic_record_intra_operative_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnaestheticRecordIntraOperativeEvents.def()
    }
}

impl Related<super::anaesthetic_record_timed_observations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnaestheticRecordTimedObservations.def()
    }
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
