//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "anaesthetic_record_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub completeness_percent: i32,
    pub graded_at: DateTimeWithTimeZone,
    pub anaesthetic_record_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::anaesthetic_record_grade_flags::Entity")]
    AnaestheticRecordGradeFlags,
    #[sea_orm(has_many = "super::anaesthetic_record_grade_rules::Entity")]
    AnaestheticRecordGradeRules,
    #[sea_orm(
        belongs_to = "super::anaesthetic_records::Entity",
        from = "Column::AnaestheticRecordId",
        to = "super::anaesthetic_records::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AnaestheticRecords,
}

impl Related<super::anaesthetic_record_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnaestheticRecordGradeFlags.def()
    }
}

impl Related<super::anaesthetic_record_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnaestheticRecordGradeRules.def()
    }
}

impl Related<super::anaesthetic_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnaestheticRecords.def()
    }
}
