#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding framingham-risk-score-for-hard-coronary-heart-disease (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_patient_information \
    assessment:references \
    full_name:string! \
    date_of_birth:date \
    nhs_number:string! \
    address:text! \
    telephone:string! \
    email:string! \
    gp_name:string! \
    gp_practice:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    age:int \
    sex:string! \
    ethnicity:string! \
    height_cm:double \
    weight_kg:double \
    --htmx

cargo loco generate scaffold assessment_smoking_history \
    assessment:references \
    smoking_status:string! \
    cigarettes_per_day:int \
    years_smoked:int \
    years_since_quit:int \
    --htmx

cargo loco generate scaffold assessment_blood_pressure \
    assessment:references \
    systolic_bp:int \
    diastolic_bp:int \
    on_bp_treatment:string! \
    bp_medication_name:string! \
    bp_measurement_method:string! \
    --htmx

cargo loco generate scaffold assessment_cholesterol \
    assessment:references \
    total_cholesterol:double \
    hdl_cholesterol:double \
    ldl_cholesterol:double \
    triglycerides:double \
    cholesterol_unit:string! \
    fasting_sample:string! \
    --htmx

cargo loco generate scaffold assessment_medical_history \
    assessment:references \
    has_diabetes:string! \
    has_prior_chd:string! \
    has_peripheral_vascular_disease:string! \
    has_cerebrovascular_disease:string! \
    has_heart_failure:string! \
    has_atrial_fibrillation:string! \
    other_conditions:text! \
    --htmx

cargo loco generate scaffold assessment_family_history \
    assessment:references \
    family_chd_history:string! \
    family_chd_age_onset:string! \
    family_chd_relationship:string! \
    family_stroke_history:string! \
    family_diabetes_history:string! \
    --htmx

cargo loco generate scaffold assessment_lifestyle_factors \
    assessment:references \
    physical_activity:string! \
    alcohol_consumption:string! \
    diet_quality:string! \
    bmi:double \
    waist_circumference_cm:double \
    stress_level:string! \
    --htmx

cargo loco generate scaffold assessment_current_medications \
    assessment:references \
    on_statin:string! \
    statin_name:string! \
    on_aspirin:string! \
    on_antihypertensive:string! \
    antihypertensive_name:string! \
    other_medications:text! \
    --htmx

cargo loco generate scaffold assessment_review_calculate \
    assessment:references \
    clinician_name:string! \
    review_date:date \
    clinical_notes:text! \
    patient_consent:string! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    ten_year_risk_percent:double! \
    risk_category:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    risk_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
