#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding pre-operative-assessment-by-clinician (21 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_clinician \
    assessment:references \
    clinician_name:string! \
    clinician_role:string! \
    registration_body:string! \
    registration_number:string! \
    site_name:string! \
    assessment_date:date \
    assessment_time:string \
    --htmx

cargo loco generate scaffold assessment_surgery_plan \
    assessment:references \
    planned_procedure:string! \
    surgical_specialty:string! \
    urgency:string! \
    laterality:string! \
    surgical_severity:string! \
    anticipated_blood_loss_ml:int \
    anticipated_duration_minutes:int \
    consultant_surgeon:string! \
    planned_date:date \
    --htmx

cargo loco generate scaffold assessment_vitals \
    assessment:references \
    systolic_bp:int \
    diastolic_bp:int \
    heart_rate:int \
    respiratory_rate:int \
    spo2_percent:double \
    temperature_celsius:double \
    capillary_refill_seconds:double \
    pain_score_0_10:int \
    on_room_air:string! \
    supplemental_oxygen_litres:double \
    --htmx

cargo loco generate scaffold assessment_airway \
    assessment:references \
    mallampati_class:string! \
    thyromental_distance_cm:double \
    mouth_opening_cm:double \
    inter_incisor_gap_cm:double \
    neck_rom:string! \
    cervical_spine_stability:string! \
    dentition:string! \
    beard:string! \
    upper_lip_bite_test:string! \
    prior_difficult_intubation:string! \
    stopbang_snoring:string! \
    stopbang_tired:string! \
    stopbang_observed_apnoea:string! \
    stopbang_pressure:string! \
    stopbang_bmi_gt35:string! \
    stopbang_age_gt50:string! \
    stopbang_neck_gt40:string! \
    stopbang_male:string! \
    airway_notes:text! \
    --htmx

cargo loco generate scaffold assessment_cardiovascular \
    assessment:references \
    heart_rhythm:string! \
    murmur_present:string! \
    murmur_description:string! \
    peripheral_pulses:string! \
    jvp_raised:string! \
    peripheral_oedema:string! \
    ecg_performed:string! \
    ecg_rhythm:string! \
    ecg_rate_bpm:int \
    ecg_axis:string! \
    ecg_ischaemic_changes:string! \
    ecg_notes:text! \
    echo_performed:string! \
    echo_ef_percent:int \
    echo_notes:text! \
    history_ihd:string! \
    history_chf:string! \
    history_stroke_tia:string! \
    recent_mi_within_3_months:string! \
    pacemaker_or_icd:string! \
    severe_valve_dysfunction:string! \
    active_angina:string! \
    --htmx

cargo loco generate scaffold assessment_respiratory \
    assessment:references \
    breath_sounds:string! \
    wheeze:string! \
    crackles:string! \
    crepitations:string! \
    chest_wall_deformity:string! \
    asthma:string! \
    copd:string! \
    cxr_performed:string! \
    cxr_findings:text! \
    pft_performed:string! \
    pft_fev1_percent_predicted:double \
    pft_fev1_fvc_ratio:double \
    smoking_status:string! \
    pack_years:double \
    covid_history:string! \
    days_since_covid:int \
    covid_unresolved_symptoms:string! \
    --htmx

cargo loco generate scaffold assessment_neurological \
    assessment:references \
    gcs_total:int \
    gcs_eye:int \
    gcs_verbal:int \
    gcs_motor:int \
    cognition_tool:string! \
    cognition_score:int \
    cognitive_impairment:string! \
    capacity_concern:string! \
    cranial_nerves_notes:text! \
    motor_power:string! \
    sensory_notes:text! \
    reflexes:string! \
    recent_stroke_tia:string! \
    days_since_stroke_tia:int \
    seizure_disorder:string! \
    --htmx

cargo loco generate scaffold assessment_renal_hepatic \
    assessment:references \
    creatinine_umol_l:int \
    egfr_ml_min_1_73m2:int \
    urea_mmol_l:double \
    potassium_mmol_l:double \
    sodium_mmol_l:double \
    dialysis_status:string! \
    ckd_stage:string! \
    bilirubin_umol_l:int \
    alt_u_l:int \
    ast_u_l:int \
    alp_u_l:int \
    albumin_g_l:double \
    chronic_liver_disease:string! \
    child_pugh_class:string! \
    --htmx

cargo loco generate scaffold assessment_haematology \
    assessment:references \
    hb_g_l:int \
    wcc_10_9_l:double \
    platelets_10_9_l:int \
    mcv_fl:double \
    ferritin_ug_l:int \
    transferrin_saturation_percent:double \
    inr:double \
    aptt_seconds:double \
    fibrinogen_g_l:double \
    on_anticoagulant:string! \
    anticoagulant_type:string! \
    anticoagulant_hold_plan:string! \
    group_and_save:string! \
    crossmatch_units:int \
    last_transfusion_date:date \
    anaemia_severity:string! \
    --htmx

cargo loco generate scaffold assessment_endocrine \
    assessment:references \
    diabetes_type:string! \
    diabetes_on_insulin:string! \
    hba1c_mmol_mol:int \
    fasting_glucose_mmol_l:double \
    random_glucose_mmol_l:double \
    diabetes_control:string! \
    diabetes_complications:string! \
    thyroid_status:string! \
    tsh_mu_l:double \
    adrenal_status:string! \
    on_long_term_steroids:string! \
    steroid_dose_mg:double \
    steroid_cover_plan:string! \
    --htmx

cargo loco generate scaffold assessment_gastrointestinal \
    assessment:references \
    abdominal_exam:string! \
    abdominal_notes:text! \
    reflux_symptoms:string! \
    hiatus_hernia:string! \
    previous_gastric_surgery:string! \
    ng_tube:string! \
    stoma:string! \
    fasting_confirmed:string! \
    last_solid_food_at:ts \
    last_clear_fluid_at:ts \
    rapid_sequence_induction_needed:string! \
    --htmx

cargo loco generate scaffold assessment_musculoskeletal \
    assessment:references \
    spine_exam:string! \
    spine_notes:text! \
    neuraxial_suitable:string! \
    joint_rom_hip:string! \
    joint_rom_shoulder:string! \
    joint_rom_neck:string! \
    skin_iv_access:string! \
    skin_block_site:string! \
    pressure_ulcer_risk:string! \
    --htmx

cargo loco generate scaffold assessment_medication \
    assessment:references \
    name:string! \
    dose:string! \
    route:string! \
    frequency:string! \
    indication:string! \
    class:string! \
    perioperative_action:string! \
    perioperative_notes:string! \
    last_dose_at:ts \
    --htmx

cargo loco generate scaffold assessment_allergy \
    assessment:references \
    allergen:string! \
    category:string! \
    reaction_type:string! \
    reaction_severity:string! \
    reaction_notes:string! \
    verified:string! \
    --htmx

cargo loco generate scaffold assessment_functional_capacity \
    assessment:references \
    mets_estimate:double \
    dasi_score:double \
    ecog_performance_status:int \
    clinical_frailty_scale:int \
    six_minute_walk_metres:int \
    sts_one_minute_reps:int \
    tug_seconds:double \
    cpet_performed:string! \
    cpet_vo2_peak_ml_kg_min:double \
    cpet_anaerobic_threshold_ml_kg_min:double \
    cpet_notes:text! \
    malnutrition_risk:string! \
    unintentional_weight_loss_kg:double \
    --htmx

cargo loco generate scaffold assessment_anaesthesia_plan \
    assessment:references \
    technique:string! \
    airway_plan:string! \
    rsi_planned:string! \
    monitoring_level:string! \
    analgesia_plan:string! \
    regional_block_planned:string! \
    dvt_prophylaxis:string! \
    antibiotic_prophylaxis:string! \
    post_op_disposition:string! \
    anticipated_length_of_stay_days:int \
    special_equipment:string! \
    blood_products_required:string! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    computed_asa_grade:string! \
    final_asa_grade:string! \
    asa_emergency_suffix:string! \
    override_reason:string! \
    mallampati_class:string! \
    rcri_score:int \
    stopbang_score:int \
    frailty_scale:int \
    composite_risk:string! \
    recommendation:string! \
    clinician_notes:text! \
    signed_at:ts \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    instrument:string! \
    grade:string! \
    category:string! \
    description:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    priority:string! \
    description:string! \
    suggested_action:string! \
    --htmx

echo "Done."
