#!/bin/sh
set -euf

cargo loco generate scaffold pre_operative_assessment_by_patient \
    patient:references \
    weight:double \
    height:double \
    bmi:double \
    planned_procedure:text! \
    procedure_urgency:text! \
    status:text! \
    hypertension:text! \
    hypertension_controlled:text! \
    ischemic_heart_disease:text! \
    ihd_details:text! \
    heart_failure:text! \
    heart_failure_nyha:text! \
    valvular_disease:text! \
    valvular_details:text! \
    arrhythmia:text! \
    arrhythmia_type:text! \
    pacemaker:text! \
    recent_mi:text! \
    recent_mi_weeks:int \
    asthma:text! \
    asthma_frequency:text! \
    copd:text! \
    copd_severity:text! \
    osa:text! \
    osa_cpap:text! \
    smoking:text! \
    smoking_pack_years:int \
    recent_urti:text! \
    ckd:text! \
    ckd_stage:text! \
    dialysis:text! \
    dialysis_type:text! \
    liver_disease:text! \
    cirrhosis:text! \
    child_pugh_score:text! \
    hepatitis:text! \
    hepatitis_type:text! \
    diabetes:text! \
    diabetes_control:text! \
    diabetes_on_insulin:text! \
    thyroid_disease:text! \
    thyroid_type:text! \
    adrenal_insufficiency:text! \
    stroke_or_tia:text! \
    stroke_details:text! \
    epilepsy:text! \
    epilepsy_controlled:text! \
    neuromuscular_disease:text! \
    neuromuscular_details:text! \
    raised_icp:text! \
    bleeding_disorder:text! \
    bleeding_details:text! \
    on_anticoagulants:text! \
    anticoagulant_type:text! \
    sickle_cell_disease:text! \
    sickle_cell_trait:text! \
    anaemia:text! \
    rheumatoid_arthritis:text! \
    cervical_spine_issues:text! \
    limited_neck_movement:text! \
    limited_mouth_opening:text! \
    dental_issues:text! \
    dental_details:text! \
    previous_difficult_airway:text! \
    mallampati_score:text! \
    gord:text! \
    hiatus_hernia:text! \
    nausea:text! \
    name:text! \
    dose:text! \
    frequency:text! \
    sort_order:int! \
    allergen:text! \
    reaction:text! \
    severity:text! \
    allergy_sort_order:int! \
    previous_anaesthesia:text! \
    anaesthesia_problems:text! \
    anaesthesia_problem_details:text! \
    family_mh_history:text! \
    family_mh_details:text! \
    ponv:text! \
    alcohol:text! \
    alcohol_units_per_week:int \
    recreational_drugs:text! \
    drug_details:text! \
    exercise_tolerance:text! \
    estimated_mets:double \
    mobility_aids:text! \
    recent_decline:text! \
    possibly_pregnant:text! \
    pregnancy_confirmed:text! \
    gestation_weeks:int \
    --htmx && \
