//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "national_early_warning_score_2s")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub observation_at: Option<DateTimeWithTimeZone>,
    pub ward_or_location: String,
    pub spo2_scale: String,
    pub spo2_scale2_endorsed: String,
    pub respiratory_rate: Option<i32>,
    pub spo2: Option<i32>,
    pub on_oxygen: String,
    pub oxygen_device: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub oxygen_flow_rate_l_min: Option<f64>,
    pub inspired_oxygen_fraction_percent: Option<i32>,
    pub systolic_blood_pressure: Option<i32>,
    pub pulse: Option<i32>,
    pub consciousness_acvpu: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub temperature: Option<f64>,
    pub is_under_16: String,
    pub is_pregnant: String,
    pub has_spinal_cord_injury: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_notes: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::national_early_warning_score_2_grades::Entity")]
    NationalEarlyWarningScore2Grades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::national_early_warning_score_2_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NationalEarlyWarningScore2Grades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
