//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "ottawa_ankle_rules_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub unable_to_bear_weight: String,
    pub ankle_xray_indicated: String,
    pub foot_xray_indicated: String,
    #[sea_orm(column_type = "Text")]
    pub recommended_action: String,
    pub graded_at: DateTimeWithTimeZone,
    pub ottawa_ankle_rules_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ottawa_ankle_rules::Entity",
        from = "Column::OttawaAnkleRulesId",
        to = "super::ottawa_ankle_rules::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    OttawaAnkleRules,
    #[sea_orm(has_many = "super::ottawa_ankle_rules_grade_flags::Entity")]
    OttawaAnkleRulesGradeFlags,
    #[sea_orm(has_many = "super::ottawa_ankle_rules_grade_rules::Entity")]
    OttawaAnkleRulesGradeRules,
}

impl Related<super::ottawa_ankle_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OttawaAnkleRules.def()
    }
}

impl Related<super::ottawa_ankle_rules_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OttawaAnkleRulesGradeFlags.def()
    }
}

impl Related<super::ottawa_ankle_rules_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OttawaAnkleRulesGradeRules.def()
    }
}
