-- ============================================================
-- 02_encounter_satisfaction.sql
-- A single encounter satisfaction survey record.
-- ============================================================
-- Each encounter satisfaction survey belongs to one patient and
-- captures their feedback for a single healthcare encounter.
-- Subsystem details are stored in 1:1 child tables (03-08).
-- ============================================================

CREATE TABLE encounter_satisfaction (
    -- Primary key: UUIDv4 generated by the database
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key to the patient this survey belongs to
    patient_id          UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,

    -- Workflow status tracking
    status              TEXT NOT NULL DEFAULT 'in_progress'
                        CHECK (status IN ('in_progress', 'completed', 'reviewed', '')),

    -- Audit timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for the most common query: all surveys for a patient
CREATE INDEX idx_encounter_satisfaction_patient_id ON encounter_satisfaction(patient_id);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_encounter_satisfaction_updated_at
    BEFORE UPDATE ON encounter_satisfaction
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE encounter_satisfaction IS
    'A single encounter satisfaction survey record. Child tables hold section-specific data.';
COMMENT ON COLUMN encounter_satisfaction.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN encounter_satisfaction.patient_id IS
    'FK to patient. One patient may have many surveys.';
COMMENT ON COLUMN encounter_satisfaction.status IS
    'Workflow status: in_progress, completed, reviewed, or empty string if unanswered.';
COMMENT ON COLUMN encounter_satisfaction.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN encounter_satisfaction.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
