//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "soap_notes")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub encountered_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    pub encounter_type: String,
    pub clinician_role: String,
    pub patient_identifier: String,
    #[sea_orm(column_type = "Text")]
    pub presenting_complaint: String,
    #[sea_orm(column_type = "Text")]
    pub history_of_presenting_complaint: String,
    #[sea_orm(column_type = "Text")]
    pub patient_reported_symptoms: String,
    #[sea_orm(column_type = "Text")]
    pub relevant_history: String,
    pub red_flag_symptoms: String,
    #[sea_orm(column_type = "Text")]
    pub examination_findings: String,
    #[sea_orm(column_type = "Text")]
    pub vital_signs: String,
    pub abnormal_vitals_present: String,
    #[sea_orm(column_type = "Text")]
    pub investigation_results: String,
    #[sea_orm(column_type = "Text")]
    pub primary_diagnosis: String,
    #[sea_orm(column_type = "Text")]
    pub problem_list: String,
    #[sea_orm(column_type = "Text")]
    pub differential: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_impression: String,
    #[sea_orm(column_type = "Text")]
    pub investigations_plan: String,
    #[sea_orm(column_type = "Text")]
    pub treatment_plan: String,
    #[sea_orm(column_type = "Text")]
    pub referrals: String,
    #[sea_orm(column_type = "Text")]
    pub follow_up: String,
    #[sea_orm(column_type = "Text")]
    pub safety_netting: String,
    pub managed_at_home: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_note: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::soap_note_grades::Entity")]
    SoapNoteGrades,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::soap_note_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SoapNoteGrades.def()
    }
}
