#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding cardiology-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    preferred_name:string! \
    gender_identity:string! \
    ethnicity:string! \
    preferred_language:string! \
    interpreter_required:string! \
    gp_name:string! \
    gp_practice:string! \
    referrer_name:string! \
    referrer_role:string! \
    --htmx

cargo loco generate scaffold assessment_chest_pain_angina \
    assessment:references \
    has_chest_pain:string! \
    chest_pain_character:string! \
    chest_pain_character_other:text! \
    chest_pain_location:string! \
    chest_pain_radiation:string! \
    chest_pain_duration_minutes:int \
    chest_pain_trigger:string! \
    relieved_by_rest:string! \
    relieved_by_gtn:string! \
    ccs_angina_class:string! \
    angina_frequency:string! \
    chest_pain_notes:text! \
    --htmx

cargo loco generate scaffold assessment_heart_failure_symptoms \
    assessment:references \
    has_dyspnoea:string! \
    dyspnoea_on_exertion:string! \
    orthopnoea:string! \
    pillows_required:int \
    paroxysmal_nocturnal_dyspnoea:string! \
    peripheral_oedema:string! \
    oedema_location:string! \
    fatigue_level:string! \
    weight_gain_recent:string! \
    weight_gain_kg:double \
    nyha_class:string! \
    heart_failure_notes:text! \
    --htmx

cargo loco generate scaffold assessment_cardiac_history \
    assessment:references \
    previous_mi:string! \
    mi_date:date \
    mi_details:text! \
    previous_pci:string! \
    pci_date:date \
    pci_details:text! \
    previous_cabg:string! \
    cabg_date:date \
    cabg_details:text! \
    previous_valve_surgery:string! \
    valve_surgery_details:text! \
    known_heart_failure:string! \
    heart_failure_type:string! \
    ejection_fraction_percent:double \
    known_cardiomyopathy:string! \
    cardiomyopathy_type:string! \
    cardiac_history_notes:text! \
    --htmx

cargo loco generate scaffold assessment_arrhythmia_conduction \
    assessment:references \
    has_palpitations:string! \
    palpitation_character:string! \
    palpitation_frequency:string! \
    known_atrial_fibrillation:string! \
    af_type:string! \
    history_of_syncope:string! \
    syncope_details:text! \
    history_of_presyncope:string! \
    known_conduction_disorder:string! \
    conduction_disorder_type:string! \
    has_pacemaker:string! \
    has_icd:string! \
    device_details:text! \
    arrhythmia_notes:text! \
    --htmx

cargo loco generate scaffold assessment_risk_factors \
    assessment:references \
    hypertension:string! \
    systolic_bp_mmhg:int \
    diastolic_bp_mmhg:int \
    diabetes:string! \
    hba1c_mmol_mol:double \
    hyperlipidaemia:string! \
    total_cholesterol_mmol:double \
    ldl_cholesterol_mmol:double \
    hdl_cholesterol_mmol:double \
    smoking_status:string! \
    pack_years:double \
    family_history_cvd:string! \
    family_cvd_details:text! \
    obesity:string! \
    chronic_kidney_disease:string! \
    ckd_stage:string! \
    risk_factors_notes:text! \
    --htmx

cargo loco generate scaffold assessment_diagnostic_results \
    assessment:references \
    ecg_performed:string! \
    ecg_date:date \
    ecg_findings:text! \
    ecg_rhythm:string! \
    echocardiogram_performed:string! \
    echocardiogram_date:date \
    echocardiogram_findings:text! \
    lvef_percent:double \
    exercise_test_performed:string! \
    exercise_test_date:date \
    exercise_test_result:string! \
    exercise_test_details:text! \
    coronary_angiogram_performed:string! \
    coronary_angiogram_date:date \
    coronary_angiogram_findings:text! \
    ct_coronary_angiogram_performed:string! \
    ct_coronary_angiogram_findings:text! \
    bnp_pg_ml:double \
    troponin_ng_l:double \
    diagnostic_notes:text! \
    --htmx

cargo loco generate scaffold assessment_current_medications \
    assessment:references \
    on_antiplatelet:string! \
    antiplatelet_details:text! \
    on_anticoagulant:string! \
    anticoagulant_type:string! \
    anticoagulant_details:text! \
    on_beta_blocker:string! \
    beta_blocker_details:text! \
    on_ace_inhibitor_arb:string! \
    ace_arb_details:text! \
    on_statin:string! \
    statin_details:text! \
    on_diuretic:string! \
    diuretic_details:text! \
    on_calcium_channel_blocker:string! \
    ccb_details:text! \
    on_nitrate:string! \
    nitrate_details:text! \
    other_cardiac_medications:text! \
    medication_adherence:string! \
    medication_notes:text! \
    --htmx

cargo loco generate scaffold assessment_allergies \
    assessment:references \
    has_drug_allergies:string! \
    drug_allergy_details:text! \
    contrast_dye_allergy:string! \
    contrast_dye_allergy_details:text! \
    latex_allergy:string! \
    other_allergies:text! \
    previous_adverse_reactions:text! \
    allergy_notes:text! \
    --htmx

cargo loco generate scaffold assessment_social_functional \
    assessment:references \
    exercise_capacity:string! \
    flights_of_stairs:int \
    walking_distance_metres:int \
    driving_status:string! \
    employment_status:string! \
    occupation:string! \
    physical_demands_of_work:string! \
    alcohol_consumption:string! \
    alcohol_units_per_week:int \
    recreational_drug_use:string! \
    recreational_drug_details:text! \
    psychological_impact:string! \
    anxiety_depression_screen:string! \
    social_functional_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    ccs_angina_class:string! \
    nyha_class:string! \
    overall_risk_level:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
