#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding casualty-card-form (21 tables)..."

cargo loco generate scaffold patient \
    first_name:text! \
    last_name:text! \
    date_of_birth:date \
    sex:text! \
    nhs_number:text! \
    address:text! \
    postcode:text! \
    phone:text! \
    email:text! \
    ethnicity:text! \
    preferred_language:text! \
    interpreter_required:text! \
    --htmx

cargo loco generate scaffold casualty_card \
    patient:references \
    status:text! \
    attendance_date:date \
    arrival_time:ts \
    --htmx

cargo loco generate scaffold casualty_card_demographics \
    casualty_card:references \
    address:text! \
    postcode:text! \
    phone:text! \
    email:text! \
    ethnicity:text! \
    preferred_language:text! \
    interpreter_required:text! \
    --htmx

cargo loco generate scaffold casualty_card_next_of_kin \
    casualty_card:references \
    name:text! \
    relationship:text! \
    phone:text! \
    notified:text! \
    --htmx

cargo loco generate scaffold casualty_card_gp \
    casualty_card:references \
    name:text! \
    practice_name:text! \
    practice_address:text! \
    practice_phone:text! \
    --htmx

cargo loco generate scaffold casualty_card_arrival_triage \
    casualty_card:references \
    attendance_category:text! \
    arrival_mode:text! \
    referral_source:text! \
    ambulance_incident_number:text! \
    triage_time:ts \
    triage_nurse:text! \
    mts_flowchart:text! \
    mts_category:text! \
    mts_discriminator:text! \
    --htmx

cargo loco generate scaffold casualty_card_presenting_complaint \
    casualty_card:references \
    chief_complaint:text! \
    history_of_presenting_complaint:text! \
    onset:text! \
    duration:text! \
    character:text! \
    severity:text! \
    location:text! \
    radiation:text! \
    aggravating_factors:text! \
    relieving_factors:text! \
    associated_symptoms:text! \
    previous_episodes:text! \
    treatment_prior_to_arrival:text! \
    --htmx

cargo loco generate scaffold casualty_card_pain_assessment \
    casualty_card:references \
    pain_present:text! \
    pain_score:int \
    pain_location:text! \
    pain_character:text! \
    pain_onset:text! \
    pain_severity_category:text! \
    --htmx

cargo loco generate scaffold casualty_card_medical_history \
    casualty_card:references \
    past_medical_history:text! \
    past_surgical_history:text! \
    tetanus_status:text! \
    smoking_status:text! \
    alcohol_consumption:text! \
    recreational_drug_use:text! \
    last_oral_intake:text! \
    --htmx

cargo loco generate scaffold casualty_card_medication \
    casualty_card:references \
    name:text! \
    dose:text! \
    frequency:text! \
    sort_order:int! \
    --htmx

cargo loco generate scaffold casualty_card_allergy \
    casualty_card:references \
    allergen:text! \
    reaction:text! \
    severity:text! \
    sort_order:int! \
    --htmx

cargo loco generate scaffold casualty_card_vital_signs \
    casualty_card:references \
    heart_rate:int \
    systolic_bp:int \
    diastolic_bp:int \
    respiratory_rate:int \
    oxygen_saturation:int \
    supplemental_oxygen:text! \
    oxygen_flow_rate:text! \
    temperature:double \
    blood_glucose:double \
    consciousness_level:text! \
    pupil_left_size:int \
    pupil_left_reactive:text! \
    pupil_right_size:int \
    pupil_right_reactive:text! \
    capillary_refill_time:text! \
    weight:double \
    --htmx

cargo loco generate scaffold casualty_card_primary_survey \
    casualty_card:references \
    airway_status:text! \
    airway_adjuncts:text! \
    c_spine_immobilised:text! \
    breathing_effort:text! \
    chest_movement:text! \
    breath_sounds:text! \
    trachea_position:text! \
    pulse_character:text! \
    skin_colour:text! \
    skin_temperature:text! \
    capillary_refill:text! \
    haemorrhage:text! \
    iv_access:text! \
    gcs_eye:int \
    gcs_verbal:int \
    gcs_motor:int \
    gcs_total:int \
    pupils:text! \
    blood_glucose_disability:text! \
    limb_movements:text! \
    skin_examination:text! \
    injuries_identified:text! \
    log_roll_findings:text! \
    --htmx

cargo loco generate scaffold casualty_card_clinical_examination \
    casualty_card:references \
    general_appearance:text! \
    head_and_face:text! \
    neck:text! \
    chest_cardiovascular:text! \
    chest_respiratory:text! \
    abdomen:text! \
    pelvis:text! \
    musculoskeletal_limbs:text! \
    neurological:text! \
    skin:text! \
    mental_state:text! \
    body_diagram_notes:text! \
    --htmx

cargo loco generate scaffold casualty_card_investigations \
    casualty_card:references \
    blood_tests:text! \
    urinalysis:text! \
    pregnancy_test:text! \
    ecg_performed:text! \
    ecg_findings:text! \
    other_investigations:text! \
    --htmx

cargo loco generate scaffold casualty_card_treatment \
    casualty_card:references \
    oxygen_therapy_device:text! \
    oxygen_therapy_flow_rate:text! \
    tetanus_prophylaxis:text! \
    --htmx

cargo loco generate scaffold casualty_card_assessment_plan \
    casualty_card:references \
    working_diagnosis:text! \
    differential_diagnoses:text! \
    clinical_impression:text! \
    risk_stratification:text! \
    --htmx

cargo loco generate scaffold casualty_card_disposition \
    casualty_card:references \
    disposition:text! \
    admitting_specialty:text! \
    admitting_consultant:text! \
    ward:text! \
    level_of_care:text! \
    discharge_diagnosis:text! \
    discharge_medications:text! \
    discharge_instructions:text! \
    follow_up:text! \
    return_precautions:text! \
    receiving_hospital:text! \
    reason_for_transfer:text! \
    mode_of_transfer:text! \
    discharge_time:ts \
    total_time_in_department:text! \
    --htmx

cargo loco generate scaffold casualty_card_safeguarding_consent \
    casualty_card:references \
    safeguarding_concern:text! \
    safeguarding_type:text! \
    referral_made:text! \
    mental_capacity_assessment:text! \
    mental_health_act_status:text! \
    consent_for_treatment:text! \
    completed_by_name:text! \
    completed_by_role:text! \
    completed_by_gmc_number:text! \
    senior_reviewing_clinician:text! \
    --htmx

cargo loco generate scaffold news2_result \
    casualty_card:references \
    total_score:int! \
    clinical_response:text! \
    has_any_single_score_3:bool! \
    parameter_scores:jsonb! \
    scored_at:ts! \
    --htmx

cargo loco generate scaffold flagged_issue \
    news2_result:references \
    flag_id:text! \
    category:text! \
    message:text! \
    priority:text! \
    --htmx

echo "Done."
