import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		dashScore: 12,
		affectedJoint: 'Right shoulder',
		disabilityLevel: 'No disability',
		surgicalCandidate: false,
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		dashScore: 35,
		affectedJoint: 'Left knee',
		disabilityLevel: 'Mild disability',
		surgicalCandidate: false,
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		dashScore: 72,
		affectedJoint: 'Right hip',
		disabilityLevel: 'Severe disability',
		surgicalCandidate: true,
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		dashScore: 5,
		affectedJoint: 'Left wrist',
		disabilityLevel: 'No disability',
		surgicalCandidate: false,
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		dashScore: 88,
		affectedJoint: 'Bilateral shoulders',
		disabilityLevel: 'Very severe disability',
		surgicalCandidate: true,
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		dashScore: 28,
		affectedJoint: 'Right elbow',
		disabilityLevel: 'Mild disability',
		surgicalCandidate: false,
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		dashScore: 55,
		affectedJoint: 'Left shoulder',
		disabilityLevel: 'Moderate disability',
		surgicalCandidate: true,
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		dashScore: 42,
		affectedJoint: 'Right hand',
		disabilityLevel: 'Moderate disability',
		surgicalCandidate: false,
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		dashScore: 65,
		affectedJoint: 'Right shoulder',
		disabilityLevel: 'Severe disability',
		surgicalCandidate: true,
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		dashScore: 8,
		affectedJoint: 'Left elbow',
		disabilityLevel: 'No disability',
		surgicalCandidate: false,
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		dashScore: 48,
		affectedJoint: 'Right wrist',
		disabilityLevel: 'Moderate disability',
		surgicalCandidate: false,
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		dashScore: 82,
		affectedJoint: 'Left hip',
		disabilityLevel: 'Very severe disability',
		surgicalCandidate: true,
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		dashScore: 18,
		affectedJoint: 'Right hand',
		disabilityLevel: 'No disability',
		surgicalCandidate: false,
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		dashScore: 61,
		affectedJoint: 'Bilateral knees',
		disabilityLevel: 'Severe disability',
		surgicalCandidate: true,
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		dashScore: 3,
		affectedJoint: 'Left ankle',
		disabilityLevel: 'No disability',
		surgicalCandidate: false,
	},
];
