import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		hhiesScore: 4,
		hearingLossGrade: 'Mild',
		currentAidStatus: 'None',
		referralType: 'Routine',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		hhiesScore: 18,
		hearingLossGrade: 'Moderate',
		currentAidStatus: 'BTE bilateral',
		referralType: 'Follow-up',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		hhiesScore: 32,
		hearingLossGrade: 'Severe',
		currentAidStatus: 'BTE left only',
		referralType: 'Urgent',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		hhiesScore: 0,
		hearingLossGrade: 'Normal',
		currentAidStatus: 'None',
		referralType: 'Screening',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		hhiesScore: 36,
		hearingLossGrade: 'Profound',
		currentAidStatus: 'CIC bilateral',
		referralType: 'Cochlear implant evaluation',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		hhiesScore: 8,
		hearingLossGrade: 'Mild',
		currentAidStatus: 'None',
		referralType: 'Routine',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		hhiesScore: 22,
		hearingLossGrade: 'Moderate',
		currentAidStatus: 'RIC bilateral',
		referralType: 'Reprogramming',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		hhiesScore: 14,
		hearingLossGrade: 'Mild',
		currentAidStatus: 'RIC right only',
		referralType: 'Follow-up',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		hhiesScore: 28,
		hearingLossGrade: 'Severe',
		currentAidStatus: 'BTE bilateral',
		referralType: 'Upgrade assessment',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		hhiesScore: 2,
		hearingLossGrade: 'Normal',
		currentAidStatus: 'None',
		referralType: 'Screening',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		hhiesScore: 16,
		hearingLossGrade: 'Moderate',
		currentAidStatus: 'ITE left only',
		referralType: 'Bilateral fitting',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		hhiesScore: 40,
		hearingLossGrade: 'Profound',
		currentAidStatus: 'BTE bilateral',
		referralType: 'Cochlear implant evaluation',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		hhiesScore: 6,
		hearingLossGrade: 'Mild',
		currentAidStatus: 'None',
		referralType: 'Routine',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		hhiesScore: 24,
		hearingLossGrade: 'Moderate',
		currentAidStatus: 'None',
		referralType: 'First fitting',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		hhiesScore: 10,
		hearingLossGrade: 'Mild',
		currentAidStatus: 'RIC bilateral',
		referralType: 'Follow-up',
	},
];
