import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		firstName: 'John',
		lastName: 'Smith',
		dob: '1968-03-15',
		eligibilityStatus: 'Eligible',
		primaryIndication: 'Type 2 Diabetes',
		bmi: 32.4,
		currentDose: '1 mg weekly',
		reviewStatus: 'Complete',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		firstName: 'Priya',
		lastName: 'Patel',
		dob: '1975-07-22',
		eligibilityStatus: 'Eligible',
		primaryIndication: 'Weight Management',
		bmi: 35.1,
		currentDose: '0.5 mg weekly',
		reviewStatus: 'Complete',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		firstName: 'Margaret',
		lastName: 'Jones',
		dob: '1952-11-08',
		eligibilityStatus: 'Conditional',
		primaryIndication: 'Type 2 Diabetes',
		bmi: 29.8,
		currentDose: '0.25 mg weekly',
		reviewStatus: 'Pending Review',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		firstName: 'David',
		lastName: 'Williams',
		dob: '1980-01-30',
		eligibilityStatus: 'Eligible',
		primaryIndication: 'Weight Management',
		bmi: 38.6,
		currentDose: '2.4 mg weekly',
		reviewStatus: 'Complete',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		firstName: 'Sarah',
		lastName: 'Brown',
		dob: '1990-05-12',
		eligibilityStatus: 'Ineligible',
		primaryIndication: 'Weight Management',
		bmi: 24.2,
		currentDose: 'N/A',
		reviewStatus: 'Declined',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		firstName: 'James',
		lastName: 'Taylor',
		dob: '1965-09-18',
		eligibilityStatus: 'Eligible',
		primaryIndication: 'Cardiovascular Risk Reduction',
		bmi: 31.0,
		currentDose: '1 mg weekly',
		reviewStatus: 'Complete',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		firstName: 'Helen',
		lastName: 'Davies',
		dob: '1988-12-03',
		eligibilityStatus: 'Conditional',
		primaryIndication: 'Type 2 Diabetes',
		bmi: 33.5,
		currentDose: '0.5 mg weekly',
		reviewStatus: 'Pending Review',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		firstName: 'Robert',
		lastName: 'Wilson',
		dob: '1958-06-25',
		eligibilityStatus: 'Eligible',
		primaryIndication: 'Type 2 Diabetes',
		bmi: 30.2,
		currentDose: '1 mg weekly',
		reviewStatus: 'Complete',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		firstName: 'Catherine',
		lastName: 'Evans',
		dob: '1972-04-14',
		eligibilityStatus: 'Conditional',
		primaryIndication: 'Weight Management',
		bmi: 41.3,
		currentDose: '0.25 mg weekly',
		reviewStatus: 'Pending Review',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		firstName: 'Michael',
		lastName: 'Thomas',
		dob: '1983-08-07',
		eligibilityStatus: 'Eligible',
		primaryIndication: 'Type 2 Diabetes',
		bmi: 28.9,
		currentDose: '0.5 mg weekly',
		reviewStatus: 'Complete',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		firstName: 'Emma',
		lastName: 'Robinson',
		dob: '1995-02-28',
		eligibilityStatus: 'Ineligible',
		primaryIndication: 'Weight Management',
		bmi: 22.1,
		currentDose: 'N/A',
		reviewStatus: 'Declined',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		firstName: 'George',
		lastName: 'Clark',
		dob: '1960-10-19',
		eligibilityStatus: 'Eligible',
		primaryIndication: 'Cardiovascular Risk Reduction',
		bmi: 34.7,
		currentDose: '1 mg weekly',
		reviewStatus: 'Complete',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		firstName: 'Susan',
		lastName: 'Walker',
		dob: '1977-07-01',
		eligibilityStatus: 'Conditional',
		primaryIndication: 'Type 2 Diabetes',
		bmi: 36.2,
		currentDose: '0.5 mg weekly',
		reviewStatus: 'Awaiting Labs',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		firstName: 'Richard',
		lastName: 'Hall',
		dob: '1945-03-22',
		eligibilityStatus: 'Conditional',
		primaryIndication: 'Type 2 Diabetes',
		bmi: 27.5,
		currentDose: '0.25 mg weekly',
		reviewStatus: 'Pending Review',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		firstName: 'Elizabeth',
		lastName: 'Young',
		dob: '1986-11-15',
		eligibilityStatus: 'Eligible',
		primaryIndication: 'Weight Management',
		bmi: 33.8,
		currentDose: '1.7 mg weekly',
		reviewStatus: 'Complete',
	},
];
