#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding attention-deficit-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    age:int \
    sex:string! \
    ethnicity:string! \
    occupation:string! \
    education_level:string! \
    marital_status:string! \
    referring_clinician:string! \
    referral_reason:text! \
    --htmx

cargo loco generate scaffold assessment_asrs_part_a \
    assessment:references \
    q1_wrapping_up_details:int \
    q2_difficulty_ordering:int \
    q3_remembering_appointments:int \
    q4_avoiding_starting:int \
    q5_fidgeting:int \
    q6_feeling_overly_active:int \
    darkly_shaded_count:int \
    --htmx

cargo loco generate scaffold assessment_asrs_part_b \
    assessment:references \
    q7_careless_mistakes:int \
    q8_difficulty_sustaining_attention:int \
    q9_difficulty_listening:int \
    q10_difficulty_following_through:int \
    q11_difficulty_keeping_quiet:int \
    q12_finishing_others_sentences:int \
    q13_difficulty_waiting_turn:int \
    q14_interrupting_others:int \
    q15_always_on_the_go:int \
    q16_difficulty_relaxing:int \
    q17_talking_too_much:int \
    q18_losing_things:int \
    --htmx

cargo loco generate scaffold assessment_childhood_history \
    assessment:references \
    symptoms_present_before_age_12:string! \
    childhood_academic_difficulties:string! \
    childhood_academic_details:text! \
    childhood_behavioural_problems:string! \
    childhood_behavioural_details:text! \
    childhood_social_difficulties:string! \
    previous_adhd_assessment:string! \
    previous_assessment_details:text! \
    school_reports_available:string! \
    informant_corroboration:string! \
    informant_details:text! \
    --htmx

cargo loco generate scaffold assessment_functional_impact \
    assessment:references \
    impact_on_work:string! \
    work_impact_details:text! \
    impact_on_education:string! \
    education_impact_details:text! \
    impact_on_relationships:string! \
    relationship_impact_details:text! \
    impact_on_daily_tasks:string! \
    daily_tasks_impact_details:text! \
    impact_on_finances:string! \
    impact_on_self_esteem:string! \
    driving_concerns:string! \
    overall_functional_impairment:text! \
    --htmx

cargo loco generate scaffold assessment_comorbid_conditions \
    assessment:references \
    has_anxiety:string! \
    has_depression:string! \
    has_bipolar_disorder:string! \
    has_autism_spectrum:string! \
    has_learning_disability:string! \
    has_substance_use_disorder:string! \
    substance_use_details:text! \
    has_sleep_disorder:string! \
    sleep_disorder_details:text! \
    has_personality_disorder:string! \
    has_eating_disorder:string! \
    has_tic_disorder:string! \
    other_comorbidities:text! \
    --htmx

cargo loco generate scaffold assessment_current_medications \
    assessment:references \
    currently_on_adhd_medication:string! \
    adhd_medication_name:string! \
    adhd_medication_dose:string! \
    adhd_medication_duration:text! \
    adhd_medication_response:string! \
    previous_adhd_medications:text! \
    previous_medication_side_effects:text! \
    other_psychiatric_medications:text! \
    other_regular_medications:text! \
    cardiovascular_history:string! \
    cardiovascular_details:text! \
    blood_pressure_checked:string! \
    --htmx

cargo loco generate scaffold assessment_allergies \
    assessment:references \
    has_drug_allergies:string! \
    drug_allergy_details:text! \
    has_food_allergies:string! \
    food_allergy_details:text! \
    has_other_allergies:string! \
    other_allergy_details:text! \
    --htmx

cargo loco generate scaffold assessment_medical_history \
    assessment:references \
    has_head_injury_history:string! \
    head_injury_details:text! \
    has_seizure_history:string! \
    seizure_details:text! \
    has_thyroid_disorder:string! \
    thyroid_details:text! \
    has_cardiac_conditions:string! \
    cardiac_details:text! \
    birth_complications:string! \
    birth_complication_details:text! \
    family_history_of_adhd:string! \
    family_adhd_details:text! \
    family_psychiatric_history:text! \
    other_medical_history:text! \
    --htmx

cargo loco generate scaffold assessment_social_support \
    assessment:references \
    living_situation:string! \
    employment_status:string! \
    has_support_network:string! \
    support_network_details:text! \
    coping_strategies:text! \
    risk_taking_behaviour:string! \
    risk_behaviour_details:text! \
    legal_issues:string! \
    legal_details:text! \
    caffeine_use:text! \
    alcohol_use:text! \
    recreational_drug_use:text! \
    goals_for_treatment:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    part_a_darkly_shaded_count:int \
    screening_result:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    screening_result:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
