//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "breast_screening_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub eligibility_status: String,
    pub result_class: String,
    pub management_action: String,
    pub status: String,
    pub graded_at: DateTimeWithTimeZone,
    pub breast_screening_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::breast_screening_grade_flags::Entity")]
    BreastScreeningGradeFlags,
    #[sea_orm(has_many = "super::breast_screening_grade_rules::Entity")]
    BreastScreeningGradeRules,
    #[sea_orm(
        belongs_to = "super::breast_screenings::Entity",
        from = "Column::BreastScreeningId",
        to = "super::breast_screenings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BreastScreenings,
}

impl Related<super::breast_screening_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BreastScreeningGradeFlags.def()
    }
}

impl Related<super::breast_screening_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BreastScreeningGradeRules.def()
    }
}

impl Related<super::breast_screenings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BreastScreenings.def()
    }
}
