//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Model.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "inpatient_clinical_note_problems")]
pub struct Model {
    /// Created at.
    pub created_at: DateTimeWithTimeZone,
    /// Updated at.
    pub updated_at: DateTimeWithTimeZone,
    /// ID.
    #[sea_orm(primary_key)]
    pub id: i64,
    /// Deleted at.
    pub deleted_at: Option<DateTimeWithTimeZone>,
    /// Sort order.
    pub sort_order: i32,
    /// Problem.
    pub problem: String,
    /// Category.
    pub category: String,
    /// Status.
    pub status: String,
    /// Priority.
    pub priority: String,
    /// Onset date.
    pub onset_date: Option<Date>,
    /// Snomed code.
    pub snomed_code: String,
    /// Progress commentary.
    #[sea_orm(column_type = "Text")]
    pub progress_commentary: String,
    /// Inpatient clinical note ID.
    pub inpatient_clinical_note_id: i64,
}

/// Relation.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inpatient_clinical_notes::Entity",
        from = "Column::InpatientClinicalNoteId",
        to = "super::inpatient_clinical_notes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Inpatient clinical notes.
    InpatientClinicalNotes,
}

impl Related<super::inpatient_clinical_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InpatientClinicalNotes.def()
    }
}
