//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Model.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "inpatient_clinical_notes")]
pub struct Model {
    /// Created at.
    pub created_at: DateTimeWithTimeZone,
    /// Updated at.
    pub updated_at: DateTimeWithTimeZone,
    /// ID.
    #[sea_orm(primary_key)]
    pub id: i64,
    /// Deleted at.
    pub deleted_at: Option<DateTimeWithTimeZone>,
    /// Status.
    pub status: String,
    /// Note type.
    pub note_type: String,
    /// Hospital name.
    pub hospital_name: String,
    /// Ward name.
    pub ward_name: String,
    /// Bed number.
    pub bed_number: String,
    /// Note at.
    pub note_at: Option<DateTimeWithTimeZone>,
    /// Author name.
    pub author_name: String,
    /// Author grade.
    pub author_grade: String,
    /// Author registration number.
    pub author_registration_number: String,
    /// Parent specialty.
    pub parent_specialty: String,
    /// Responsible consultant name.
    pub responsible_consultant_name: String,
    /// Consult question.
    #[sea_orm(column_type = "Text")]
    pub consult_question: String,
    /// Consult requesting team.
    pub consult_requesting_team: String,
    /// Procedure performed.
    pub procedure_performed: String,
    /// Procedure detail.
    #[sea_orm(column_type = "Text")]
    pub procedure_detail: String,
    /// Procedure consent.
    pub procedure_consent: String,
    /// Procedure complications.
    #[sea_orm(column_type = "Text")]
    pub procedure_complications: String,
    /// Transfer from ward.
    pub transfer_from_ward: String,
    /// Transfer to ward.
    pub transfer_to_ward: String,
    /// Transfer reason.
    #[sea_orm(column_type = "Text")]
    pub transfer_reason: String,
    /// Admission at.
    pub admission_at: Option<DateTimeWithTimeZone>,
    /// Admitting specialty.
    pub admitting_specialty: String,
    /// Admission method.
    pub admission_method: String,
    /// Admission reason.
    #[sea_orm(column_type = "Text")]
    pub admission_reason: String,
    /// Interval history.
    #[sea_orm(column_type = "Text")]
    pub interval_history: String,
    /// No interval events.
    pub no_interval_events: String,
    /// Overnight events.
    #[sea_orm(column_type = "Text")]
    pub overnight_events: String,
    /// Patient reported symptoms.
    #[sea_orm(column_type = "Text")]
    pub patient_reported_symptoms: String,
    /// Nursing concerns.
    #[sea_orm(column_type = "Text")]
    pub nursing_concerns: String,
    /// Pain score.
    pub pain_score: Option<i32>,
    /// Sleep quality.
    pub sleep_quality: String,
    /// Oral intake.
    pub oral_intake: String,
    /// Bowels last opened.
    pub bowels_last_opened: Option<Date>,
    /// Mobility status.
    pub mobility_status: String,
    /// Observed at.
    pub observed_at: Option<DateTimeWithTimeZone>,
    /// Respiratory rate.
    pub respiratory_rate: Option<i32>,
    /// Oxygen saturation.
    pub oxygen_saturation: Option<i32>,
    /// Spo2 scale.
    pub spo2_scale: String,
    /// Oxygen delivery.
    pub oxygen_delivery: String,
    /// Oxygen flow litres per minute.
    pub oxygen_flow_litres_per_minute: Option<Decimal>,
    /// Systolic blood pressure.
    pub systolic_blood_pressure: Option<i32>,
    /// Diastolic blood pressure.
    pub diastolic_blood_pressure: Option<i32>,
    /// Pulse rate.
    pub pulse_rate: Option<i32>,
    /// Acvpu.
    pub acvpu: String,
    /// Temperature celsius.
    pub temperature_celsius: Option<Decimal>,
    /// News2 total.
    pub news2_total: Option<i32>,
    /// News2 derived total.
    pub news2_derived_total: Option<i32>,
    /// News2 trend.
    pub news2_trend: String,
    /// News2 applicable.
    pub news2_applicable: String,
    /// News2 not applicable reason.
    pub news2_not_applicable_reason: String,
    /// Examination general.
    #[sea_orm(column_type = "Text")]
    pub examination_general: String,
    /// Examination cardiovascular.
    #[sea_orm(column_type = "Text")]
    pub examination_cardiovascular: String,
    /// Examination respiratory.
    #[sea_orm(column_type = "Text")]
    pub examination_respiratory: String,
    /// Examination abdominal.
    #[sea_orm(column_type = "Text")]
    pub examination_abdominal: String,
    /// Examination neurological.
    #[sea_orm(column_type = "Text")]
    pub examination_neurological: String,
    /// Examination musculoskeletal.
    #[sea_orm(column_type = "Text")]
    pub examination_musculoskeletal: String,
    /// Examination skin and wounds.
    #[sea_orm(column_type = "Text")]
    pub examination_skin_and_wounds: String,
    /// Examination lines and drains.
    #[sea_orm(column_type = "Text")]
    pub examination_lines_and_drains: String,
    /// Examination other.
    #[sea_orm(column_type = "Text")]
    pub examination_other: String,
    /// No investigations reviewed.
    pub no_investigations_reviewed: String,
    /// No medication changes.
    pub no_medication_changes: String,
    /// Allergy checked.
    pub allergy_checked: String,
    /// Medicines reconciliation status.
    pub medicines_reconciliation_status: String,
    /// Antimicrobial review status.
    pub antimicrobial_review_status: String,
    /// Antimicrobial review at.
    pub antimicrobial_review_at: Option<DateTimeWithTimeZone>,
    /// Vte status.
    pub vte_status: String,
    /// Vte prophylaxis.
    pub vte_prophylaxis: String,
    /// Vte assessed at.
    pub vte_assessed_at: Option<DateTimeWithTimeZone>,
    /// Vte notes.
    #[sea_orm(column_type = "Text")]
    pub vte_notes: String,
    /// Falls risk.
    pub falls_risk: String,
    /// Falls interventions.
    #[sea_orm(column_type = "Text")]
    pub falls_interventions: String,
    /// Pressure ulcer risk.
    pub pressure_ulcer_risk: String,
    /// Skin integrity.
    pub skin_integrity: String,
    /// Pressure ulcer grade.
    pub pressure_ulcer_grade: String,
    /// Pressure ulcer sites.
    pub pressure_ulcer_sites: String,
    /// Delirium screen.
    pub delirium_screen: String,
    /// Delirium 4at score.
    pub delirium_4at_score: Option<i32>,
    /// Delirium notes.
    #[sea_orm(column_type = "Text")]
    pub delirium_notes: String,
    /// Nutrition screen.
    pub nutrition_screen: String,
    /// Must score.
    pub must_score: Option<i32>,
    /// Nutrition plan.
    #[sea_orm(column_type = "Text")]
    pub nutrition_plan: String,
    /// Infection status.
    pub infection_status: String,
    /// Isolation status.
    pub isolation_status: String,
    /// Organism.
    pub organism: String,
    /// Infection precautions.
    #[sea_orm(column_type = "Text")]
    pub infection_precautions: String,
    /// Safeguarding concern.
    pub safeguarding_concern: String,
    /// Safeguarding notes.
    #[sea_orm(column_type = "Text")]
    pub safeguarding_notes: String,
    /// Safeguarding referral made.
    pub safeguarding_referral_made: String,
    /// Clinical impression.
    #[sea_orm(column_type = "Text")]
    pub clinical_impression: String,
    /// Differential diagnosis.
    #[sea_orm(column_type = "Text")]
    pub differential_diagnosis: String,
    /// Response to treatment.
    pub response_to_treatment: String,
    /// New oxygen requirement.
    pub new_oxygen_requirement: String,
    /// New confusion.
    pub new_confusion: String,
    /// Sepsis screen.
    pub sepsis_screen: String,
    /// Arrest call.
    pub arrest_call: String,
    /// Critical care referral.
    pub critical_care_referral: String,
    /// New organ support.
    pub new_organ_support: String,
    /// Plan.
    #[sea_orm(column_type = "Text")]
    pub plan: String,
    /// Escalation status.
    pub escalation_status: String,
    /// Escalation action.
    #[sea_orm(column_type = "Text")]
    pub escalation_action: String,
    /// Ceiling of care.
    pub ceiling_of_care: String,
    /// Respect status.
    pub respect_status: String,
    /// Dnacpr status.
    pub dnacpr_status: String,
    /// Senior review needed.
    pub senior_review_needed: String,
    /// Senior review by.
    pub senior_review_by: String,
    /// Senior review at.
    pub senior_review_at: Option<DateTimeWithTimeZone>,
    /// Estimated discharge date.
    pub estimated_discharge_date: Option<Date>,
    /// Discharge planning notes.
    #[sea_orm(column_type = "Text")]
    pub discharge_planning_notes: String,
    /// Family communication.
    #[sea_orm(column_type = "Text")]
    pub family_communication: String,
    /// Patient communication.
    #[sea_orm(column_type = "Text")]
    pub patient_communication: String,
    /// Team handover.
    #[sea_orm(column_type = "Text")]
    pub team_handover: String,
    /// Consent status.
    pub consent_status: String,
    /// Capacity assessed.
    pub capacity_assessed: String,
    /// Capacity notes.
    #[sea_orm(column_type = "Text")]
    pub capacity_notes: String,
    /// Author override acuity.
    pub author_override_acuity: String,
    /// Author override reason.
    #[sea_orm(column_type = "Text")]
    pub author_override_reason: String,
    /// Attestation text.
    #[sea_orm(column_type = "Text")]
    pub attestation_text: String,
    /// Electronic signature.
    #[sea_orm(column_type = "Text")]
    pub electronic_signature: String,
    /// Signed at.
    pub signed_at: Option<DateTimeWithTimeZone>,
    /// Patient ID.
    pub patient_id: i64,
    /// Author ID.
    pub author_id: i64,
    /// Responsible consultant ID.
    pub responsible_consultant_id: i64,
}

/// Relation.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Inpatient clinical note grades.
    #[sea_orm(has_many = "super::inpatient_clinical_note_grades::Entity")]
    InpatientClinicalNoteGrades,
    /// Inpatient clinical note investigations.
    #[sea_orm(has_many = "super::inpatient_clinical_note_investigations::Entity")]
    InpatientClinicalNoteInvestigations,
    /// Inpatient clinical note jobs.
    #[sea_orm(has_many = "super::inpatient_clinical_note_jobs::Entity")]
    InpatientClinicalNoteJobs,
    /// Inpatient clinical note medication changes.
    #[sea_orm(has_many = "super::inpatient_clinical_note_medication_changes::Entity")]
    InpatientClinicalNoteMedicationChanges,
    /// Inpatient clinical note problems.
    #[sea_orm(has_many = "super::inpatient_clinical_note_problems::Entity")]
    InpatientClinicalNoteProblems,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Patients.
    Patients,
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::AuthorId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Clinicians.
    Clinicians,
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ResponsibleConsultantId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Clinicians.
    ResponsibleConsultant,
}

impl Related<super::inpatient_clinical_note_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InpatientClinicalNoteGrades.def()
    }
}

impl Related<super::inpatient_clinical_note_investigations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InpatientClinicalNoteInvestigations.def()
    }
}

impl Related<super::inpatient_clinical_note_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InpatientClinicalNoteJobs.def()
    }
}

impl Related<super::inpatient_clinical_note_medication_changes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InpatientClinicalNoteMedicationChanges.def()
    }
}

impl Related<super::inpatient_clinical_note_problems::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InpatientClinicalNoteProblems.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}
