-- ============================================================
-- 01_patient.sql
-- Root entity: a unique individual in the system.
-- ============================================================
-- A patient can have many casualty card records over time
-- (e.g. for different ED attendances). Identity data lives
-- here; clinical data lives in the casualty card tables.
-- ============================================================

CREATE TABLE patient (
    -- Primary key: UUIDv4 generated by the database
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Patient identity
    first_name            TEXT NOT NULL DEFAULT '',
    last_name             TEXT NOT NULL DEFAULT '',
    date_of_birth         DATE,

    -- Biological sex
    sex                   TEXT NOT NULL DEFAULT ''
                          CHECK (sex IN ('male', 'female', 'other', '')),

    -- NHS number (10-digit unique identifier)
    nhs_number            TEXT NOT NULL DEFAULT '',

    -- Contact details
    address               TEXT NOT NULL DEFAULT '',
    postcode              TEXT NOT NULL DEFAULT '',
    phone                 TEXT NOT NULL DEFAULT '',
    email                 TEXT NOT NULL DEFAULT '',

    -- Demographics
    ethnicity             TEXT NOT NULL DEFAULT '',
    preferred_language    TEXT NOT NULL DEFAULT '',
    interpreter_required  TEXT NOT NULL DEFAULT ''
                          CHECK (interpreter_required IN ('yes', 'no', '')),

    -- Audit timestamps
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for NHS number lookups
CREATE INDEX idx_patient_nhs_number ON patient(nhs_number);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Root entity representing a unique individual. Identity data only; clinical data is per-casualty-card.';
COMMENT ON COLUMN patient.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN patient.first_name IS
    'Patient given name.';
COMMENT ON COLUMN patient.last_name IS
    'Patient family name.';
COMMENT ON COLUMN patient.date_of_birth IS
    'Date of birth. NULL if not recorded.';
COMMENT ON COLUMN patient.sex IS
    'Biological sex: male, female, other, or empty string if unanswered.';
COMMENT ON COLUMN patient.nhs_number IS
    'NHS number, a 10-digit unique patient identifier used across the NHS.';
COMMENT ON COLUMN patient.address IS
    'Patient home address.';
COMMENT ON COLUMN patient.postcode IS
    'Patient postcode.';
COMMENT ON COLUMN patient.phone IS
    'Patient phone number.';
COMMENT ON COLUMN patient.email IS
    'Patient email address.';
COMMENT ON COLUMN patient.ethnicity IS
    'Patient ethnicity as self-reported.';
COMMENT ON COLUMN patient.preferred_language IS
    'Patient preferred language for communication.';
COMMENT ON COLUMN patient.interpreter_required IS
    'Whether an interpreter is required: yes, no, or empty string if unanswered.';
COMMENT ON COLUMN patient.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN patient.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
