-- ============================================================
-- 04_casualty_card_next_of_kin.sql
-- Next of kin details (1:1 with casualty_card).
-- ============================================================
-- Records the patient's nominated next of kin and whether
-- they have been notified of the attendance.
-- ============================================================

CREATE TABLE casualty_card_next_of_kin (
    -- Primary key: UUIDv4 generated by the database
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- 1:1 relationship with casualty_card (UNIQUE constraint)
    casualty_card_id  UUID NOT NULL UNIQUE REFERENCES casualty_card(id) ON DELETE CASCADE,

    -- Next of kin details
    name              TEXT NOT NULL DEFAULT '',
    relationship      TEXT NOT NULL DEFAULT '',
    phone             TEXT NOT NULL DEFAULT '',
    notified          TEXT NOT NULL DEFAULT ''
                      CHECK (notified IN ('yes', 'no', '')),

    -- Audit timestamps
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_casualty_card_next_of_kin_updated_at
    BEFORE UPDATE ON casualty_card_next_of_kin
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE casualty_card_next_of_kin IS
    '1:1 with casualty_card. Next of kin contact details and notification status.';
COMMENT ON COLUMN casualty_card_next_of_kin.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN casualty_card_next_of_kin.casualty_card_id IS
    'FK to casualty_card (UNIQUE = 1:1 relationship).';
COMMENT ON COLUMN casualty_card_next_of_kin.name IS
    'Full name of the next of kin.';
COMMENT ON COLUMN casualty_card_next_of_kin.relationship IS
    'Relationship to the patient (e.g. spouse, parent, sibling).';
COMMENT ON COLUMN casualty_card_next_of_kin.phone IS
    'Contact phone number for the next of kin.';
COMMENT ON COLUMN casualty_card_next_of_kin.notified IS
    'Whether the next of kin has been notified: yes, no, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_next_of_kin.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN casualty_card_next_of_kin.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
