-- ============================================================
-- 06_casualty_card_arrival_triage.sql
-- Arrival and triage details (1:1 with casualty_card).
-- ============================================================
-- Captures how the patient arrived, the referral source, and
-- the Manchester Triage System (MTS) assessment results.
-- ============================================================

CREATE TABLE casualty_card_arrival_triage (
    -- Primary key: UUIDv4 generated by the database
    id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- 1:1 relationship with casualty_card (UNIQUE constraint)
    casualty_card_id            UUID NOT NULL UNIQUE REFERENCES casualty_card(id) ON DELETE CASCADE,

    -- Attendance classification
    attendance_category         TEXT NOT NULL DEFAULT ''
                                CHECK (attendance_category IN ('first', 'follow-up', 'planned', 'unplanned', '')),

    -- Mode of arrival
    arrival_mode                TEXT NOT NULL DEFAULT ''
                                CHECK (arrival_mode IN ('ambulance', 'walk-in', 'helicopter', 'police', 'other', '')),

    -- Referral source
    referral_source             TEXT NOT NULL DEFAULT ''
                                CHECK (referral_source IN ('self', 'gp', '999', 'nhs111', 'other-hospital', 'police', 'other', '')),

    -- Ambulance incident reference
    ambulance_incident_number   TEXT NOT NULL DEFAULT '',

    -- Triage details
    triage_time                 TIMESTAMPTZ,
    triage_nurse                TEXT NOT NULL DEFAULT '',

    -- Manchester Triage System (MTS)
    mts_flowchart               TEXT NOT NULL DEFAULT '',
    mts_category                TEXT NOT NULL DEFAULT ''
                                CHECK (mts_category IN ('1-immediate', '2-very-urgent', '3-urgent', '4-standard', '5-non-urgent', '')),
    mts_discriminator           TEXT NOT NULL DEFAULT '',

    -- Audit timestamps
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_casualty_card_arrival_triage_updated_at
    BEFORE UPDATE ON casualty_card_arrival_triage
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE casualty_card_arrival_triage IS
    '1:1 with casualty_card. Arrival mode, referral source, and Manchester Triage System assessment.';
COMMENT ON COLUMN casualty_card_arrival_triage.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN casualty_card_arrival_triage.casualty_card_id IS
    'FK to casualty_card (UNIQUE = 1:1 relationship).';
COMMENT ON COLUMN casualty_card_arrival_triage.attendance_category IS
    'Attendance classification: first, follow-up, planned, unplanned, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_arrival_triage.arrival_mode IS
    'How the patient arrived: ambulance, walk-in, helicopter, police, other, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_arrival_triage.referral_source IS
    'Who referred the patient: self, gp, 999, nhs111, other-hospital, police, other, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_arrival_triage.ambulance_incident_number IS
    'Ambulance service incident reference number.';
COMMENT ON COLUMN casualty_card_arrival_triage.triage_time IS
    'Timestamp when triage was performed. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_arrival_triage.triage_nurse IS
    'Name of the triage nurse who assessed the patient.';
COMMENT ON COLUMN casualty_card_arrival_triage.mts_flowchart IS
    'Manchester Triage System flowchart used for triage assessment.';
COMMENT ON COLUMN casualty_card_arrival_triage.mts_category IS
    'MTS urgency category: 1-immediate, 2-very-urgent, 3-urgent, 4-standard, 5-non-urgent, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_arrival_triage.mts_discriminator IS
    'MTS discriminator that determined the triage category.';
COMMENT ON COLUMN casualty_card_arrival_triage.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN casualty_card_arrival_triage.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
