-- ============================================================
-- 08_casualty_card_pain_assessment.sql
-- Pain assessment (1:1 with casualty_card).
-- ============================================================
-- Structured pain assessment using the Numeric Rating Scale
-- (NRS 0-10) and descriptive characterisation.
-- ============================================================

CREATE TABLE casualty_card_pain_assessment (
    -- Primary key: UUIDv4 generated by the database
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- 1:1 relationship with casualty_card (UNIQUE constraint)
    casualty_card_id        UUID NOT NULL UNIQUE REFERENCES casualty_card(id) ON DELETE CASCADE,

    -- Pain presence
    pain_present            TEXT NOT NULL DEFAULT ''
                            CHECK (pain_present IN ('yes', 'no', '')),

    -- Numeric Rating Scale (0 = no pain, 10 = worst pain imaginable)
    pain_score              INTEGER
                            CHECK (pain_score IS NULL OR (pain_score >= 0 AND pain_score <= 10)),

    -- Pain characterisation
    pain_location           TEXT NOT NULL DEFAULT '',
    pain_character          TEXT NOT NULL DEFAULT '',
    pain_onset              TEXT NOT NULL DEFAULT '',

    -- Severity category
    pain_severity_category  TEXT NOT NULL DEFAULT ''
                            CHECK (pain_severity_category IN ('mild', 'moderate', 'severe', '')),

    -- Audit timestamps
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_casualty_card_pain_assessment_updated_at
    BEFORE UPDATE ON casualty_card_pain_assessment
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE casualty_card_pain_assessment IS
    '1:1 with casualty_card. Structured pain assessment using NRS and descriptive characterisation.';
COMMENT ON COLUMN casualty_card_pain_assessment.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN casualty_card_pain_assessment.casualty_card_id IS
    'FK to casualty_card (UNIQUE = 1:1 relationship).';
COMMENT ON COLUMN casualty_card_pain_assessment.pain_present IS
    'Whether pain is present: yes, no, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_pain_assessment.pain_score IS
    'Numeric Rating Scale 0-10 (0 = no pain, 10 = worst pain imaginable). NULL if not assessed.';
COMMENT ON COLUMN casualty_card_pain_assessment.pain_location IS
    'Anatomical location of the pain.';
COMMENT ON COLUMN casualty_card_pain_assessment.pain_character IS
    'Nature of the pain (e.g. sharp, dull, burning, throbbing).';
COMMENT ON COLUMN casualty_card_pain_assessment.pain_onset IS
    'When the pain started.';
COMMENT ON COLUMN casualty_card_pain_assessment.pain_severity_category IS
    'Severity category: mild, moderate, severe, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_pain_assessment.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN casualty_card_pain_assessment.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
