-- ============================================================
-- 15_casualty_card_investigations.sql
-- Investigations ordered and results (1:1 with casualty_card).
-- ============================================================
-- Records blood tests, urinalysis, imaging, ECG, and other
-- investigations requested during the ED attendance.
-- Blood tests use a TEXT[] array for selected test types.
-- ============================================================

CREATE TABLE casualty_card_investigations (
    -- Primary key: UUIDv4 generated by the database
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- 1:1 relationship with casualty_card (UNIQUE constraint)
    casualty_card_id        UUID NOT NULL UNIQUE REFERENCES casualty_card(id) ON DELETE CASCADE,

    -- Blood tests (array of selected test types, e.g. FBC, U&E, LFTs, CRP, troponin)
    blood_tests             TEXT[] NOT NULL DEFAULT '{}',

    -- Urinalysis
    urinalysis              TEXT NOT NULL DEFAULT '',
    pregnancy_test          TEXT NOT NULL DEFAULT '',

    -- ECG
    ecg_performed           TEXT NOT NULL DEFAULT ''
                            CHECK (ecg_performed IN ('yes', 'no', '')),
    ecg_findings            TEXT NOT NULL DEFAULT '',

    -- Other investigations
    other_investigations    TEXT NOT NULL DEFAULT '',

    -- Audit timestamps
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_casualty_card_investigations_updated_at
    BEFORE UPDATE ON casualty_card_investigations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE casualty_card_investigations IS
    '1:1 with casualty_card. Investigations ordered and their results.';
COMMENT ON COLUMN casualty_card_investigations.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN casualty_card_investigations.casualty_card_id IS
    'FK to casualty_card (UNIQUE = 1:1 relationship).';
COMMENT ON COLUMN casualty_card_investigations.blood_tests IS
    'Array of blood test types ordered (e.g. FBC, U&E, LFTs, CRP, coagulation, troponin).';
COMMENT ON COLUMN casualty_card_investigations.urinalysis IS
    'Urinalysis dipstick results.';
COMMENT ON COLUMN casualty_card_investigations.pregnancy_test IS
    'Pregnancy test result.';
COMMENT ON COLUMN casualty_card_investigations.ecg_performed IS
    'Whether an ECG was performed: yes, no, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_investigations.ecg_findings IS
    'ECG interpretation findings.';
COMMENT ON COLUMN casualty_card_investigations.other_investigations IS
    'Free-text description of other investigations performed.';
COMMENT ON COLUMN casualty_card_investigations.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN casualty_card_investigations.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
