-- ============================================================
-- 16_casualty_card_treatment.sql
-- Treatment and interventions summary (1:1 with casualty_card).
-- ============================================================
-- Records oxygen therapy and tetanus prophylaxis status.
-- Note: medications administered, fluid therapy, and
-- procedures are separate many-to-one tables.
-- ============================================================

CREATE TABLE casualty_card_treatment (
    -- Primary key: UUIDv4 generated by the database
    id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- 1:1 relationship with casualty_card (UNIQUE constraint)
    casualty_card_id          UUID NOT NULL UNIQUE REFERENCES casualty_card(id) ON DELETE CASCADE,

    -- Oxygen therapy
    oxygen_therapy_device     TEXT NOT NULL DEFAULT '',
    oxygen_therapy_flow_rate  TEXT NOT NULL DEFAULT '',

    -- Tetanus prophylaxis
    tetanus_prophylaxis       TEXT NOT NULL DEFAULT ''
                              CHECK (tetanus_prophylaxis IN ('given', 'not-indicated', 'status-checked', '')),

    -- Audit timestamps
    created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_casualty_card_treatment_updated_at
    BEFORE UPDATE ON casualty_card_treatment
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE casualty_card_treatment IS
    '1:1 with casualty_card. Oxygen therapy and tetanus prophylaxis. Medications, fluids, and procedures are separate tables.';
COMMENT ON COLUMN casualty_card_treatment.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN casualty_card_treatment.casualty_card_id IS
    'FK to casualty_card (UNIQUE = 1:1 relationship).';
COMMENT ON COLUMN casualty_card_treatment.oxygen_therapy_device IS
    'Oxygen delivery device (e.g. nasal cannula, simple face mask, non-rebreather mask).';
COMMENT ON COLUMN casualty_card_treatment.oxygen_therapy_flow_rate IS
    'Oxygen flow rate (e.g. 2L/min, 15L/min).';
COMMENT ON COLUMN casualty_card_treatment.tetanus_prophylaxis IS
    'Tetanus prophylaxis status: given, not-indicated, status-checked, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_treatment.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN casualty_card_treatment.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
