//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "wells_score_for_pulmonary_embolism_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Double", nullable)]
    pub wells_score: Option<f64>,
    pub two_level_band: String,
    pub three_level_band: String,
    #[sea_orm(column_type = "Text")]
    pub recommended_pathway: String,
    pub graded_at: DateTimeWithTimeZone,
    pub wells_score_for_pulmonary_embolism_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::wells_score_for_pulmonary_embolism_grade_flags::Entity")]
    WellsScoreForPulmonaryEmbolismGradeFlags,
    #[sea_orm(has_many = "super::wells_score_for_pulmonary_embolism_grade_rules::Entity")]
    WellsScoreForPulmonaryEmbolismGradeRules,
    #[sea_orm(
        belongs_to = "super::wells_score_for_pulmonary_embolisms::Entity",
        from = "Column::WellsScoreForPulmonaryEmbolismId",
        to = "super::wells_score_for_pulmonary_embolisms::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    WellsScoreForPulmonaryEmbolisms,
}

impl Related<super::wells_score_for_pulmonary_embolism_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WellsScoreForPulmonaryEmbolismGradeFlags.def()
    }
}

impl Related<super::wells_score_for_pulmonary_embolism_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WellsScoreForPulmonaryEmbolismGradeRules.def()
    }
}

impl Related<super::wells_score_for_pulmonary_embolisms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WellsScoreForPulmonaryEmbolisms.def()
    }
}
