#!/bin/sh
# cargo-loco-generate/cargo-loco-generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding first-aid-training-checklist (6 tables)..."

cargo loco generate scaffold patient \
    deleted_at:ts \
    name:string! \
    birth_date:date \
    united_kingdom_nhs_number:string^ \
    waist_as_cm:double \
    height_as_cm:double \
    weight_as_kg:double \
    body_mass_index:double \
    waist_height_ratio:double \
    vo2_max:double \
    --htmx && \
cargo loco generate scaffold clinician \
    deleted_at:ts \
    name:text! \
    role:text! \
    registration_body:text! \
    registration_number:text! \
    united_kingdom_nhs_number:string^ \
    --htmx && \
cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx && \
cargo loco generate scaffold grading_result \
    assessment:references \
    result_category:string! \
    result_score:double \
    result_notes:text! \
    graded_at:ts! \
    --htmx && \
cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx && \
cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    description:text! \
    priority:string! \
    --htmx

echo "Done."
