//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "apgar_score_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub total_one_minute: Option<i32>,
    pub total_five_minute: Option<i32>,
    pub total_ten_minute: Option<i32>,
    pub band_one_minute: String,
    pub band_five_minute: String,
    pub band_ten_minute: String,
    pub summary_band: String,
    pub trend: String,
    pub graded_at: DateTimeWithTimeZone,
    pub apgar_score_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::apgar_score_grade_flags::Entity")]
    ApgarScoreGradeFlags,
    #[sea_orm(has_many = "super::apgar_score_grade_rules::Entity")]
    ApgarScoreGradeRules,
    #[sea_orm(
        belongs_to = "super::apgar_scores::Entity",
        from = "Column::ApgarScoreId",
        to = "super::apgar_scores::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ApgarScores,
}

impl Related<super::apgar_score_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApgarScoreGradeFlags.def()
    }
}

impl Related<super::apgar_score_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApgarScoreGradeRules.def()
    }
}

impl Related<super::apgar_scores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApgarScores.def()
    }
}
