//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "agile_checklist_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub answered_count: i32,
    pub teams_yes_count: i32,
    pub teams_applicable_count: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub teams_percent: Option<f64>,
    pub stakeholders_yes_count: i32,
    pub stakeholders_applicable_count: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub stakeholders_percent: Option<f64>,
    pub practices_yes_count: i32,
    pub practices_applicable_count: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub practices_percent: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub overall_percent: Option<f64>,
    pub teams_band: String,
    pub stakeholders_band: String,
    pub practices_band: String,
    pub maturity: String,
    pub top_action_1: String,
    pub top_action_2: String,
    pub top_action_3: String,
    #[sea_orm(column_type = "Text")]
    pub coach_notes: String,
    pub signed_at: Option<DateTimeWithTimeZone>,
    pub graded_at: DateTimeWithTimeZone,
    pub agile_checklist_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agile_checklist_grade_flags::Entity")]
    AgileChecklistGradeFlags,
    #[sea_orm(has_many = "super::agile_checklist_grade_rules::Entity")]
    AgileChecklistGradeRules,
    #[sea_orm(
        belongs_to = "super::agile_checklists::Entity",
        from = "Column::AgileChecklistId",
        to = "super::agile_checklists::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AgileChecklists,
}

impl Related<super::agile_checklist_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgileChecklistGradeFlags.def()
    }
}

impl Related<super::agile_checklist_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgileChecklistGradeRules.def()
    }
}

impl Related<super::agile_checklists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgileChecklists.def()
    }
}
