//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "nursing_care_plan_problems")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub problem_statement: String,
    pub adl_category: String,
    pub actual_or_potential: String,
    #[sea_orm(column_type = "Text")]
    pub assessment_data: String,
    pub linked_risk: String,
    #[sea_orm(column_type = "Text")]
    pub evaluation_note: String,
    pub goal_met: String,
    pub next_review_date: Option<Date>,
    pub nursing_care_plan_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::nursing_care_plan_goals::Entity")]
    NursingCarePlanGoals,
    #[sea_orm(has_many = "super::nursing_care_plan_interventions::Entity")]
    NursingCarePlanInterventions,
    #[sea_orm(
        belongs_to = "super::nursing_care_plans::Entity",
        from = "Column::NursingCarePlanId",
        to = "super::nursing_care_plans::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    NursingCarePlans,
}

impl Related<super::nursing_care_plan_goals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NursingCarePlanGoals.def()
    }
}

impl Related<super::nursing_care_plan_interventions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NursingCarePlanInterventions.def()
    }
}

impl Related<super::nursing_care_plans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NursingCarePlans.def()
    }
}
