//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "colonoscopy_test_requests")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub site_name: String,
    pub setting: String,
    pub referral_date: Option<Date>,
    pub requested_by_date: Option<Date>,
    pub procedure: String,
    pub primary_indication: String,
    pub clinical_question: String,
    pub relevant_history: String,
    pub red_flag_weight_loss: bool,
    pub red_flag_anaemia: bool,
    pub red_flag_abdominal_mass: bool,
    pub red_flag_rectal_bleeding: bool,
    #[sea_orm(column_type = "Double", nullable)]
    pub fit_result_ug_g: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub haemoglobin_g_l: Option<f64>,
    pub taking_anticoagulant: bool,
    pub anticoagulant_agent: String,
    pub taking_antiplatelet: bool,
    pub antiplatelet_agent: String,
    pub diabetes_medication: String,
    pub fit_for_bowel_prep: bool,
    pub bowel_prep_agent: String,
    pub chronic_kidney_disease: bool,
    #[sea_orm(column_type = "Double", nullable)]
    pub egfr_ml_min: Option<f64>,
    pub asa_grade: String,
    pub urgency: String,
    pub supervising_consultant: String,
    pub requester_contact: String,
    pub notes: String,
    pub patient_id: i64,
    pub clinician_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::colonoscopy_test_request_grades::Entity")]
    ColonoscopyTestRequestGrades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::colonoscopy_test_request_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColonoscopyTestRequestGrades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
