//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "return_to_work_restrictions")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub kind: String,
    pub severity: String,
    pub quantitative_limit: String,
    pub notes: String,
    pub start_date: Option<Date>,
    pub end_date: Option<Date>,
    pub priority_rank: i32,
    pub return_to_work_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::return_to_works::Entity",
        from = "Column::ReturnToWorkId",
        to = "super::return_to_works::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ReturnToWorks,
}

impl Related<super::return_to_works::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReturnToWorks.def()
    }
}
