//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "emergency_department_triage_notes")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub nurse_name: String,
    pub triaged_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    pub arrival_mode: String,
    pub arrived_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub referral_source: String,
    #[sea_orm(column_type = "Text")]
    pub patient_identifier: String,
    pub age_band: String,
    #[sea_orm(column_type = "Text")]
    pub presenting_complaint: String,
    #[sea_orm(column_type = "Text")]
    pub brief_history: String,
    #[sea_orm(column_type = "Text")]
    pub symptom_onset: String,
    pub respiratory_rate: Option<i32>,
    pub spo2: Option<i32>,
    pub on_oxygen: String,
    pub systolic_bp: Option<i32>,
    pub pulse: Option<i32>,
    pub consciousness_acvpu: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub temperature: Option<f64>,
    pub glasgow_coma_scale: Option<i32>,
    pub pain_score: Option<i32>,
    pub airway_threat: String,
    pub breathing_inadequate: String,
    pub circulation_shock: String,
    pub haemorrhage_major: String,
    pub consciousness_reduced: String,
    pub seizure_active: String,
    pub focal_neurology: String,
    pub sepsis_features: String,
    pub chest_pain_cardiac: String,
    pub stroke_features: String,
    pub paediatric_red_flag: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_notes: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::emergency_department_triage_note_grades::Entity")]
    EmergencyDepartmentTriageNoteGrades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::emergency_department_triage_note_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmergencyDepartmentTriageNoteGrades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
