CREATE TABLE assessment (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'reviewed', 'urgent')),
    full_name VARCHAR(255) NOT NULL DEFAULT '',
    address TEXT NOT NULL DEFAULT '',
    postcode VARCHAR(20) NOT NULL DEFAULT '',
    date_of_birth DATE,
    nhs_number VARCHAR(20) NOT NULL DEFAULT '',
    phone VARCHAR(30) NOT NULL DEFAULT '',
    email VARCHAR(255) NOT NULL DEFAULT '',
    gp_name VARCHAR(255) NOT NULL DEFAULT '',
    gp_practice VARCHAR(255) NOT NULL DEFAULT '',
    reason_for_statement TEXT NOT NULL DEFAULT '',
    current_health_status TEXT NOT NULL DEFAULT '',
    current_diagnoses TEXT NOT NULL DEFAULT '',
    has_discussed_with_family VARCHAR(5) NOT NULL DEFAULT '' CHECK (has_discussed_with_family IN ('yes', 'no', '')),
    has_discussed_with_clinician VARCHAR(5) NOT NULL DEFAULT '' CHECK (has_discussed_with_clinician IN ('yes', 'no', '')),
    discussion_details TEXT NOT NULL DEFAULT '',
    personal_values TEXT NOT NULL DEFAULT '',
    quality_of_life_priorities TEXT NOT NULL DEFAULT '',
    religious_beliefs TEXT NOT NULL DEFAULT '',
    spiritual_needs TEXT NOT NULL DEFAULT '',
    cultural_considerations TEXT NOT NULL DEFAULT '',
    fears_and_concerns TEXT NOT NULL DEFAULT '',
    things_that_matter_most TEXT NOT NULL DEFAULT '',
    preferred_place_of_care TEXT NOT NULL DEFAULT '',
    preferred_place_of_death TEXT NOT NULL DEFAULT '',
    daily_routine_preferences TEXT NOT NULL DEFAULT '',
    personal_care_preferences TEXT NOT NULL DEFAULT '',
    food_and_drink_preferences TEXT NOT NULL DEFAULT '',
    sleep_preferences TEXT NOT NULL DEFAULT '',
    clothing_preferences TEXT NOT NULL DEFAULT '',
    environment_preferences TEXT NOT NULL DEFAULT '',
    pet_care_wishes TEXT NOT NULL DEFAULT '',
    pain_management_preferences TEXT NOT NULL DEFAULT '',
    attitude_to_hospital_admission TEXT NOT NULL DEFAULT '',
    attitude_to_intensive_care TEXT NOT NULL DEFAULT '',
    attitude_to_artificial_nutrition TEXT NOT NULL DEFAULT '',
    attitude_to_artificial_hydration TEXT NOT NULL DEFAULT '',
    medication_preferences TEXT NOT NULL DEFAULT '',
    complementary_therapy_preferences TEXT NOT NULL DEFAULT '',
    other_treatment_wishes TEXT NOT NULL DEFAULT '',
    preferred_language VARCHAR(100) NOT NULL DEFAULT '',
    communication_aids TEXT NOT NULL DEFAULT '',
    how_to_share_information TEXT NOT NULL DEFAULT '',
    who_to_involve_in_decisions TEXT NOT NULL DEFAULT '',
    information_sharing_restrictions TEXT NOT NULL DEFAULT '',
    preferred_communication_style TEXT NOT NULL DEFAULT '',
    primary_contact_name VARCHAR(255) NOT NULL DEFAULT '',
    primary_contact_relationship VARCHAR(100) NOT NULL DEFAULT '',
    primary_contact_phone VARCHAR(30) NOT NULL DEFAULT '',
    primary_contact_email VARCHAR(255) NOT NULL DEFAULT '',
    secondary_contact_name VARCHAR(255) NOT NULL DEFAULT '',
    secondary_contact_relationship VARCHAR(100) NOT NULL DEFAULT '',
    secondary_contact_phone VARCHAR(30) NOT NULL DEFAULT '',
    people_who_should_visit TEXT NOT NULL DEFAULT '',
    people_who_should_not_visit TEXT NOT NULL DEFAULT '',
    support_network_details TEXT NOT NULL DEFAULT '',
    financial_arrangements TEXT NOT NULL DEFAULT '',
    property_arrangements TEXT NOT NULL DEFAULT '',
    insurance_details TEXT NOT NULL DEFAULT '',
    will_location TEXT NOT NULL DEFAULT '',
    has_lasting_power_of_attorney VARCHAR(5) NOT NULL DEFAULT '' CHECK (has_lasting_power_of_attorney IN ('yes', 'no', '')),
    lpa_details TEXT NOT NULL DEFAULT '',
    funeral_wishes TEXT NOT NULL DEFAULT '',
    burial_or_cremation VARCHAR(20) NOT NULL DEFAULT '' CHECK (burial_or_cremation IN ('burial', 'cremation', 'other', '')),
    other_practical_matters TEXT NOT NULL DEFAULT '',
    maker_signature_obtained VARCHAR(5) NOT NULL DEFAULT '' CHECK (maker_signature_obtained IN ('yes', 'no', '')),
    maker_signature_date DATE,
    witness_name VARCHAR(255) NOT NULL DEFAULT '',
    witness_address TEXT NOT NULL DEFAULT '',
    witness_signature_obtained VARCHAR(5) NOT NULL DEFAULT '' CHECK (witness_signature_obtained IN ('yes', 'no', '')),
    witness_signature_date DATE,
    review_date DATE,
    review_notes TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_assessment_updated_at
    BEFORE UPDATE ON assessment
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE assessment IS
    'Flat assessment table: parent assessment merged with every assessment_<section> child. Generated by bin/generate-sql-flat.py.';

COMMENT ON COLUMN assessment.patient_id IS
    'Foreign key to the patient table.';
COMMENT ON COLUMN assessment.status IS
    'Lifecycle status of this row.';
COMMENT ON COLUMN assessment.full_name IS
    'Full name.';
COMMENT ON COLUMN assessment.address IS
    'Address.';
COMMENT ON COLUMN assessment.postcode IS
    'Postcode.';
COMMENT ON COLUMN assessment.date_of_birth IS
    'Date of birth.';
COMMENT ON COLUMN assessment.nhs_number IS
    'NHS number.';
COMMENT ON COLUMN assessment.phone IS
    'Phone.';
COMMENT ON COLUMN assessment.email IS
    'Email.';
COMMENT ON COLUMN assessment.gp_name IS
    'GP name.';
COMMENT ON COLUMN assessment.gp_practice IS
    'GP practice.';
COMMENT ON COLUMN assessment.reason_for_statement IS
    'Reason for statement.';
COMMENT ON COLUMN assessment.current_health_status IS
    'Current health status.';
COMMENT ON COLUMN assessment.current_diagnoses IS
    'Current diagnoses.';
COMMENT ON COLUMN assessment.has_discussed_with_family IS
    'Has discussed with family. One of: yes, no.';
COMMENT ON COLUMN assessment.has_discussed_with_clinician IS
    'Has discussed with clinician. One of: yes, no.';
COMMENT ON COLUMN assessment.discussion_details IS
    'Discussion details.';
COMMENT ON COLUMN assessment.personal_values IS
    'Personal values.';
COMMENT ON COLUMN assessment.quality_of_life_priorities IS
    'Quality of life priorities.';
COMMENT ON COLUMN assessment.religious_beliefs IS
    'Religious beliefs.';
COMMENT ON COLUMN assessment.spiritual_needs IS
    'Spiritual needs.';
COMMENT ON COLUMN assessment.cultural_considerations IS
    'Cultural considerations.';
COMMENT ON COLUMN assessment.fears_and_concerns IS
    'Fears and concerns.';
COMMENT ON COLUMN assessment.things_that_matter_most IS
    'Things that matter most.';
COMMENT ON COLUMN assessment.preferred_place_of_care IS
    'Preferred place of care.';
COMMENT ON COLUMN assessment.preferred_place_of_death IS
    'Preferred place of death.';
COMMENT ON COLUMN assessment.daily_routine_preferences IS
    'Daily routine preferences.';
COMMENT ON COLUMN assessment.personal_care_preferences IS
    'Personal care preferences.';
COMMENT ON COLUMN assessment.food_and_drink_preferences IS
    'Food and drink preferences.';
COMMENT ON COLUMN assessment.sleep_preferences IS
    'Sleep preferences.';
COMMENT ON COLUMN assessment.clothing_preferences IS
    'Clothing preferences.';
COMMENT ON COLUMN assessment.environment_preferences IS
    'Environment preferences.';
COMMENT ON COLUMN assessment.pet_care_wishes IS
    'Pet care wishes.';
COMMENT ON COLUMN assessment.pain_management_preferences IS
    'Pain management preferences.';
COMMENT ON COLUMN assessment.attitude_to_hospital_admission IS
    'Attitude to hospital admission.';
COMMENT ON COLUMN assessment.attitude_to_intensive_care IS
    'Attitude to intensive care.';
COMMENT ON COLUMN assessment.attitude_to_artificial_nutrition IS
    'Attitude to artificial nutrition.';
COMMENT ON COLUMN assessment.attitude_to_artificial_hydration IS
    'Attitude to artificial hydration.';
COMMENT ON COLUMN assessment.medication_preferences IS
    'Medication preferences.';
COMMENT ON COLUMN assessment.complementary_therapy_preferences IS
    'Complementary therapy preferences.';
COMMENT ON COLUMN assessment.other_treatment_wishes IS
    'Other treatment wishes.';
COMMENT ON COLUMN assessment.preferred_language IS
    'Preferred language.';
COMMENT ON COLUMN assessment.communication_aids IS
    'Communication aids.';
COMMENT ON COLUMN assessment.how_to_share_information IS
    'How to share information.';
COMMENT ON COLUMN assessment.who_to_involve_in_decisions IS
    'WHO to involve in decisions.';
COMMENT ON COLUMN assessment.information_sharing_restrictions IS
    'Information sharing restrictions.';
COMMENT ON COLUMN assessment.preferred_communication_style IS
    'Preferred communication style.';
COMMENT ON COLUMN assessment.primary_contact_name IS
    'Primary contact name.';
COMMENT ON COLUMN assessment.primary_contact_relationship IS
    'Primary contact relationship.';
COMMENT ON COLUMN assessment.primary_contact_phone IS
    'Primary contact phone.';
COMMENT ON COLUMN assessment.primary_contact_email IS
    'Primary contact email.';
COMMENT ON COLUMN assessment.secondary_contact_name IS
    'Secondary contact name.';
COMMENT ON COLUMN assessment.secondary_contact_relationship IS
    'Secondary contact relationship.';
COMMENT ON COLUMN assessment.secondary_contact_phone IS
    'Secondary contact phone.';
COMMENT ON COLUMN assessment.people_who_should_visit IS
    'People WHO should visit.';
COMMENT ON COLUMN assessment.people_who_should_not_visit IS
    'People WHO should not visit.';
COMMENT ON COLUMN assessment.support_network_details IS
    'Support network details.';
COMMENT ON COLUMN assessment.financial_arrangements IS
    'Financial arrangements.';
COMMENT ON COLUMN assessment.property_arrangements IS
    'Property arrangements.';
COMMENT ON COLUMN assessment.insurance_details IS
    'Insurance details.';
COMMENT ON COLUMN assessment.will_location IS
    'Will location.';
COMMENT ON COLUMN assessment.has_lasting_power_of_attorney IS
    'Has lasting power of attorney. One of: yes, no.';
COMMENT ON COLUMN assessment.lpa_details IS
    'Lpa details.';
COMMENT ON COLUMN assessment.funeral_wishes IS
    'Funeral wishes.';
COMMENT ON COLUMN assessment.burial_or_cremation IS
    'Burial or cremation. One of: burial, cremation, other.';
COMMENT ON COLUMN assessment.other_practical_matters IS
    'Other practical matters.';
COMMENT ON COLUMN assessment.maker_signature_obtained IS
    'Maker signature obtained. One of: yes, no.';
COMMENT ON COLUMN assessment.maker_signature_date IS
    'Maker signature date.';
COMMENT ON COLUMN assessment.witness_name IS
    'Witness name.';
COMMENT ON COLUMN assessment.witness_address IS
    'Witness address.';
COMMENT ON COLUMN assessment.witness_signature_obtained IS
    'Witness signature obtained. One of: yes, no.';
COMMENT ON COLUMN assessment.witness_signature_date IS
    'Witness signature date.';
COMMENT ON COLUMN assessment.review_date IS
    'Review date.';
COMMENT ON COLUMN assessment.review_notes IS
    'Review notes.';
COMMENT ON COLUMN assessment.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN assessment.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN assessment.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN assessment.deleted_at IS
    'Timestamp when this row was deleted.';
