//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "qrisk3_cardiovascular_disease_risk_scores")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub clinician_name: String,
    pub clinician_role: String,
    pub assessed_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    pub patient_identifier: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub age: Option<f64>,
    pub sex: String,
    pub ethnicity: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub townsend_score: Option<f64>,
    pub postcode: String,
    pub smoking_status: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub body_mass_index: Option<f64>,
    pub diabetes_status: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub cholesterol_hdl_ratio: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub systolic_blood_pressure: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub systolic_blood_pressure_sd: Option<f64>,
    pub on_blood_pressure_treatment: String,
    pub family_history_chd: String,
    pub atrial_fibrillation: String,
    pub chronic_kidney_disease_stage: String,
    pub migraine: String,
    pub rheumatoid_arthritis: String,
    pub systemic_lupus_erythematosus: String,
    pub severe_mental_illness: String,
    pub erectile_dysfunction: String,
    pub on_atypical_antipsychotics: String,
    pub on_corticosteroids: String,
    pub has_established_cvd: String,
    pub has_familial_hypercholesterolaemia: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_note: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::qrisk3_cardiovascular_disease_risk_score_grades::Entity")]
    Qrisk3CardiovascularDiseaseRiskScoreGrades,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::qrisk3_cardiovascular_disease_risk_score_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Qrisk3CardiovascularDiseaseRiskScoreGrades.def()
    }
}
