//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "qrisk3_cardiovascular_disease_risk_score_grade_rules")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub rule_id: String,
    pub component: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub contribution: Option<f64>,
    pub category: String,
    pub description: String,
    pub qrisk3_cardiovascular_disease_risk_score_grade_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::qrisk3_cardiovascular_disease_risk_score_grades::Entity",
        from = "Column::Qrisk3CardiovascularDiseaseRiskScoreGradeId",
        to = "super::qrisk3_cardiovascular_disease_risk_score_grades::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Qrisk3CardiovascularDiseaseRiskScoreGrades,
}

impl Related<super::qrisk3_cardiovascular_disease_risk_score_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Qrisk3CardiovascularDiseaseRiskScoreGrades.def()
    }
}
