#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding rheumatology-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    ethnicity:string! \
    occupation:string! \
    referring_physician:string! \
    referral_date:date \
    smoking_status:string! \
    alcohol_use:string! \
    --htmx

cargo loco generate scaffold assessment_chief_complaint \
    assessment:references \
    primary_complaint:text! \
    symptom_onset_date:date \
    symptom_duration_weeks:int \
    symptom_pattern:string! \
    morning_stiffness_duration_minutes:int \
    pain_severity:int \
    fatigue_severity:int \
    patient_global_assessment:int \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_joint_assessment \
    assessment:references \
    tender_joint_count_28:int \
    swollen_joint_count_28:int \
    shoulders_involved:string! \
    elbows_involved:string! \
    wrists_involved:string! \
    mcp_joints_involved:string! \
    pip_joints_involved:string! \
    knees_involved:string! \
    joint_deformity_present:string! \
    joint_deformity_details:text! \
    joint_pattern:string! \
    --htmx

cargo loco generate scaffold assessment_disease_history \
    assessment:references \
    diagnosis:string! \
    diagnosis_other:text! \
    diagnosis_date:date \
    disease_duration_years:int \
    rheumatoid_factor_positive:string! \
    anti_ccp_positive:string! \
    previous_dmard_use:string! \
    previous_dmard_details:text! \
    previous_biologic_use:string! \
    previous_biologic_details:text! \
    joint_surgery_history:string! \
    joint_surgery_details:text! \
    flare_frequency:string! \
    --htmx

cargo loco generate scaffold assessment_extra_articular_features \
    assessment:references \
    rheumatoid_nodules:string! \
    rheumatoid_nodules_location:text! \
    dry_eyes_or_mouth:string! \
    skin_rash:string! \
    skin_rash_details:text! \
    raynauds_phenomenon:string! \
    interstitial_lung_disease:string! \
    vasculitis:string! \
    scleritis_episcleritis:string! \
    peripheral_neuropathy:string! \
    pleuritis_pericarditis:string! \
    constitutional_symptoms:text! \
    --htmx

cargo loco generate scaffold assessment_laboratory_results \
    assessment:references \
    esr_mm_hr:double \
    crp_mg_l:double \
    rheumatoid_factor_iu_ml:double \
    anti_ccp_u_ml:double \
    ana_positive:string! \
    ana_titre:string! \
    haemoglobin_g_dl:double \
    white_cell_count:double \
    platelet_count:int \
    creatinine_umol_l:double \
    alt_u_l:double \
    lab_date:date \
    additional_results:text! \
    --htmx

cargo loco generate scaffold assessment_current_medications \
    assessment:references \
    currently_on_dmard:string! \
    dmard_names:text! \
    currently_on_biologic:string! \
    biologic_name:text! \
    currently_on_corticosteroid:string! \
    corticosteroid_dose_mg:double \
    nsaid_use:string! \
    nsaid_name:text! \
    analgesic_use:string! \
    analgesic_details:text! \
    folic_acid_supplementation:string! \
    other_medications:text! \
    medication_adherence:string! \
    --htmx

cargo loco generate scaffold assessment_allergies \
    assessment:references \
    has_drug_allergies:string! \
    drug_allergy_details:text! \
    methotrexate_intolerance:string! \
    sulfa_allergy:string! \
    nsaid_allergy:string! \
    biologic_reaction_history:string! \
    biologic_reaction_details:text! \
    latex_allergy:string! \
    other_allergies:text! \
    --htmx

cargo loco generate scaffold assessment_functional_assessment \
    assessment:references \
    haq_dressing_grooming:int \
    haq_arising:int \
    haq_eating:int \
    haq_walking:int \
    haq_hygiene:int \
    haq_reach:int \
    haq_grip:int \
    haq_activities:int \
    work_impact:string! \
    mobility_aid_use:string! \
    mobility_aid_details:text! \
    physiotherapy_current:string! \
    occupational_therapy_current:string! \
    --htmx

cargo loco generate scaffold assessment_comorbidities_social \
    assessment:references \
    cardiovascular_disease:string! \
    cardiovascular_details:text! \
    diabetes:string! \
    diabetes_type:string! \
    hypertension:string! \
    chronic_kidney_disease:string! \
    hepatitis_b_or_c:string! \
    tuberculosis_history:string! \
    osteoporosis:string! \
    depression_anxiety:string! \
    malignancy_history:string! \
    malignancy_details:text! \
    lives_alone:string! \
    carer_support:string! \
    exercise_frequency:string! \
    vaccination_status_up_to_date:string! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    das28_score:double \
    das28_method:string! \
    disease_activity_level:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
