import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		validityStatus: 'Valid',
		lifeSustainingRefusal: true,
		witnessed: true,
		reviewDate: '2026-01-15',
		lpaStatus: 'None',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		validityStatus: 'Complete',
		lifeSustainingRefusal: false,
		witnessed: false,
		reviewDate: '2025-11-20',
		lpaStatus: 'None',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		validityStatus: 'Invalid',
		lifeSustainingRefusal: true,
		witnessed: false,
		reviewDate: '2026-03-01',
		lpaStatus: 'Health & Welfare',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		validityStatus: 'Draft',
		lifeSustainingRefusal: false,
		witnessed: false,
		reviewDate: '',
		lpaStatus: 'None',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		validityStatus: 'Valid',
		lifeSustainingRefusal: true,
		witnessed: true,
		reviewDate: '2026-02-28',
		lpaStatus: 'None',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		validityStatus: 'Valid',
		lifeSustainingRefusal: false,
		witnessed: false,
		reviewDate: '2025-12-10',
		lpaStatus: 'None',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		validityStatus: 'Invalid',
		lifeSustainingRefusal: true,
		witnessed: true,
		reviewDate: '2026-01-05',
		lpaStatus: 'Property & Financial',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		validityStatus: 'Complete',
		lifeSustainingRefusal: true,
		witnessed: true,
		reviewDate: '2026-03-07',
		lpaStatus: 'None',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		validityStatus: 'Valid',
		lifeSustainingRefusal: true,
		witnessed: true,
		reviewDate: '2025-10-15',
		lpaStatus: 'Health & Welfare',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		validityStatus: 'Draft',
		lifeSustainingRefusal: false,
		witnessed: false,
		reviewDate: '',
		lpaStatus: 'None',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		validityStatus: 'Valid',
		lifeSustainingRefusal: false,
		witnessed: false,
		reviewDate: '2026-02-14',
		lpaStatus: 'None',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		validityStatus: 'Invalid',
		lifeSustainingRefusal: true,
		witnessed: false,
		reviewDate: '2025-09-30',
		lpaStatus: 'Health & Welfare',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		validityStatus: 'Complete',
		lifeSustainingRefusal: false,
		witnessed: false,
		reviewDate: '2026-01-22',
		lpaStatus: 'None',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		validityStatus: 'Valid',
		lifeSustainingRefusal: true,
		witnessed: true,
		reviewDate: '2026-03-05',
		lpaStatus: 'None',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		validityStatus: 'Draft',
		lifeSustainingRefusal: false,
		witnessed: false,
		reviewDate: '',
		lpaStatus: 'Property & Financial',
	},
];
