//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "parkland_formula_for_burns_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Double", nullable)]
    pub total_24h_volume_ml: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub first_8h_volume_ml: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub next_16h_volume_ml: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub hours_since_injury: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub remaining_first_8h_hours: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub first_8h_rate_ml_h: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub next_16h_rate_ml_h: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub urine_output_target_min_ml_h: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub urine_output_target_max_ml_h: Option<f64>,
    pub graded_at: DateTimeWithTimeZone,
    pub parkland_formula_for_burns_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::parkland_formula_for_burns::Entity",
        from = "Column::ParklandFormulaForBurnsId",
        to = "super::parkland_formula_for_burns::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ParklandFormulaForBurns,
    #[sea_orm(has_many = "super::parkland_formula_for_burns_grade_flags::Entity")]
    ParklandFormulaForBurnsGradeFlags,
    #[sea_orm(has_many = "super::parkland_formula_for_burns_grade_rules::Entity")]
    ParklandFormulaForBurnsGradeRules,
}

impl Related<super::parkland_formula_for_burns::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ParklandFormulaForBurns.def()
    }
}

impl Related<super::parkland_formula_for_burns_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ParklandFormulaForBurnsGradeFlags.def()
    }
}

impl Related<super::parkland_formula_for_burns_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ParklandFormulaForBurnsGradeRules.def()
    }
}
