//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "parkland_formula_for_burns")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub clinician_name: String,
    pub clinician_role: String,
    pub care_setting: String,
    pub assessed_at: Option<DateTimeWithTimeZone>,
    pub patient_identifier: String,
    pub age_band: String,
    pub sex: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight_kg: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tbsa_percent: Option<f64>,
    pub tbsa_method: String,
    pub injury_at: Option<DateTimeWithTimeZone>,
    pub injury_time_known: String,
    pub inhalation_suspected: String,
    pub circumferential_or_deep: String,
    pub mechanism: String,
    pub patient_id: i64,
    pub clinician_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::parkland_formula_for_burns_grades::Entity")]
    ParklandFormulaForBurnsGrades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::parkland_formula_for_burns_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ParklandFormulaForBurnsGrades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
