-- ============================================================
-- 02_assessment.sql
-- A single diabetes assessment visit.
-- ============================================================
-- Each assessment belongs to one patient and captures the
-- clinical snapshot at the time of the diabetes review.
-- Section details are stored in 1:1 child tables (03-11).
-- ============================================================

CREATE TABLE assessment (
    -- Primary key: UUIDv4 generated by the database
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key to the patient this assessment belongs to
    patient_id          UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,

    -- Assessment status tracking
    status              TEXT NOT NULL DEFAULT 'in_progress'
                        CHECK (status IN ('in_progress', 'completed', 'reviewed')),

    -- Audit timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for the most common query: all assessments for a patient
CREATE INDEX idx_assessment_patient_id ON assessment(patient_id);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_assessment_updated_at
    BEFORE UPDATE ON assessment
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE assessment IS
    'A single diabetes assessment visit. Child tables hold section-specific clinical data.';
COMMENT ON COLUMN assessment.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN assessment.patient_id IS
    'FK to patient. One patient may have many assessments.';
COMMENT ON COLUMN assessment.status IS
    'Workflow status: in_progress (filling in), completed (submitted), reviewed (clinician signed off).';
COMMENT ON COLUMN assessment.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN assessment.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
