//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "agile_principles_assessments")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub is_anonymous: bool,
    pub assessment_date: Option<Date>,
    pub assessment_period: String,
    pub p01_customer_satisfaction: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p01_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p01_weight: f64,
    pub p02_welcome_change: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p02_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p02_weight: f64,
    pub p03_deliver_frequently: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p03_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p03_weight: f64,
    pub p04_collaboration: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p04_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p04_weight: f64,
    pub p05_motivated_individuals: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p05_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p05_weight: f64,
    pub p06_face_to_face: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p06_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p06_weight: f64,
    pub p07_working_software: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p07_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p07_weight: f64,
    pub p08_sustainable_development: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p08_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p08_weight: f64,
    pub p09_technical_excellence: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p09_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p09_weight: f64,
    pub p10_simplicity: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p10_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p10_weight: f64,
    pub p11_self_organising_teams: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p11_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p11_weight: f64,
    pub p12_regular_reflection: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub p12_comment: String,
    #[sea_orm(column_type = "Double")]
    pub p12_weight: f64,
    #[sea_orm(column_type = "Text")]
    pub overall_notes: String,
    pub respondent_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agile_principles_assessment_grades::Entity")]
    AgilePrinciplesAssessmentGrades,
    #[sea_orm(
        belongs_to = "super::respondents::Entity",
        from = "Column::RespondentId",
        to = "super::respondents::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Respondents,
}

impl Related<super::agile_principles_assessment_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgilePrinciplesAssessmentGrades.def()
    }
}

impl Related<super::respondents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Respondents.def()
    }
}
