#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding patient-satisfaction-survey (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    preferred_name:string! \
    gender_identity:string! \
    age_range:string! \
    ethnicity:string! \
    preferred_language:string! \
    interpreter_required:string! \
    postcode_area:string! \
    --htmx

cargo loco generate scaffold assessment_visit_details \
    assessment:references \
    visit_date:date \
    visit_type:string! \
    department:string! \
    hospital_site:string! \
    length_of_stay_days:int \
    referral_source:string! \
    is_first_visit:string! \
    visit_details_notes:text! \
    --htmx

cargo loco generate scaffold assessment_access_waiting_times \
    assessment:references \
    ease_of_booking:int \
    waiting_time_for_appointment:int \
    waiting_time_on_day:int \
    reception_service:int \
    signage_wayfinding:int \
    parking_transport:int \
    actual_wait_minutes:int \
    access_notes:text! \
    --htmx

cargo loco generate scaffold assessment_communication_information \
    assessment:references \
    explanation_of_condition:int \
    explanation_of_treatment:int \
    opportunity_to_ask_questions:int \
    listened_to:int \
    informed_about_medication:int \
    written_information_quality:int \
    communication_notes:text! \
    --htmx

cargo loco generate scaffold assessment_clinical_care_quality \
    assessment:references \
    confidence_in_clinician:int \
    thoroughness_of_examination:int \
    pain_management:int \
    involvement_in_decisions:int \
    privacy_during_examination:int \
    coordination_of_care:int \
    clinical_care_notes:text! \
    --htmx

cargo loco generate scaffold assessment_staff_attitude \
    assessment:references \
    doctor_courtesy:int \
    nurse_courtesy:int \
    reception_courtesy:int \
    respect_for_dignity:int \
    cultural_sensitivity:int \
    emotional_support:int \
    staff_attitude_notes:text! \
    --htmx

cargo loco generate scaffold assessment_environment_facilities \
    assessment:references \
    cleanliness:int \
    comfort:int \
    noise_levels:int \
    food_quality:int \
    toilet_facilities:int \
    temperature_comfort:int \
    environment_notes:text! \
    --htmx

cargo loco generate scaffold assessment_discharge_follow_up \
    assessment:references \
    discharge_information:int \
    medication_explanation:int \
    follow_up_arrangements:int \
    knew_who_to_contact:int \
    recovery_information:int \
    care_plan_clarity:int \
    discharge_notes:text! \
    --htmx

cargo loco generate scaffold assessment_overall_experience \
    assessment:references \
    overall_satisfaction:int \
    would_recommend:int \
    met_expectations:int \
    felt_safe:int \
    would_return:int \
    nhs_rating:int \
    overall_experience_notes:text! \
    --htmx

cargo loco generate scaffold assessment_comments_suggestions \
    assessment:references \
    what_went_well:text! \
    what_could_improve:text! \
    specific_staff_praise:text! \
    complaint_raised:string! \
    complaint_details:text! \
    additional_comments:text! \
    consent_to_contact:string! \
    contact_email:string! \
    contact_phone:string! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    normalized_score:double! \
    satisfaction_category:string! \
    domain_access_score:double \
    domain_communication_score:double \
    domain_clinical_care_score:double \
    domain_staff_score:double \
    domain_environment_score:double \
    domain_discharge_score:double \
    domain_overall_score:double \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
