import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		hearingGrade: 'normal',
		affectedEar: 'N/A',
		hearingLossType: 'N/A',
		tinnitus: false,
		hearingAidStatus: 'None',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		hearingGrade: 'mild',
		affectedEar: 'Both',
		hearingLossType: 'Sensorineural',
		tinnitus: true,
		hearingAidStatus: 'Candidate',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		hearingGrade: 'moderate',
		affectedEar: 'Right',
		hearingLossType: 'Conductive',
		tinnitus: false,
		hearingAidStatus: 'Fitted',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		hearingGrade: 'severe',
		affectedEar: 'Both',
		hearingLossType: 'Mixed',
		tinnitus: true,
		hearingAidStatus: 'Fitted',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		hearingGrade: 'profound',
		affectedEar: 'Left',
		hearingLossType: 'Sensorineural',
		tinnitus: true,
		hearingAidStatus: 'Cochlear implant candidate',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		hearingGrade: 'mild',
		affectedEar: 'Right',
		hearingLossType: 'Conductive',
		tinnitus: false,
		hearingAidStatus: 'None',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		hearingGrade: 'moderate',
		affectedEar: 'Both',
		hearingLossType: 'Sensorineural',
		tinnitus: true,
		hearingAidStatus: 'Fitted',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		hearingGrade: 'normal',
		affectedEar: 'N/A',
		hearingLossType: 'N/A',
		tinnitus: true,
		hearingAidStatus: 'None',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		hearingGrade: 'severe',
		affectedEar: 'Both',
		hearingLossType: 'Sensorineural',
		tinnitus: false,
		hearingAidStatus: 'Fitted',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		hearingGrade: 'mild',
		affectedEar: 'Left',
		hearingLossType: 'Conductive',
		tinnitus: false,
		hearingAidStatus: 'Candidate',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		hearingGrade: 'moderate',
		affectedEar: 'Both',
		hearingLossType: 'Mixed',
		tinnitus: true,
		hearingAidStatus: 'Fitted',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		hearingGrade: 'profound',
		affectedEar: 'Both',
		hearingLossType: 'Sensorineural',
		tinnitus: false,
		hearingAidStatus: 'Cochlear implant candidate',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		hearingGrade: 'mild',
		affectedEar: 'Right',
		hearingLossType: 'Sensorineural',
		tinnitus: false,
		hearingAidStatus: 'None',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		hearingGrade: 'moderate',
		affectedEar: 'Both',
		hearingLossType: 'Mixed',
		tinnitus: true,
		hearingAidStatus: 'Candidate',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		hearingGrade: 'normal',
		affectedEar: 'N/A',
		hearingLossType: 'N/A',
		tinnitus: false,
		hearingAidStatus: 'None',
	},
];
