//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "post_anaesthesia_care_unit_record_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub activity_score: Option<i32>,
    pub respiration_score: Option<i32>,
    pub circulation_score: Option<i32>,
    pub consciousness_score: Option<i32>,
    pub oxygen_saturation_score: Option<i32>,
    pub aldrete_total: Option<i32>,
    pub discharge_ready: String,
    pub padss_total: Option<i32>,
    pub padss_street_fit: String,
    pub graded_at: DateTimeWithTimeZone,
    pub post_anaesthesia_care_unit_record_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post_anaesthesia_care_unit_record_grade_flags::Entity")]
    PostAnaesthesiaCareUnitRecordGradeFlags,
    #[sea_orm(has_many = "super::post_anaesthesia_care_unit_record_grade_rules::Entity")]
    PostAnaesthesiaCareUnitRecordGradeRules,
    #[sea_orm(
        belongs_to = "super::post_anaesthesia_care_unit_records::Entity",
        from = "Column::PostAnaesthesiaCareUnitRecordId",
        to = "super::post_anaesthesia_care_unit_records::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PostAnaesthesiaCareUnitRecords,
}

impl Related<super::post_anaesthesia_care_unit_record_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostAnaesthesiaCareUnitRecordGradeFlags.def()
    }
}

impl Related<super::post_anaesthesia_care_unit_record_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostAnaesthesiaCareUnitRecordGradeRules.def()
    }
}

impl Related<super::post_anaesthesia_care_unit_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostAnaesthesiaCareUnitRecords.def()
    }
}
