//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "cytology_test_request_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub appropriateness_score: Option<i32>,
    pub appropriateness_band: String,
    pub preanalytical_band: String,
    pub completeness_percent: Option<i32>,
    pub triage_tier: String,
    pub target_timeframe: String,
    pub recommendation: String,
    #[sea_orm(column_type = "Text")]
    pub clinician_notes: String,
    pub signed_at: Option<DateTimeWithTimeZone>,
    pub graded_at: DateTimeWithTimeZone,
    pub cytology_test_request_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cytology_test_request_grade_flags::Entity")]
    CytologyTestRequestGradeFlags,
    #[sea_orm(has_many = "super::cytology_test_request_grade_rules::Entity")]
    CytologyTestRequestGradeRules,
    #[sea_orm(
        belongs_to = "super::cytology_test_requests::Entity",
        from = "Column::CytologyTestRequestId",
        to = "super::cytology_test_requests::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CytologyTestRequests,
}

impl Related<super::cytology_test_request_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CytologyTestRequestGradeFlags.def()
    }
}

impl Related<super::cytology_test_request_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CytologyTestRequestGradeRules.def()
    }
}

impl Related<super::cytology_test_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CytologyTestRequests.def()
    }
}
