//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "medications")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub international_nonproprietary_name: String,
    #[sea_orm(column_type = "Text")]
    pub brand_name: String,
    #[sea_orm(column_type = "Text")]
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub hold_class: String,
    pub hold_required: bool,
    pub default_hold_start_before_days: Option<i32>,
    pub default_restart_after_days: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub perioperative_hold_guidance: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::patient_medications::Entity")]
    PatientMedications,
}

impl Related<super::patient_medications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatientMedications.def()
    }
}
