//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "perioperative_optimization_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub weeks_to_surgery: Option<i32>,
    pub gating_applied: bool,
    pub must_score: Option<i32>,
    pub must_risk: String,
    pub audit_c_score: Option<i32>,
    pub stop_bang_score: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub duke_activity_status_index: Option<f64>,
    pub clinical_frailty_scale: Option<i32>,
    pub fried_phenotype_score: Option<i32>,
    pub fried_frailty_category: String,
    pub domains_optimized: Option<i32>,
    pub domains_in_progress: Option<i32>,
    pub domains_action_required: Option<i32>,
    pub domains_insufficient_time: Option<i32>,
    pub computed_readiness: String,
    pub final_readiness: String,
    pub override_reason: String,
    pub gate_decision: String,
    pub recommended_earliest_surgery_date: Option<Date>,
    #[sea_orm(column_type = "Text")]
    pub clinician_notes: String,
    pub signed_by_name: String,
    pub signed_at: Option<DateTimeWithTimeZone>,
    pub graded_at: DateTimeWithTimeZone,
    pub perioperative_optimization_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::perioperative_optimization_grade_domains::Entity")]
    PerioperativeOptimizationGradeDomains,
    #[sea_orm(has_many = "super::perioperative_optimization_grade_flags::Entity")]
    PerioperativeOptimizationGradeFlags,
    #[sea_orm(
        belongs_to = "super::perioperative_optimizations::Entity",
        from = "Column::PerioperativeOptimizationId",
        to = "super::perioperative_optimizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PerioperativeOptimizations,
}

impl Related<super::perioperative_optimization_grade_domains::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerioperativeOptimizationGradeDomains.def()
    }
}

impl Related<super::perioperative_optimization_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerioperativeOptimizationGradeFlags.def()
    }
}

impl Related<super::perioperative_optimizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerioperativeOptimizations.def()
    }
}
