//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "perioperative_optimizations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub assessment_date: Option<Date>,
    pub assessment_time: Option<String>,
    pub site_name: String,
    pub service_name: String,
    pub pathway_stage: String,
    pub assessment_mode: String,
    pub referral_source: String,
    pub planned_procedure: String,
    pub surgical_specialty: String,
    pub consultant_surgeon: String,
    pub planned_surgery_date: Option<Date>,
    pub urgency: String,
    pub surgical_severity: String,
    pub laterality: String,
    pub anticipated_blood_loss_ml: Option<i32>,
    pub anticipated_length_of_stay_days: Option<i32>,
    pub interpreter_required: String,
    pub interpreter_language: String,
    pub condition_cardiac: String,
    pub condition_respiratory: String,
    pub condition_renal: String,
    pub condition_hepatic: String,
    pub condition_stroke: String,
    pub condition_cancer: String,
    pub condition_rheumatological: String,
    pub condition_thyroid: String,
    pub condition_other: String,
    pub previous_surgery: String,
    pub previous_surgery_detail: String,
    pub previous_anaesthetic_complication: String,
    pub previous_anaesthetic_complication_detail: String,
    pub postoperative_nausea_history: String,
    pub difficult_airway_history: String,
    pub malignant_hyperthermia_history: String,
    pub venous_thromboembolism_history: String,
    #[sea_orm(column_type = "Text")]
    pub family_history: String,
    pub pregnancy_status: String,
    pub takes_prescription_medicines: String,
    pub takes_over_the_counter_medicines: String,
    pub takes_herbal_products: String,
    pub takes_anticoagulant: String,
    pub takes_antiplatelet: String,
    pub takes_ace_inhibitor_or_arb: String,
    pub takes_sglt2_inhibitor: String,
    pub takes_glp1_agonist: String,
    pub glp1_formulation: String,
    pub glp1_held_per_guideline: String,
    pub glp1_extended_clear_fluids_confirmed: String,
    pub glp1_gi_symptoms: String,
    pub glp1_gi_symptoms_details: String,
    pub glp1_gastric_ultrasound_performed: String,
    pub glp1_gastric_ultrasound_findings: String,
    pub takes_corticosteroid: String,
    pub takes_immunosuppressant: String,
    pub takes_hormone_therapy: String,
    pub medication_hold_plan_agreed: String,
    pub medication_hold_plan_agreed_by: String,
    pub medication_adherence: String,
    #[sea_orm(column_type = "Text")]
    pub medication_notes: String,
    pub has_drug_allergy: String,
    pub drug_allergy_detail: String,
    pub has_food_allergy: String,
    pub food_allergy_detail: String,
    pub has_latex_allergy: String,
    pub has_adhesive_allergy: String,
    pub has_contrast_allergy: String,
    pub allergy_severity: String,
    pub adrenaline_auto_injector: String,
    #[sea_orm(column_type = "Text")]
    pub allergy_notes: String,
    pub bloods_sample_date: Option<Date>,
    #[sea_orm(column_type = "Double", nullable)]
    pub haemoglobin_g_per_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub mean_cell_volume_fl: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub ferritin_ug_per_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub transferrin_saturation_percent: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub vitamin_b12_ng_per_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub folate_ug_per_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub c_reactive_protein_mg_per_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub creatinine_umol_per_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub egfr_ml_per_min: Option<f64>,
    pub anaemia_known_cause: String,
    pub anaemia_treatment_started: String,
    pub anaemia_treatment_route: String,
    pub anaemia_treatment_start_date: Option<Date>,
    pub previous_transfusion: String,
    pub group_and_save_done: String,
    #[sea_orm(column_type = "Text")]
    pub anaemia_notes: String,
    pub diabetes_type: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub diabetes_duration_years: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub hba1c_mmol_per_mol: Option<f64>,
    pub hba1c_sample_date: Option<Date>,
    #[sea_orm(column_type = "Double", nullable)]
    pub capillary_glucose_mmol_per_l: Option<f64>,
    pub diabetes_treatment: String,
    pub insulin_regimen: String,
    pub hypoglycaemia_awareness: String,
    pub diabetes_team_review: String,
    pub diabetes_team_review_date: Option<Date>,
    pub foot_check_done: String,
    #[sea_orm(column_type = "Text")]
    pub glycaemic_notes: String,
    pub smoking_status: String,
    pub cigarettes_per_day: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pack_years: Option<f64>,
    pub quit_date: Option<Date>,
    pub smoking_cessation_offered: String,
    pub smoking_cessation_accepted: String,
    pub nicotine_replacement: String,
    pub vaping: String,
    #[sea_orm(column_type = "Text")]
    pub smoking_notes: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub alcohol_units_per_week: Option<f64>,
    pub audit_c_frequency: Option<i32>,
    pub audit_c_typical_quantity: Option<i32>,
    pub audit_c_binge_frequency: Option<i32>,
    pub alcohol_dependence_features: String,
    pub alcohol_reduction_plan_agreed: String,
    pub alcohol_services_referral: String,
    pub recreational_drug_use: String,
    pub recreational_drug_detail: String,
    #[sea_orm(column_type = "Text")]
    pub alcohol_notes: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub height_as_cm: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight_as_kg: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub body_mass_index: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub usual_weight_as_kg: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight_loss_percent: Option<f64>,
    pub weight_loss_is_intentional: String,
    pub acutely_ill: String,
    pub no_nutritional_intake_over_5_days: String,
    pub appetite: String,
    pub oral_nutritional_supplements: String,
    pub immunonutrition: String,
    pub dietitian_referral: String,
    #[sea_orm(column_type = "Text")]
    pub nutrition_notes: String,
    pub usual_activity_level: String,
    pub climbs_flight_of_stairs: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub metabolic_equivalents: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub duke_activity_status_index: Option<f64>,
    pub six_minute_walk_metres: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cpet_anaerobic_threshold: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cpet_peak_vo2: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub grip_strength_kg: Option<f64>,
    pub prehabilitation_offered: String,
    pub prehabilitation_enrolled: String,
    pub prehabilitation_sessions_per_week: Option<i32>,
    pub prehabilitation_start_date: Option<Date>,
    pub protein_supplementation_recommended: String,
    #[sea_orm(column_type = "Text")]
    pub fitness_notes: String,
    pub clinical_frailty_scale: Option<i32>,
    pub fried_weakness: String,
    pub fried_slowness: String,
    pub fried_low_physical_activity: String,
    pub fried_exhaustion: String,
    pub fried_unintentional_weight_loss: String,
    pub risk_analysis_index_score: Option<i32>,
    pub mini_cog_performed: String,
    pub mini_cog_score: Option<i32>,
    pub cognitive_screen_tool: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub cognitive_screen_score: Option<f64>,
    pub cognitive_impairment: String,
    pub capacity_concern: String,
    pub falls_in_last_12_months: Option<i32>,
    pub mobility_aid: String,
    pub living_situation: String,
    pub care_package: String,
    #[sea_orm(column_type = "Text")]
    pub frailty_notes: String,
    pub systolic_bp: Option<i32>,
    pub diastolic_bp: Option<i32>,
    pub heart_rate: Option<i32>,
    pub heart_rhythm: String,
    pub murmur_present: String,
    pub exercise_tolerance: String,
    pub ejection_fraction_percent: Option<i32>,
    pub echo_date: Option<Date>,
    pub asthma_control: String,
    pub copd_control: String,
    pub inhaler_technique_checked: String,
    pub rescue_steroids: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub spirometry_fev1_percent: Option<f64>,
    pub stop_bang_score: Option<i32>,
    pub sleep_apnoea_diagnosis: String,
    pub cpap_use: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub oxygen_saturation_percent: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub cardiorespiratory_notes: String,
    pub anxiety_level: String,
    pub depression_screen: String,
    pub understands_procedure: String,
    pub expectations_realistic: String,
    pub shared_decision_making_discussed: String,
    pub has_carer: String,
    pub transport_home_arranged: String,
    pub support_after_discharge: String,
    pub health_literacy: String,
    pub psychological_support_offered: String,
    #[sea_orm(column_type = "Text")]
    pub social_notes: String,
    pub plan_anaemia: String,
    pub referral_anaemia: String,
    pub plan_glycaemic_control: String,
    pub referral_glycaemic_control: String,
    pub plan_smoking: String,
    pub referral_smoking: String,
    pub plan_alcohol: String,
    pub referral_alcohol: String,
    pub plan_nutrition: String,
    pub referral_nutrition: String,
    pub plan_physical_fitness: String,
    pub referral_physical_fitness: String,
    pub plan_medication: String,
    pub referral_medication: String,
    pub plan_cardiorespiratory: String,
    pub referral_cardiorespiratory: String,
    pub responsible_clinician: String,
    pub plan_agreed_with_patient: String,
    pub plan_shared_with_patient: String,
    pub next_review_date: Option<Date>,
    #[sea_orm(column_type = "Text")]
    pub plan_notes: String,
    pub gate_decision: String,
    #[sea_orm(column_type = "Text")]
    pub additional_notes: String,
    pub patient_id: i64,
    pub clinician_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::perioperative_optimization_grades::Entity")]
    PerioperativeOptimizationGrades,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::perioperative_optimization_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PerioperativeOptimizationGrades.def()
    }
}
