//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "casualty_card_clinical_examinations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub general_appearance: String,
    #[sea_orm(column_type = "Text")]
    pub head_and_face: String,
    #[sea_orm(column_type = "Text")]
    pub neck: String,
    #[sea_orm(column_type = "Text")]
    pub chest_cardiovascular: String,
    #[sea_orm(column_type = "Text")]
    pub chest_respiratory: String,
    #[sea_orm(column_type = "Text")]
    pub abdomen: String,
    #[sea_orm(column_type = "Text")]
    pub pelvis: String,
    #[sea_orm(column_type = "Text")]
    pub musculoskeletal_limbs: String,
    #[sea_orm(column_type = "Text")]
    pub neurological: String,
    #[sea_orm(column_type = "Text")]
    pub skin: String,
    #[sea_orm(column_type = "Text")]
    pub mental_state: String,
    #[sea_orm(column_type = "Text")]
    pub body_diagram_notes: String,
    pub casualty_card_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::casualty_cards::Entity",
        from = "Column::CasualtyCardId",
        to = "super::casualty_cards::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CasualtyCards,
}

impl Related<super::casualty_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CasualtyCards.def()
    }
}
