//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "zarit_burden_interview_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub total_score: Option<i32>,
    pub max_score: Option<i32>,
    pub burden_band: String,
    pub short_form_score: Option<i32>,
    pub graded_at: DateTimeWithTimeZone,
    pub zarit_burden_interview_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::zarit_burden_interview_grade_flags::Entity")]
    ZaritBurdenInterviewGradeFlags,
    #[sea_orm(has_many = "super::zarit_burden_interview_grade_rules::Entity")]
    ZaritBurdenInterviewGradeRules,
    #[sea_orm(
        belongs_to = "super::zarit_burden_interviews::Entity",
        from = "Column::ZaritBurdenInterviewId",
        to = "super::zarit_burden_interviews::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ZaritBurdenInterviews,
}

impl Related<super::zarit_burden_interview_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZaritBurdenInterviewGradeFlags.def()
    }
}

impl Related<super::zarit_burden_interview_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZaritBurdenInterviewGradeRules.def()
    }
}

impl Related<super::zarit_burden_interviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ZaritBurdenInterviews.def()
    }
}
