import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, Jane',
		phq9Score: 3,
		gad7Score: 2,
		riskLevel: 'low',
		allergyFlag: false,
		previousAdverseIncident: false,
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		phq9Score: 12,
		gad7Score: 14,
		riskLevel: 'medium',
		allergyFlag: true,
		previousAdverseIncident: false,
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		phq9Score: 22,
		gad7Score: 18,
		riskLevel: 'high',
		allergyFlag: false,
		previousAdverseIncident: true,
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		phq9Score: 7,
		gad7Score: 5,
		riskLevel: 'low',
		allergyFlag: false,
		previousAdverseIncident: false,
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		phq9Score: 25,
		gad7Score: 19,
		riskLevel: 'high',
		allergyFlag: true,
		previousAdverseIncident: true,
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		phq9Score: 1,
		gad7Score: 0,
		riskLevel: 'low',
		allergyFlag: false,
		previousAdverseIncident: false,
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		phq9Score: 16,
		gad7Score: 12,
		riskLevel: 'high',
		allergyFlag: true,
		previousAdverseIncident: false,
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		phq9Score: 8,
		gad7Score: 9,
		riskLevel: 'medium',
		allergyFlag: false,
		previousAdverseIncident: false,
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		phq9Score: 20,
		gad7Score: 16,
		riskLevel: 'high',
		allergyFlag: false,
		previousAdverseIncident: true,
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		phq9Score: 4,
		gad7Score: 3,
		riskLevel: 'low',
		allergyFlag: false,
		previousAdverseIncident: false,
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		phq9Score: 11,
		gad7Score: 10,
		riskLevel: 'medium',
		allergyFlag: true,
		previousAdverseIncident: false,
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		phq9Score: 24,
		gad7Score: 20,
		riskLevel: 'high',
		allergyFlag: false,
		previousAdverseIncident: true,
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		phq9Score: 6,
		gad7Score: 4,
		riskLevel: 'low',
		allergyFlag: false,
		previousAdverseIncident: false,
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		phq9Score: 15,
		gad7Score: 13,
		riskLevel: 'medium',
		allergyFlag: true,
		previousAdverseIncident: false,
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		phq9Score: 2,
		gad7Score: 1,
		riskLevel: 'low',
		allergyFlag: false,
		previousAdverseIncident: false,
	},
];
