//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "rockall_score_for_upper_gastrointestinal_bleeding_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub age_points: Option<i32>,
    pub shock_points: Option<i32>,
    pub comorbidity_points: Option<i32>,
    pub clinical_score: Option<i32>,
    pub diagnosis_points: Option<i32>,
    pub stigmata_points: Option<i32>,
    pub full_score: Option<i32>,
    pub risk_band: String,
    pub graded_at: DateTimeWithTimeZone,
    pub rockall_score_for_upper_gastrointestinal_bleeding_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        has_many = "super::rockall_score_for_upper_gastrointestinal_bleeding_grade_flags::Entity"
    )]
    RockallScoreForUpperGastrointestinalBleedingGradeFlags,
    #[sea_orm(
        has_many = "super::rockall_score_for_upper_gastrointestinal_bleeding_grade_rules::Entity"
    )]
    RockallScoreForUpperGastrointestinalBleedingGradeRules,
    #[sea_orm(
        belongs_to = "super::rockall_score_for_upper_gastrointestinal_bleedings::Entity",
        from = "Column::RockallScoreForUpperGastrointestinalBleedingId",
        to = "super::rockall_score_for_upper_gastrointestinal_bleedings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RockallScoreForUpperGastrointestinalBleedings,
}

impl Related<super::rockall_score_for_upper_gastrointestinal_bleeding_grade_flags::Entity>
    for Entity
{
    fn to() -> RelationDef {
        Relation::RockallScoreForUpperGastrointestinalBleedingGradeFlags.def()
    }
}

impl Related<super::rockall_score_for_upper_gastrointestinal_bleeding_grade_rules::Entity>
    for Entity
{
    fn to() -> RelationDef {
        Relation::RockallScoreForUpperGastrointestinalBleedingGradeRules.def()
    }
}

impl Related<super::rockall_score_for_upper_gastrointestinal_bleedings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RockallScoreForUpperGastrointestinalBleedings.def()
    }
}
