#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding sundowner-syndrome-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    preferred_name:string! \
    gender_identity:string! \
    ethnicity:string! \
    preferred_language:string! \
    interpreter_required:string! \
    living_situation:string! \
    primary_carer_name:string! \
    primary_carer_relationship:string! \
    gp_name:string! \
    gp_practice:string! \
    referrer_name:string! \
    referrer_role:string! \
    --htmx

cargo loco generate scaffold assessment_cognitive_status \
    assessment:references \
    dementia_diagnosis:string! \
    dementia_type:string! \
    dementia_stage:string! \
    mmse_score:int \
    moca_score:int \
    orientation_impaired:string! \
    short_term_memory_impaired:string! \
    long_term_memory_impaired:string! \
    communication_ability:string! \
    decision_making_capacity:string! \
    cognitive_status_notes:text! \
    --htmx

cargo loco generate scaffold assessment_behavioural_symptoms \
    assessment:references \
    agitation_level:string! \
    verbal_aggression:string! \
    physical_aggression:string! \
    wandering:string! \
    wandering_risk:string! \
    pacing:string! \
    repetitive_behaviours:string! \
    repetitive_behaviours_details:text! \
    hallucinations:string! \
    hallucination_type:string! \
    delusions:string! \
    anxiety:string! \
    depression:string! \
    cmai_score:int \
    npi_total_score:int \
    self_harm_risk:string! \
    harm_to_others_risk:string! \
    behavioural_notes:text! \
    --htmx

cargo loco generate scaffold assessment_temporal_pattern \
    assessment:references \
    onset_time:string! \
    typical_onset_hour:int \
    peak_severity_time:string! \
    typical_duration_hours:int \
    episode_frequency:string! \
    seasonal_pattern:string! \
    seasonal_pattern_details:text! \
    worse_with_daylight_changes:string! \
    symptoms_resolve_by_morning:string! \
    pattern_duration_months:int \
    pattern_worsening:string! \
    temporal_notes:text! \
    --htmx

cargo loco generate scaffold assessment_trigger_identification \
    assessment:references \
    pain_trigger:string! \
    pain_details:text! \
    hunger_thirst_trigger:string! \
    toileting_needs_trigger:string! \
    fatigue_trigger:string! \
    overstimulation_trigger:string! \
    understimulation_trigger:string! \
    unfamiliar_environment_trigger:string! \
    carer_change_trigger:string! \
    routine_disruption_trigger:string! \
    infection_trigger:string! \
    infection_details:text! \
    constipation_trigger:string! \
    dehydration_trigger:string! \
    medication_change_trigger:string! \
    other_triggers:text! \
    trigger_notes:text! \
    --htmx

cargo loco generate scaffold assessment_sleep_wake_cycle \
    assessment:references \
    sleep_quality:string! \
    typical_bedtime:string! \
    typical_wake_time:string! \
    sleep_duration_hours:double \
    night_waking_frequency:string! \
    daytime_napping:string! \
    nap_duration_hours:double \
    day_night_reversal:string! \
    circadian_rhythm_disruption:string! \
    sleep_apnoea:string! \
    restless_legs:string! \
    sleep_medication:string! \
    sleep_medication_details:text! \
    light_exposure_adequate:string! \
    sleep_notes:text! \
    --htmx

cargo loco generate scaffold assessment_medication_review \
    assessment:references \
    on_cholinesterase_inhibitor:string! \
    cholinesterase_inhibitor_details:text! \
    on_memantine:string! \
    on_antipsychotic:string! \
    antipsychotic_details:text! \
    on_benzodiazepine:string! \
    benzodiazepine_details:text! \
    on_antidepressant:string! \
    antidepressant_details:text! \
    on_melatonin:string! \
    melatonin_dose:text! \
    on_analgesic:string! \
    analgesic_details:text! \
    anticholinergic_burden:string! \
    polypharmacy:string! \
    total_medications:int \
    recent_medication_changes:string! \
    recent_medication_changes_details:text! \
    medication_adherence:string! \
    medication_notes:text! \
    --htmx

cargo loco generate scaffold assessment_environmental \
    assessment:references \
    lighting_adequate:string! \
    lighting_notes:text! \
    noise_level:string! \
    temperature_comfortable:string! \
    familiar_objects_present:string! \
    orientation_cues_present:string! \
    orientation_cues_details:text! \
    safe_wandering_space:string! \
    exit_security:string! \
    fall_hazards_addressed:string! \
    structured_routine:string! \
    evening_routine_established:string! \
    evening_routine_details:text! \
    daytime_activity_level:string! \
    social_interaction:string! \
    environmental_notes:text! \
    --htmx

cargo loco generate scaffold assessment_carer_impact \
    assessment:references \
    carer_stress_level:string! \
    carer_sleep_disruption:string! \
    carer_physical_health_impact:string! \
    carer_mental_health_impact:string! \
    carer_burnout_risk:string! \
    respite_care_available:string! \
    respite_care_frequency:string! \
    formal_support_services:string! \
    formal_support_details:text! \
    carer_training_received:string! \
    carer_support_group:string! \
    safeguarding_concerns:string! \
    safeguarding_details:text! \
    carer_impact_notes:text! \
    --htmx

cargo loco generate scaffold assessment_management_plan \
    assessment:references \
    non_pharmacological_interventions:string! \
    light_therapy:string! \
    music_therapy:string! \
    aromatherapy:string! \
    structured_activities:string! \
    exercise_programme:string! \
    sleep_hygiene_plan:string! \
    environmental_modifications:string! \
    environmental_modifications_details:text! \
    pharmacological_review:string! \
    pharmacological_review_details:text! \
    referral_to_specialist:string! \
    specialist_type:string! \
    carer_support_plan:string! \
    follow_up_interval:string! \
    safety_plan:string! \
    safety_plan_details:text! \
    management_plan_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    cmai_score:int \
    npi_total_score:int \
    overall_severity:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
