//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Model.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "neurodiversity_adjustment_requests")]
#[allow(clippy::struct_excessive_bools)] // mirrors the form's sql/ boolean columns (source of truth)
pub struct Model {
    /// Created at.
    pub created_at: DateTimeWithTimeZone,
    /// Updated at.
    pub updated_at: DateTimeWithTimeZone,
    /// ID.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// Deleted at.
    pub deleted_at: Option<DateTimeWithTimeZone>,
    /// Status.
    pub status: String,
    /// Requested by.
    pub requested_by: String,
    /// Request date.
    pub request_date: Option<Date>,
    /// Requested start date.
    pub requested_start_date: Option<Date>,
    /// Condition adhd.
    pub condition_adhd: bool,
    /// Condition autism.
    pub condition_autism: bool,
    /// Condition dyslexia.
    pub condition_dyslexia: bool,
    /// Condition dyspraxia.
    pub condition_dyspraxia: bool,
    /// Condition dyscalculia.
    pub condition_dyscalculia: bool,
    /// Condition tourettes.
    pub condition_tourettes: bool,
    /// Condition other.
    pub condition_other: bool,
    /// Condition other detail.
    pub condition_other_detail: String,
    /// Diagnosis status.
    pub diagnosis_status: String,
    /// Considers disability.
    pub considers_disability: String,
    /// Substantial long term impact.
    pub substantial_long_term_impact: bool,
    /// Disclosure consent.
    pub disclosure_consent: bool,
    /// Difficulty concentration.
    pub difficulty_concentration: bool,
    /// Difficulty written communication.
    pub difficulty_written_communication: bool,
    /// Difficulty organisation time.
    pub difficulty_organisation_time: bool,
    /// Difficulty sensory overload.
    pub difficulty_sensory_overload: bool,
    /// Difficulty balance coordination.
    pub difficulty_balance_coordination: bool,
    /// Difficulty social communication.
    pub difficulty_social_communication: bool,
    /// Difficulty memory.
    pub difficulty_memory: bool,
    /// Difficulty burnout wellbeing.
    pub difficulty_burnout_wellbeing: bool,
    /// Tasks situations affected.
    pub tasks_situations_affected: String,
    /// Worker strengths.
    pub worker_strengths: String,
    /// Adjustment working environment.
    pub adjustment_working_environment: bool,
    /// Adjustment equipment technology.
    pub adjustment_equipment_technology: bool,
    /// Adjustment working arrangements.
    pub adjustment_working_arrangements: bool,
    /// Adjustment communication.
    pub adjustment_communication: bool,
    /// Adjustment support mentoring.
    pub adjustment_support_mentoring: bool,
    /// Adjustment recruitment process.
    pub adjustment_recruitment_process: bool,
    /// Adjustment policy dress.
    pub adjustment_policy_dress: bool,
    /// Adjustment other.
    pub adjustment_other: bool,
    /// Adjustments requested detail.
    pub adjustments_requested_detail: String,
    /// Supporting evidence type.
    pub supporting_evidence_type: String,
    /// Occupational health involved.
    pub occupational_health_involved: bool,
    /// Access to work involved.
    pub access_to_work_involved: bool,
    /// Current impact.
    pub current_impact: String,
    /// At risk of absence.
    pub at_risk_of_absence: bool,
    /// Urgency.
    pub urgency: String,
    /// Notes.
    pub notes: String,
    /// Worker ID.
    pub worker_id: Uuid,
    /// Manager ID.
    pub manager_id: Uuid,
}

/// Relation.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::managers::Entity",
        from = "Column::ManagerId",
        to = "super::managers::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Managers.
    Managers,
    /// Neurodiversity adjustment request grades.
    #[sea_orm(has_many = "super::neurodiversity_adjustment_request_grades::Entity")]
    NeurodiversityAdjustmentRequestGrades,
    #[sea_orm(
        belongs_to = "super::workers::Entity",
        from = "Column::WorkerId",
        to = "super::workers::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Workers.
    Workers,
}

impl Related<super::managers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Managers.def()
    }
}

impl Related<super::neurodiversity_adjustment_request_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NeurodiversityAdjustmentRequestGrades.def()
    }
}

impl Related<super::workers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workers.def()
    }
}
