import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		psqiScore: 3,
		sleepQuality: 'Good sleep quality',
		primaryConcern: 'Mild insomnia',
		snoringFlag: false,
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		psqiScore: 8,
		sleepQuality: 'Poor sleep quality',
		primaryConcern: 'Sleep onset difficulty',
		snoringFlag: true,
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		psqiScore: 14,
		sleepQuality: 'Sleep disorder likely',
		primaryConcern: 'Chronic insomnia with sleep apnea',
		snoringFlag: true,
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		psqiScore: 2,
		sleepQuality: 'Good sleep quality',
		primaryConcern: 'Routine assessment',
		snoringFlag: false,
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		psqiScore: 18,
		sleepQuality: 'Severe sleep disturbance',
		primaryConcern: 'Severe insomnia and daytime dysfunction',
		snoringFlag: true,
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		psqiScore: 5,
		sleepQuality: 'Good sleep quality',
		primaryConcern: 'Shift work sleep disorder',
		snoringFlag: false,
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		psqiScore: 11,
		sleepQuality: 'Sleep disorder likely',
		primaryConcern: 'Restless legs syndrome',
		snoringFlag: false,
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		psqiScore: 7,
		sleepQuality: 'Poor sleep quality',
		primaryConcern: 'Pain-related sleep disruption',
		snoringFlag: false,
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		psqiScore: 13,
		sleepQuality: 'Sleep disorder likely',
		primaryConcern: 'Sleep maintenance insomnia',
		snoringFlag: true,
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		psqiScore: 1,
		sleepQuality: 'Good sleep quality',
		primaryConcern: 'Follow-up assessment',
		snoringFlag: false,
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		psqiScore: 9,
		sleepQuality: 'Poor sleep quality',
		primaryConcern: 'Anxiety-related insomnia',
		snoringFlag: false,
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		psqiScore: 17,
		sleepQuality: 'Severe sleep disturbance',
		primaryConcern: 'Obstructive sleep apnea',
		snoringFlag: true,
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		psqiScore: 4,
		sleepQuality: 'Good sleep quality',
		primaryConcern: 'Occasional nightmares',
		snoringFlag: false,
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		psqiScore: 12,
		sleepQuality: 'Sleep disorder likely',
		primaryConcern: 'Medication-related sleep issues',
		snoringFlag: true,
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		psqiScore: 0,
		sleepQuality: 'Good sleep quality',
		primaryConcern: 'Annual screening',
		snoringFlag: false,
	},
];
