CREATE TABLE casualty_card (
    -- Primary key: UUIDv4 generated by the database
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key to the patient this casualty card belongs to
    patient_id          UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,

    -- Workflow status tracking
    status              TEXT NOT NULL DEFAULT 'in_progress'
                        CHECK (status IN ('in_progress', 'completed', 'reviewed', '')),

    -- Attendance timing
    attendance_date     DATE,
    arrival_time        TIMESTAMPTZ,

    -- Audit timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for the most common query: all casualty cards for a patient
CREATE INDEX idx_casualty_card_patient_id ON casualty_card(patient_id);

-- Auto-update updated_at on every row change
CREATE TRIGGER trigger_casualty_card_updated_at
    BEFORE UPDATE ON casualty_card
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE casualty_card IS
    'A single ED or MIU attendance record. Child tables hold section-specific clinical data.';
COMMENT ON COLUMN casualty_card.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN casualty_card.patient_id IS
    'FK to patient. One patient may have many casualty cards.';
COMMENT ON COLUMN casualty_card.status IS
    'Workflow status: in_progress, completed, reviewed, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card.attendance_date IS
    'Date of ED attendance. NULL if not recorded.';
COMMENT ON COLUMN casualty_card.arrival_time IS
    'Timestamp of patient arrival at the department. NULL if not recorded.';
COMMENT ON COLUMN casualty_card.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN casualty_card.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
