-- ============================================================
-- 12_casualty_card_vital_signs.sql
-- Vital signs observations (1:1 with casualty_card).
-- ============================================================
-- Records the initial set of vital signs from which the
-- NEWS2 score is auto-calculated. Includes pupil assessment,
-- capillary refill time, and weight.
-- ============================================================

CREATE TABLE casualty_card_vital_signs (
    -- Primary key: UUIDv4 generated by the database
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- 1:1 relationship with casualty_card (UNIQUE constraint)
    casualty_card_id        UUID NOT NULL UNIQUE REFERENCES casualty_card(id) ON DELETE CASCADE,

    -- Cardiovascular
    heart_rate              INTEGER
                            CHECK (heart_rate IS NULL OR (heart_rate >= 0 AND heart_rate <= 300)),
    systolic_bp             INTEGER
                            CHECK (systolic_bp IS NULL OR (systolic_bp >= 0 AND systolic_bp <= 400)),
    diastolic_bp            INTEGER
                            CHECK (diastolic_bp IS NULL OR (diastolic_bp >= 0 AND diastolic_bp <= 300)),

    -- Respiratory
    respiratory_rate        INTEGER
                            CHECK (respiratory_rate IS NULL OR (respiratory_rate >= 0 AND respiratory_rate <= 100)),
    oxygen_saturation       INTEGER
                            CHECK (oxygen_saturation IS NULL OR (oxygen_saturation >= 0 AND oxygen_saturation <= 100)),
    supplemental_oxygen     TEXT NOT NULL DEFAULT ''
                            CHECK (supplemental_oxygen IN ('yes', 'no', '')),
    oxygen_flow_rate        TEXT NOT NULL DEFAULT '',

    -- Temperature
    temperature             NUMERIC(4,1)
                            CHECK (temperature IS NULL OR (temperature >= 25.0 AND temperature <= 45.0)),

    -- Blood glucose
    blood_glucose           NUMERIC(4,1)
                            CHECK (blood_glucose IS NULL OR blood_glucose >= 0),

    -- Consciousness (AVPU scale, used in NEWS2)
    consciousness_level     TEXT NOT NULL DEFAULT ''
                            CHECK (consciousness_level IN ('alert', 'verbal', 'pain', 'unresponsive', '')),

    -- Pupil assessment
    pupil_left_size         INTEGER
                            CHECK (pupil_left_size IS NULL OR (pupil_left_size >= 1 AND pupil_left_size <= 9)),
    pupil_left_reactive     TEXT NOT NULL DEFAULT ''
                            CHECK (pupil_left_reactive IN ('yes', 'no', '')),
    pupil_right_size        INTEGER
                            CHECK (pupil_right_size IS NULL OR (pupil_right_size >= 1 AND pupil_right_size <= 9)),
    pupil_right_reactive    TEXT NOT NULL DEFAULT ''
                            CHECK (pupil_right_reactive IN ('yes', 'no', '')),

    -- Other observations
    capillary_refill_time   TEXT NOT NULL DEFAULT '',
    weight                  NUMERIC(5,1)
                            CHECK (weight IS NULL OR weight > 0),

    -- Audit timestamps
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_casualty_card_vital_signs_updated_at
    BEFORE UPDATE ON casualty_card_vital_signs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE casualty_card_vital_signs IS
    '1:1 with casualty_card. Vital signs observations used for NEWS2 auto-calculation.';
COMMENT ON COLUMN casualty_card_vital_signs.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN casualty_card_vital_signs.casualty_card_id IS
    'FK to casualty_card (UNIQUE = 1:1 relationship).';
COMMENT ON COLUMN casualty_card_vital_signs.heart_rate IS
    'Heart rate in beats per minute. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.systolic_bp IS
    'Systolic blood pressure in mmHg. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.diastolic_bp IS
    'Diastolic blood pressure in mmHg. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.respiratory_rate IS
    'Respiratory rate in breaths per minute. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.oxygen_saturation IS
    'Peripheral oxygen saturation (SpO2) as a percentage. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.supplemental_oxygen IS
    'Whether patient is on supplemental oxygen: yes, no, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_vital_signs.oxygen_flow_rate IS
    'Oxygen flow rate (e.g. 2L/min, 15L NRB).';
COMMENT ON COLUMN casualty_card_vital_signs.temperature IS
    'Core temperature in degrees Celsius. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.blood_glucose IS
    'Blood glucose in mmol/L. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.consciousness_level IS
    'AVPU consciousness level: alert, verbal, pain, unresponsive, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_vital_signs.pupil_left_size IS
    'Left pupil size in mm (1-9). NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.pupil_left_reactive IS
    'Whether the left pupil is reactive to light: yes, no, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_vital_signs.pupil_right_size IS
    'Right pupil size in mm (1-9). NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.pupil_right_reactive IS
    'Whether the right pupil is reactive to light: yes, no, or empty string if unanswered.';
COMMENT ON COLUMN casualty_card_vital_signs.capillary_refill_time IS
    'Capillary refill time (e.g. less than 2 seconds, 3 seconds).';
COMMENT ON COLUMN casualty_card_vital_signs.weight IS
    'Patient weight in kilograms. NULL if not recorded.';
COMMENT ON COLUMN casualty_card_vital_signs.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN casualty_card_vital_signs.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
