#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding semaglutide-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    ethnicity:string! \
    occupation:string! \
    referring_physician:string! \
    referral_date:date \
    smoking_status:string! \
    alcohol_use:string! \
    --htmx

cargo loco generate scaffold assessment_indication_goals \
    assessment:references \
    primary_indication:string! \
    indication_other:text! \
    weight_loss_goal_kg:double \
    target_hba1c_percent:double \
    previous_weight_loss_attempts:string! \
    previous_attempts_details:text! \
    previous_glp1_use:string! \
    previous_glp1_details:text! \
    patient_motivation:string! \
    realistic_expectations_discussed:string! \
    --htmx

cargo loco generate scaffold assessment_body_composition \
    assessment:references \
    current_weight_kg:double \
    height_cm:double \
    bmi:double \
    waist_circumference_cm:double \
    hip_circumference_cm:double \
    waist_hip_ratio:double \
    body_fat_percentage:double \
    highest_lifetime_weight_kg:double \
    weight_change_last_6_months_kg:double \
    bmi_category:string! \
    --htmx

cargo loco generate scaffold assessment_metabolic_profile \
    assessment:references \
    fasting_glucose_mmol_l:double \
    hba1c_percent:double \
    hba1c_mmol_mol:double \
    diabetes_diagnosis:string! \
    diabetes_type:string! \
    diabetes_duration_years:int \
    total_cholesterol_mmol_l:double \
    ldl_cholesterol_mmol_l:double \
    hdl_cholesterol_mmol_l:double \
    triglycerides_mmol_l:double \
    insulin_resistance_suspected:string! \
    metabolic_syndrome:string! \
    thyroid_function_normal:string! \
    tsh_miu_l:double \
    lab_date:date \
    --htmx

cargo loco generate scaffold assessment_cardiovascular_risk \
    assessment:references \
    hypertension:string! \
    systolic_bp_mmhg:int \
    diastolic_bp_mmhg:int \
    resting_heart_rate_bpm:int \
    history_of_mi:string! \
    history_of_stroke:string! \
    peripheral_arterial_disease:string! \
    heart_failure:string! \
    heart_failure_nyha_class:string! \
    atrial_fibrillation:string! \
    family_history_cvd:string! \
    family_history_cvd_details:text! \
    obstructive_sleep_apnoea:string! \
    --htmx

cargo loco generate scaffold assessment_contraindications_screening \
    assessment:references \
    personal_medullary_thyroid_carcinoma:string! \
    family_medullary_thyroid_carcinoma:string! \
    men2_syndrome:string! \
    type1_diabetes:string! \
    pregnancy:string! \
    breastfeeding:string! \
    planning_pregnancy:string! \
    history_of_pancreatitis:string! \
    gallbladder_disease:string! \
    severe_renal_impairment:string! \
    egfr_ml_min:double \
    diabetic_retinopathy:string! \
    history_of_eating_disorder:string! \
    known_hypersensitivity_glp1:string! \
    additional_contraindications:text! \
    --htmx

cargo loco generate scaffold assessment_gi_history \
    assessment:references \
    history_of_nausea:string! \
    history_of_vomiting:string! \
    chronic_diarrhoea:string! \
    chronic_constipation:string! \
    gastroesophageal_reflux:string! \
    gastroparesis:string! \
    inflammatory_bowel_disease:string! \
    ibd_type:string! \
    irritable_bowel_syndrome:string! \
    previous_gi_surgery:string! \
    gi_surgery_details:text! \
    previous_bariatric_surgery:string! \
    bariatric_surgery_type:text! \
    current_gi_symptoms:text! \
    --htmx

cargo loco generate scaffold assessment_current_medications \
    assessment:references \
    currently_on_insulin:string! \
    insulin_type:text! \
    insulin_dose:text! \
    currently_on_sulfonylurea:string! \
    sulfonylurea_name:text! \
    currently_on_metformin:string! \
    metformin_dose_mg:int \
    currently_on_sglt2_inhibitor:string! \
    sglt2_inhibitor_name:text! \
    currently_on_other_glp1:string! \
    other_glp1_name:text! \
    antihypertensive_use:string! \
    antihypertensive_details:text! \
    statin_use:string! \
    anticoagulant_use:string! \
    oral_contraceptive_use:string! \
    other_medications:text! \
    --htmx

cargo loco generate scaffold assessment_mental_health_screening \
    assessment:references \
    history_of_depression:string! \
    current_depression:string! \
    depression_treatment:string! \
    depression_treatment_details:text! \
    history_of_anxiety:string! \
    current_anxiety:string! \
    suicidal_ideation_history:string! \
    current_suicidal_ideation:string! \
    history_of_eating_disorder:string! \
    eating_disorder_type:string! \
    eating_disorder_details:text! \
    binge_eating_current:string! \
    body_image_concerns:string! \
    phq2_score:int \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_treatment_plan \
    assessment:references \
    semaglutide_formulation:string! \
    brand_name:string! \
    starting_dose:text! \
    dose_escalation_plan:text! \
    injection_site_education:string! \
    dietary_counselling_provided:string! \
    exercise_plan_discussed:string! \
    behavioural_support_referral:string! \
    monitoring_plan:text! \
    follow_up_interval_weeks:int \
    insulin_dose_adjustment_needed:string! \
    sulfonylurea_dose_adjustment_needed:string! \
    informed_consent_obtained:string! \
    side_effects_discussed:string! \
    clinician_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    eligibility_status:string! \
    absolute_contraindication_count:int! \
    relative_contraindication_count:int! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
