//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "microbiology_culture_test_request_grade_rules")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub rule_id: String,
    pub axis: String,
    pub category: String,
    pub description: String,
    pub microbiology_culture_test_request_grade_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::microbiology_culture_test_request_grades::Entity",
        from = "Column::MicrobiologyCultureTestRequestGradeId",
        to = "super::microbiology_culture_test_request_grades::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MicrobiologyCultureTestRequestGrades,
}

impl Related<super::microbiology_culture_test_request_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MicrobiologyCultureTestRequestGrades.def()
    }
}
