window.SAMPLE_ASSESSMENTS = [
  {
    id: 'A001',
    patient: 'Alice Smith',
    nhs: '123 456 7890',
    dob: '1952-03-11',
    procedure: 'Right hip arthroplasty',
    urgency: 'elective',
    severity: 'major-plus',
    asa: 'III',
    composite: 'high',
    flags: ['difficult-airway', 'severe-cardiac'],
    clinician: 'Dr B Adams',
    date: '2026-04-20',
  },
  {
    id: 'A002',
    patient: 'Bob Jones',
    nhs: '234 567 8901',
    dob: '1978-09-04',
    procedure: 'Laparoscopic cholecystectomy',
    urgency: 'elective',
    severity: 'intermediate',
    asa: 'II',
    composite: 'moderate',
    flags: [],
    clinician: 'Dr C Patel',
    date: '2026-04-20',
  },
  {
    id: 'A003',
    patient: 'Carol Lee',
    nhs: '345 678 9012',
    dob: '1940-11-21',
    procedure: 'Dynamic hip screw',
    urgency: 'emergency',
    severity: 'major',
    asa: 'IV',
    composite: 'critical',
    flags: ['severe-frailty', 'severe-cardiac', 'fasting-violation'],
    clinician: 'Dr D Williams',
    date: '2026-04-21',
  },
  {
    id: 'A004',
    patient: 'David Brown',
    nhs: '456 789 0123',
    dob: '1990-07-15',
    procedure: 'Inguinal hernia repair',
    urgency: 'elective',
    severity: 'intermediate',
    asa: 'I',
    composite: 'low',
    flags: [],
    clinician: 'Dr E Khan',
    date: '2026-04-21',
  },
];
