logger:
  enable: true
  pretty_backtrace: true
  level: warn
  format: compact

server:
  port: 5160
  binding: localhost
  host: http://localhost
  middlewares:
    cors:
      enable: true
      allow_origins:
        - http://localhost:5160
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization

database:
  uri: postgres://localhost:5432/patient_intake_tera_test
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 1
  auto_migrate: true
  dangerously_truncate: true
  dangerously_recreate: false
