import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		fmsScore: 19,
		movementCategory: 'Excellent',
		sportType: 'Football',
		painFlag: false,
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		fmsScore: 14,
		movementCategory: 'Good',
		sportType: 'Running',
		painFlag: true,
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		fmsScore: 8,
		movementCategory: 'Poor',
		sportType: 'Tennis',
		painFlag: true,
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		fmsScore: 21,
		movementCategory: 'Excellent',
		sportType: 'Swimming',
		painFlag: false,
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		fmsScore: 6,
		movementCategory: 'Poor',
		sportType: 'CrossFit',
		painFlag: true,
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		fmsScore: 16,
		movementCategory: 'Good',
		sportType: 'Rugby',
		painFlag: false,
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		fmsScore: 12,
		movementCategory: 'Fair',
		sportType: 'Cycling',
		painFlag: true,
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		fmsScore: 15,
		movementCategory: 'Good',
		sportType: 'Basketball',
		painFlag: false,
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		fmsScore: 10,
		movementCategory: 'Fair',
		sportType: 'Gymnastics',
		painFlag: false,
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		fmsScore: 18,
		movementCategory: 'Excellent',
		sportType: 'Cricket',
		painFlag: false,
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		fmsScore: 9,
		movementCategory: 'Poor',
		sportType: 'Netball',
		painFlag: true,
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		fmsScore: 13,
		movementCategory: 'Fair',
		sportType: 'Weightlifting',
		painFlag: false,
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		fmsScore: 17,
		movementCategory: 'Good',
		sportType: 'Yoga',
		painFlag: false,
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		fmsScore: 7,
		movementCategory: 'Poor',
		sportType: 'Hockey',
		painFlag: true,
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		fmsScore: 20,
		movementCategory: 'Excellent',
		sportType: 'Athletics',
		painFlag: false,
	},
];
