//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "columbia_suicide_severity_rating_scales")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub clinician_name: String,
    pub clinician_role: String,
    pub assessed_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    pub scale_version: String,
    #[sea_orm(column_type = "Text")]
    pub reason_for_assessment: String,
    pub patient_identifier: String,
    pub age_band: String,
    pub sex: String,
    pub wish_to_be_dead: String,
    pub non_specific_active_thoughts: String,
    pub active_ideation_methods: String,
    pub active_ideation_intent: String,
    pub active_ideation_plan: String,
    pub ideation_timeframe: String,
    pub ideation_frequency: Option<i32>,
    pub ideation_duration: Option<i32>,
    pub ideation_controllability: Option<i32>,
    pub ideation_deterrents: Option<i32>,
    pub ideation_reasons: Option<i32>,
    pub actual_attempt: String,
    pub interrupted_attempt: String,
    pub aborted_attempt: String,
    pub preparatory_acts: String,
    pub non_suicidal_self_injury: String,
    pub behaviour_recency: String,
    pub lifetime_attempt_count: Option<i32>,
    pub most_recent_attempt_date: Option<Date>,
    pub actual_lethality: Option<i32>,
    pub potential_lethality: Option<i32>,
    pub access_to_lethal_means: String,
    #[sea_orm(column_type = "Text")]
    pub protective_factors: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_note: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::columbia_suicide_severity_rating_scale_grades::Entity")]
    ColumbiaSuicideSeverityRatingScaleGrades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::columbia_suicide_severity_rating_scale_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColumbiaSuicideSeverityRatingScaleGrades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
