//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "edinburgh_postnatal_depression_scale_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub total_score: Option<i32>,
    pub interpretation: String,
    pub item_10_score: Option<i32>,
    pub self_harm_flag: String,
    pub graded_at: DateTimeWithTimeZone,
    pub edinburgh_postnatal_depression_scale_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::edinburgh_postnatal_depression_scale_grade_flags::Entity")]
    EdinburghPostnatalDepressionScaleGradeFlags,
    #[sea_orm(has_many = "super::edinburgh_postnatal_depression_scale_grade_rules::Entity")]
    EdinburghPostnatalDepressionScaleGradeRules,
    #[sea_orm(
        belongs_to = "super::edinburgh_postnatal_depression_scales::Entity",
        from = "Column::EdinburghPostnatalDepressionScaleId",
        to = "super::edinburgh_postnatal_depression_scales::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    EdinburghPostnatalDepressionScales,
}

impl Related<super::edinburgh_postnatal_depression_scale_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EdinburghPostnatalDepressionScaleGradeFlags.def()
    }
}

impl Related<super::edinburgh_postnatal_depression_scale_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EdinburghPostnatalDepressionScaleGradeRules.def()
    }
}

impl Related<super::edinburgh_postnatal_depression_scales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EdinburghPostnatalDepressionScales.def()
    }
}
