#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding advance-statement-about-care (14 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_personal_information \
    assessment:references \
    full_name:string! \
    address:text! \
    postcode:string! \
    date_of_birth:date \
    nhs_number:string! \
    phone:string! \
    email:string! \
    gp_name:string! \
    gp_practice:string! \
    --htmx

cargo loco generate scaffold assessment_statement_context \
    assessment:references \
    reason_for_statement:text! \
    current_health_status:text! \
    current_diagnoses:text! \
    has_discussed_with_family:string! \
    has_discussed_with_clinician:string! \
    discussion_details:text! \
    --htmx

cargo loco generate scaffold assessment_values_beliefs \
    assessment:references \
    personal_values:text! \
    quality_of_life_priorities:text! \
    religious_beliefs:text! \
    spiritual_needs:text! \
    cultural_considerations:text! \
    fears_and_concerns:text! \
    things_that_matter_most:text! \
    --htmx

cargo loco generate scaffold assessment_care_preferences \
    assessment:references \
    preferred_place_of_care:text! \
    preferred_place_of_death:text! \
    daily_routine_preferences:text! \
    personal_care_preferences:text! \
    food_and_drink_preferences:text! \
    sleep_preferences:text! \
    clothing_preferences:text! \
    environment_preferences:text! \
    pet_care_wishes:text! \
    --htmx

cargo loco generate scaffold assessment_medical_treatment_wishes \
    assessment:references \
    pain_management_preferences:text! \
    attitude_to_hospital_admission:text! \
    attitude_to_intensive_care:text! \
    attitude_to_artificial_nutrition:text! \
    attitude_to_artificial_hydration:text! \
    medication_preferences:text! \
    complementary_therapy_preferences:text! \
    other_treatment_wishes:text! \
    --htmx

cargo loco generate scaffold assessment_communication_preferences \
    assessment:references \
    preferred_language:string! \
    communication_aids:text! \
    how_to_share_information:text! \
    who_to_involve_in_decisions:text! \
    information_sharing_restrictions:text! \
    preferred_communication_style:text! \
    --htmx

cargo loco generate scaffold assessment_people_important_to_me \
    assessment:references \
    primary_contact_name:string! \
    primary_contact_relationship:string! \
    primary_contact_phone:string! \
    primary_contact_email:string! \
    secondary_contact_name:string! \
    secondary_contact_relationship:string! \
    secondary_contact_phone:string! \
    people_who_should_visit:text! \
    people_who_should_not_visit:text! \
    support_network_details:text! \
    --htmx

cargo loco generate scaffold assessment_practical_matters \
    assessment:references \
    financial_arrangements:text! \
    property_arrangements:text! \
    insurance_details:text! \
    will_location:text! \
    has_lasting_power_of_attorney:string! \
    lpa_details:text! \
    funeral_wishes:text! \
    burial_or_cremation:string! \
    other_practical_matters:text! \
    --htmx

cargo loco generate scaffold assessment_signatures_witnesses \
    assessment:references \
    maker_signature_obtained:string! \
    maker_signature_date:date \
    witness_name:string! \
    witness_address:text! \
    witness_signature_obtained:string! \
    witness_signature_date:date \
    review_date:date \
    review_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    completeness_level:string! \
    sections_completed:int! \
    total_sections:int! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    completeness_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
