#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding prescription-request (9 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    phone:string! \
    email:string! \
    --htmx

cargo loco generate scaffold clinician \
    first_name:string! \
    last_name:string! \
    nhs_employee_number:string^ \
    phone:string! \
    email:string! \
    --htmx

cargo loco generate scaffold prescription_request \
    patient:references \
    clinician:references \
    status:string! \
    --htmx

cargo loco generate scaffold prescription_details \
    prescription_request:references \
    request_date:date! \
    medication_name:string! \
    dosage:string! \
    frequency:string! \
    route_of_administration:string! \
    treatment_instructions:text! \
    --htmx

cargo loco generate scaffold prescription_substitution_options \
    prescription_request:references \
    allow_brand_substitution:string! \
    allow_generic_substitution:string! \
    allow_dosage_adjustment:string! \
    substitution_notes:text! \
    --htmx

cargo loco generate scaffold prescription_request_type \
    prescription_request:references \
    is_new_prescription:string! \
    is_emergency:string! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    prescription_request:references \
    priority_level:string! \
    rule_count:int! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
