#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding cognitive-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    preferred_name:string! \
    gender_identity:string! \
    ethnicity:string! \
    preferred_language:string! \
    interpreter_required:string! \
    education_level:string! \
    years_of_education:int \
    handedness:string! \
    gp_name:string! \
    gp_practice:string! \
    --htmx

cargo loco generate scaffold assessment_referral_information \
    assessment:references \
    referrer_name:string! \
    referrer_role:string! \
    referral_date:date \
    reason_for_referral:text! \
    presenting_complaint:text! \
    symptom_duration_months:int \
    symptom_onset:string! \
    informant_name:string! \
    informant_relationship:string! \
    informant_available:string! \
    referral_notes:text! \
    --htmx

cargo loco generate scaffold assessment_orientation \
    assessment:references \
    orientation_year:string! \
    orientation_season:string! \
    orientation_month:string! \
    orientation_date:string! \
    orientation_day:string! \
    orientation_time_score:int \
    orientation_country:string! \
    orientation_county:string! \
    orientation_city:string! \
    orientation_building:string! \
    orientation_floor:string! \
    orientation_place_score:int \
    orientation_notes:text! \
    --htmx

cargo loco generate scaffold assessment_registration \
    assessment:references \
    word_1:string! \
    word_1_recalled:string! \
    word_2:string! \
    word_2_recalled:string! \
    word_3:string! \
    word_3_recalled:string! \
    registration_score:int \
    number_of_trials:int \
    registration_notes:text! \
    --htmx

cargo loco generate scaffold assessment_attention_calculation \
    assessment:references \
    test_used:string! \
    serial_7s_attempt_1:string! \
    serial_7s_attempt_2:string! \
    serial_7s_attempt_3:string! \
    serial_7s_attempt_4:string! \
    serial_7s_attempt_5:string! \
    world_letter_1:string! \
    world_letter_2:string! \
    world_letter_3:string! \
    world_letter_4:string! \
    world_letter_5:string! \
    attention_score:int \
    attention_notes:text! \
    --htmx

cargo loco generate scaffold assessment_recall \
    assessment:references \
    word_1_recalled:string! \
    word_2_recalled:string! \
    word_3_recalled:string! \
    recall_score:int \
    cueing_required:string! \
    cueing_details:text! \
    recall_notes:text! \
    --htmx

cargo loco generate scaffold assessment_language \
    assessment:references \
    naming_object_1:string! \
    naming_object_1_correct:string! \
    naming_object_2:string! \
    naming_object_2_correct:string! \
    naming_score:int \
    repetition_correct:string! \
    repetition_score:int \
    language_notes:text! \
    --htmx

cargo loco generate scaffold assessment_repetition_commands \
    assessment:references \
    command_take_paper:string! \
    command_fold_paper:string! \
    command_put_on_floor:string! \
    three_stage_command_score:int \
    reading_instruction_followed:string! \
    reading_score:int \
    writing_sentence_produced:string! \
    writing_score:int \
    commands_notes:text! \
    --htmx

cargo loco generate scaffold assessment_visuospatial \
    assessment:references \
    pentagon_copy_correct:string! \
    visuospatial_score:int \
    pentagon_quality:string! \
    tremor_observed:string! \
    visuospatial_notes:text! \
    --htmx

cargo loco generate scaffold assessment_functional_history \
    assessment:references \
    managing_finances:string! \
    managing_medications:string! \
    using_telephone:string! \
    meal_preparation:string! \
    shopping:string! \
    housekeeping:string! \
    transportation:string! \
    personal_care:string! \
    driving_status:string! \
    safety_concerns:string! \
    safety_concern_details:text! \
    wandering_risk:string! \
    carer_name:string! \
    carer_relationship:string! \
    carer_strain:string! \
    functional_history_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    mmse_total_score:int! \
    cognitive_category:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
