//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "meetings")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub title: String,
    pub purpose: String,
    #[sea_orm(column_type = "Text")]
    pub long_description: String,
    pub category: String,
    pub visibility: String,
    pub scheduled_start_at: Option<DateTimeWithTimeZone>,
    pub scheduled_end_at: Option<DateTimeWithTimeZone>,
    pub timezone: String,
    pub location: String,
    pub video_url: String,
    pub phone_number: String,
    pub dial_in_code: String,
    #[sea_orm(column_type = "Text")]
    pub joining_instructions: String,
    pub calendar_uid: String,
    pub summary: String,
    pub actual_start_at: Option<DateTimeWithTimeZone>,
    pub actual_end_at: Option<DateTimeWithTimeZone>,
    pub overall_result: String,
    #[sea_orm(column_type = "Text")]
    pub additional_notes: String,
    pub signed_by_name: String,
    pub signed_at: Option<DateTimeWithTimeZone>,
    pub organizer_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::action_items::Entity")]
    ActionItems,
    #[sea_orm(has_many = "super::agenda_items::Entity")]
    AgendaItems,
    #[sea_orm(has_many = "super::meeting_outputs::Entity")]
    MeetingOutputs,
    #[sea_orm(
        belongs_to = "super::organizers::Entity",
        from = "Column::OrganizerId",
        to = "super::organizers::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organizers,
    #[sea_orm(has_many = "super::participants::Entity")]
    Participants,
    #[sea_orm(has_many = "super::recurring_rules::Entity")]
    RecurringRules,
    #[sea_orm(has_many = "super::resources::Entity")]
    Resources,
}

impl Related<super::action_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActionItems.def()
    }
}

impl Related<super::agenda_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgendaItems.def()
    }
}

impl Related<super::meeting_outputs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MeetingOutputs.def()
    }
}

impl Related<super::organizers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizers.def()
    }
}

impl Related<super::participants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Participants.def()
    }
}

impl Related<super::recurring_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecurringRules.def()
    }
}

impl Related<super::resources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Resources.def()
    }
}
