//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "recurring_rules")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub frequency: String,
    pub interval_count: i32,
    pub by_day_of_week: String,
    pub by_day_of_month: Option<i32>,
    pub by_set_position: Option<i32>,
    pub by_month_of_year: Option<i32>,
    pub series_count: Option<i32>,
    pub series_until: Option<DateTimeWithTimeZone>,
    pub timezone: String,
    pub rrule_text: String,
    pub meeting_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::meetings::Entity",
        from = "Column::MeetingId",
        to = "super::meetings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Meetings,
}

impl Related<super::meetings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meetings.def()
    }
}
