import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		news2Score: 2,
		news2Response: 'low',
		mtsCategory: '4-standard',
		chiefComplaint: 'Laceration to right forearm',
		allergyFlag: false,
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		news2Score: 6,
		news2Response: 'medium',
		mtsCategory: '2-very-urgent',
		chiefComplaint: 'Chest pain radiating to left arm',
		allergyFlag: true,
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		news2Score: 9,
		news2Response: 'high',
		mtsCategory: '1-immediate',
		chiefComplaint: 'Collapse with unresponsiveness',
		allergyFlag: false,
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		news2Score: 0,
		news2Response: 'low',
		mtsCategory: '5-non-urgent',
		chiefComplaint: 'Insect bite to left ankle',
		allergyFlag: false,
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		news2Score: 8,
		news2Response: 'high',
		mtsCategory: '1-immediate',
		chiefComplaint: 'Acute asthma exacerbation',
		allergyFlag: true,
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		news2Score: 1,
		news2Response: 'low',
		mtsCategory: '4-standard',
		chiefComplaint: 'Twisted right ankle playing football',
		allergyFlag: false,
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		news2Score: 4,
		news2Response: 'low-medium',
		mtsCategory: '3-urgent',
		chiefComplaint: 'Abdominal pain with vomiting',
		allergyFlag: true,
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		news2Score: 5,
		news2Response: 'medium',
		mtsCategory: '2-very-urgent',
		chiefComplaint: 'Acute confusion in elderly patient',
		allergyFlag: false,
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		news2Score: 7,
		news2Response: 'high',
		mtsCategory: '2-very-urgent',
		chiefComplaint: 'Sepsis query -- fever and tachycardia',
		allergyFlag: false,
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		news2Score: 0,
		news2Response: 'low',
		mtsCategory: '5-non-urgent',
		chiefComplaint: 'Foreign body in ear',
		allergyFlag: false,
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		news2Score: 3,
		news2Response: 'low-medium',
		mtsCategory: '3-urgent',
		chiefComplaint: 'Head injury with brief loss of consciousness',
		allergyFlag: true,
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		news2Score: 10,
		news2Response: 'high',
		mtsCategory: '1-immediate',
		chiefComplaint: 'Major trauma -- RTC pedestrian vs car',
		allergyFlag: false,
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		news2Score: 1,
		news2Response: 'low',
		mtsCategory: '4-standard',
		chiefComplaint: 'Lower back pain -- 3 days duration',
		allergyFlag: false,
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		news2Score: 3,
		news2Response: 'low-medium',
		mtsCategory: '3-urgent',
		chiefComplaint: 'Overdose -- paracetamol ingestion',
		allergyFlag: true,
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		news2Score: 2,
		news2Response: 'low',
		mtsCategory: '3-urgent',
		chiefComplaint: 'Burns to right hand -- hot water',
		allergyFlag: false,
	},
];
