pub mod auth;
pub mod openapi;

pub mod patient;
pub mod clinician;
pub mod caprini_venous_thromboembolism_risk_assessment;
pub mod caprini_venous_thromboembolism_risk_assessment_grade;
pub mod caprini_venous_thromboembolism_risk_assessment_grade_rule;
pub mod caprini_venous_thromboembolism_risk_assessment_grade_flag;