//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "health_screening_questionnaire_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub parq_plus_clearance: String,
    pub audit_c_score: Option<i32>,
    pub audit_c_band: String,
    pub computed_risk_band: String,
    pub final_risk_band: String,
    pub computed_recommendation: String,
    pub final_recommendation: String,
    pub override_reason: String,
    #[sea_orm(column_type = "Text")]
    pub notes: String,
    pub signed_by_name: String,
    pub signed_at: Option<DateTimeWithTimeZone>,
    pub graded_at: DateTimeWithTimeZone,
    pub health_screening_questionnaire_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::health_screening_questionnaire_grade_flags::Entity")]
    HealthScreeningQuestionnaireGradeFlags,
    #[sea_orm(
        belongs_to = "super::health_screening_questionnaires::Entity",
        from = "Column::HealthScreeningQuestionnaireId",
        to = "super::health_screening_questionnaires::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    HealthScreeningQuestionnaires,
}

impl Related<super::health_screening_questionnaire_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HealthScreeningQuestionnaireGradeFlags.def()
    }
}

impl Related<super::health_screening_questionnaires::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HealthScreeningQuestionnaires.def()
    }
}
