import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, Eleanor',
		das28Score: 5.8,
		diseaseActivity: 'High',
		primaryDiagnosis: 'Rheumatoid Arthritis',
		currentTreatment: 'Methotrexate + Adalimumab',
		allergyFlag: false,
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Anita',
		das28Score: 3.5,
		diseaseActivity: 'Moderate',
		primaryDiagnosis: 'Rheumatoid Arthritis',
		currentTreatment: 'Methotrexate + Sulfasalazine',
		allergyFlag: true,
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		das28Score: 2.1,
		diseaseActivity: 'Remission',
		primaryDiagnosis: 'Rheumatoid Arthritis',
		currentTreatment: 'Methotrexate',
		allergyFlag: false,
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		das28Score: 4.2,
		diseaseActivity: 'Moderate',
		primaryDiagnosis: 'Psoriatic Arthritis',
		currentTreatment: 'Apremilast',
		allergyFlag: false,
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		das28Score: 6.3,
		diseaseActivity: 'High',
		primaryDiagnosis: 'Rheumatoid Arthritis',
		currentTreatment: 'Rituximab',
		allergyFlag: true,
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		das28Score: 2.8,
		diseaseActivity: 'Low',
		primaryDiagnosis: 'Ankylosing Spondylitis',
		currentTreatment: 'Etanercept',
		allergyFlag: false,
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		das28Score: 4.8,
		diseaseActivity: 'Moderate',
		primaryDiagnosis: 'Systemic Lupus',
		currentTreatment: 'Hydroxychloroquine + Prednisolone',
		allergyFlag: true,
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		das28Score: 1.9,
		diseaseActivity: 'Remission',
		primaryDiagnosis: 'Gout',
		currentTreatment: 'Allopurinol',
		allergyFlag: false,
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		das28Score: 5.4,
		diseaseActivity: 'High',
		primaryDiagnosis: 'Rheumatoid Arthritis',
		currentTreatment: 'Tocilizumab',
		allergyFlag: false,
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		das28Score: 3.0,
		diseaseActivity: 'Low',
		primaryDiagnosis: 'Psoriatic Arthritis',
		currentTreatment: 'Methotrexate',
		allergyFlag: false,
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		das28Score: 3.8,
		diseaseActivity: 'Moderate',
		primaryDiagnosis: 'Rheumatoid Arthritis',
		currentTreatment: 'Leflunomide',
		allergyFlag: true,
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		das28Score: null,
		diseaseActivity: 'Not calculated',
		primaryDiagnosis: 'Osteoarthritis',
		currentTreatment: 'NSAIDs',
		allergyFlag: false,
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		das28Score: 2.4,
		diseaseActivity: 'Remission',
		primaryDiagnosis: 'Rheumatoid Arthritis',
		currentTreatment: 'Methotrexate + Hydroxychloroquine',
		allergyFlag: false,
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		das28Score: 4.5,
		diseaseActivity: 'Moderate',
		primaryDiagnosis: 'Ankylosing Spondylitis',
		currentTreatment: 'Secukinumab',
		allergyFlag: true,
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		das28Score: 2.0,
		diseaseActivity: 'Remission',
		primaryDiagnosis: 'Rheumatoid Arthritis',
		currentTreatment: 'Sulfasalazine',
		allergyFlag: false,
	},
];
