#!/bin/sh
set -euf

cargo loco generate scaffold advance_statement_about_care \
    patient:references \
    status:string! \
    full_name:string! \
    address:text! \
    postcode:string! \
    date_of_birth:date \
    nhs_number:string! \
    phone:string! \
    email:string! \
    gp_name:string! \
    gp_practice:string! \
    reason_for_statement:text! \
    current_health_status:text! \
    current_diagnoses:text! \
    has_discussed_with_family:string! \
    has_discussed_with_clinician:string! \
    discussion_details:text! \
    personal_values:text! \
    quality_of_life_priorities:text! \
    religious_beliefs:text! \
    spiritual_needs:text! \
    cultural_considerations:text! \
    fears_and_concerns:text! \
    things_that_matter_most:text! \
    preferred_place_of_care:text! \
    preferred_place_of_death:text! \
    daily_routine_preferences:text! \
    personal_care_preferences:text! \
    food_and_drink_preferences:text! \
    sleep_preferences:text! \
    clothing_preferences:text! \
    environment_preferences:text! \
    pet_care_wishes:text! \
    pain_management_preferences:text! \
    attitude_to_hospital_admission:text! \
    attitude_to_intensive_care:text! \
    attitude_to_artificial_nutrition:text! \
    attitude_to_artificial_hydration:text! \
    medication_preferences:text! \
    complementary_therapy_preferences:text! \
    other_treatment_wishes:text! \
    preferred_language:string! \
    communication_aids:text! \
    how_to_share_information:text! \
    who_to_involve_in_decisions:text! \
    information_sharing_restrictions:text! \
    preferred_communication_style:text! \
    primary_contact_name:string! \
    primary_contact_relationship:string! \
    primary_contact_phone:string! \
    primary_contact_email:string! \
    secondary_contact_name:string! \
    secondary_contact_relationship:string! \
    secondary_contact_phone:string! \
    people_who_should_visit:text! \
    people_who_should_not_visit:text! \
    support_network_details:text! \
    financial_arrangements:text! \
    property_arrangements:text! \
    insurance_details:text! \
    will_location:text! \
    has_lasting_power_of_attorney:string! \
    lpa_details:text! \
    funeral_wishes:text! \
    burial_or_cremation:string! \
    other_practical_matters:text! \
    maker_signature_obtained:string! \
    maker_signature_date:date \
    witness_name:string! \
    witness_address:text! \
    witness_signature_obtained:string! \
    witness_signature_date:date \
    review_date:date \
    review_notes:text! \
    --htmx
