//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "chronic_obstructive_pulmonary_disease_review_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub gold_airflow_grade: String,
    pub symptom_burden: String,
    pub exacerbation_risk: String,
    pub abe_group: String,
    pub review_status: String,
    pub graded_at: DateTimeWithTimeZone,
    pub chronic_obstructive_pulmonary_disease_review_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        has_many = "super::chronic_obstructive_pulmonary_disease_review_grade_flags::Entity"
    )]
    ChronicObstructivePulmonaryDiseaseReviewGradeFlags,
    #[sea_orm(
        has_many = "super::chronic_obstructive_pulmonary_disease_review_grade_rules::Entity"
    )]
    ChronicObstructivePulmonaryDiseaseReviewGradeRules,
    #[sea_orm(
        belongs_to = "super::chronic_obstructive_pulmonary_disease_reviews::Entity",
        from = "Column::ChronicObstructivePulmonaryDiseaseReviewId",
        to = "super::chronic_obstructive_pulmonary_disease_reviews::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ChronicObstructivePulmonaryDiseaseReviews,
}

impl Related<super::chronic_obstructive_pulmonary_disease_review_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChronicObstructivePulmonaryDiseaseReviewGradeFlags.def()
    }
}

impl Related<super::chronic_obstructive_pulmonary_disease_review_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChronicObstructivePulmonaryDiseaseReviewGradeRules.def()
    }
}

impl Related<super::chronic_obstructive_pulmonary_disease_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChronicObstructivePulmonaryDiseaseReviews.def()
    }
}
