//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "chronic_obstructive_pulmonary_disease_reviews")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub clinician_name: String,
    pub clinician_role: String,
    pub reviewed_at: Option<Date>,
    pub review_type: String,
    pub patient_identifier: String,
    pub age_band: String,
    pub sex: String,
    pub diagnosis_year: Option<i32>,
    pub spirometry_confirmed: String,
    #[sea_orm(column_type = "Text")]
    pub exposure_notes: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub fev1_litres: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fev1_percent_predicted: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fvc_litres: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fev1_fvc_ratio: Option<f64>,
    pub spirometry_date: Option<Date>,
    pub mrc_grade: Option<i32>,
    pub mmrc_grade: Option<i32>,
    pub cat_score: Option<i32>,
    pub exacerbations_last_12m: Option<i32>,
    pub hospitalisations_last_12m: Option<i32>,
    pub last_exacerbation_date: Option<Date>,
    pub rescue_pack_courses: Option<i32>,
    pub smoking_status: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub pack_years: Option<f64>,
    pub cessation_support_offered: String,
    #[sea_orm(column_type = "Text")]
    pub inhaled_therapy: String,
    #[sea_orm(column_type = "Text")]
    pub device_type: String,
    pub inhaler_technique_checked: String,
    pub inhaler_technique_adequate: String,
    pub adherence: String,
    pub influenza_vaccine: String,
    pub pneumococcal_vaccine: String,
    pub covid_vaccine: String,
    pub pulmonary_rehab_status: String,
    pub oxygen_use: String,
    pub resting_spo2: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub comorbidities: String,
    pub self_management_plan: String,
    pub rescue_pack_supplied: String,
    #[sea_orm(column_type = "Text")]
    pub next_review_interval: String,
    #[sea_orm(column_type = "Text")]
    pub clinician_note: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chronic_obstructive_pulmonary_disease_review_grades::Entity")]
    ChronicObstructivePulmonaryDiseaseReviewGrades,
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::chronic_obstructive_pulmonary_disease_review_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChronicObstructivePulmonaryDiseaseReviewGrades.def()
    }
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
