#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding allergy-assessment (19 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_allergy_history \
    assessment:references \
    age_of_onset:int \
    known_allergens:text! \
    family_history_of_atopy:string! \
    family_atopy_details:text! \
    family_history_of_allergy:string! \
    family_allergy_details:text! \
    --htmx

cargo loco generate scaffold assessment_drug_allergies \
    assessment:references \
    has_drug_allergies:string! \
    cross_reactivity_concerns:text! \
    --htmx

cargo loco generate scaffold assessment_drug_allergy_item \
    drug_allergies:references \
    allergen:string! \
    reaction_type:string! \
    severity:string! \
    timing:string! \
    alternatives_tolerated:text! \
    sort_order:int! \
    --htmx

cargo loco generate scaffold assessment_food_allergies \
    assessment:references \
    has_food_allergies:string! \
    ige_type:string! \
    oral_allergy_syndrome:string! \
    dietary_restrictions:text! \
    --htmx

cargo loco generate scaffold assessment_food_allergy_item \
    food_allergies:references \
    allergen:string! \
    reaction_type:string! \
    severity:string! \
    timing:string! \
    alternatives_tolerated:text! \
    sort_order:int! \
    --htmx

cargo loco generate scaffold assessment_environmental_allergies \
    assessment:references \
    pollen_allergy:string! \
    dust_mite_allergy:string! \
    mould_allergy:string! \
    animal_dander_allergy:string! \
    latex_allergy:string! \
    insect_sting_allergy:string! \
    insect_sting_severity:string! \
    seasonal_pattern:string! \
    other_environmental_allergens:text! \
    --htmx

cargo loco generate scaffold assessment_anaphylaxis_history \
    assessment:references \
    has_anaphylaxis_history:string! \
    number_of_episodes:int \
    adrenaline_auto_injector_prescribed:string! \
    action_plan_in_place:string! \
    --htmx

cargo loco generate scaffold assessment_anaphylaxis_episode \
    anaphylaxis_history:references \
    trigger_description:text! \
    symptoms:text! \
    treatment_required:text! \
    sort_order:int! \
    --htmx

cargo loco generate scaffold assessment_testing_results \
    assessment:references \
    skin_prick_tests_done:string! \
    specific_ige_done:string! \
    component_resolved_diagnostics_done:string! \
    challenge_tests_done:string! \
    patch_tests_done:string! \
    --htmx

cargo loco generate scaffold assessment_test_result_item \
    testing_results:references \
    test_type:string! \
    allergen:string! \
    result:string! \
    sort_order:int! \
    --htmx

cargo loco generate scaffold assessment_current_management \
    assessment:references \
    antihistamines:string! \
    antihistamine_details:text! \
    nasal_steroids:string! \
    adrenaline_auto_injector:string! \
    immunotherapy:string! \
    immunotherapy_details:text! \
    biologics:string! \
    biologic_details:text! \
    allergen_avoidance_strategies:text! \
    --htmx

cargo loco generate scaffold assessment_other_medication \
    current_management:references \
    medication_name:string! \
    dose:string! \
    frequency:string! \
    sort_order:int! \
    --htmx

cargo loco generate scaffold assessment_comorbidities \
    assessment:references \
    asthma:string! \
    asthma_severity:string! \
    eczema:string! \
    eczema_severity:string! \
    rhinitis:string! \
    rhinitis_severity:string! \
    eosinophilic_oesophagitis:string! \
    mast_cell_disorders:string! \
    mast_cell_details:text! \
    mental_health_impact:string! \
    mental_health_details:text! \
    --htmx

cargo loco generate scaffold assessment_impact_action_plan \
    assessment:references \
    quality_of_life_score:int \
    school_work_impact:string! \
    school_work_impact_details:text! \
    emergency_action_plan_status:string! \
    training_provided:string! \
    training_details:text! \
    follow_up_schedule:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    severity_level:string! \
    allergy_burden_score:int! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
