CREATE TABLE assessment (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ DEFAULT NULL,
    patient_id UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'reviewed', 'urgent')),
    age_of_onset INTEGER CHECK (age_of_onset IS NULL OR (age_of_onset >= 0 AND age_of_onset <= 120)),
    known_allergens TEXT NOT NULL DEFAULT '',
    family_history_of_atopy VARCHAR(5) NOT NULL DEFAULT '' CHECK (family_history_of_atopy IN ('yes', 'no', '')),
    family_atopy_details TEXT NOT NULL DEFAULT '',
    family_history_of_allergy VARCHAR(5) NOT NULL DEFAULT '' CHECK (family_history_of_allergy IN ('yes', 'no', '')),
    family_allergy_details TEXT NOT NULL DEFAULT '',
    pollen_allergy VARCHAR(5) NOT NULL DEFAULT '' CHECK (pollen_allergy IN ('yes', 'no', '')),
    dust_mite_allergy VARCHAR(5) NOT NULL DEFAULT '' CHECK (dust_mite_allergy IN ('yes', 'no', '')),
    mould_allergy VARCHAR(5) NOT NULL DEFAULT '' CHECK (mould_allergy IN ('yes', 'no', '')),
    animal_dander_allergy VARCHAR(5) NOT NULL DEFAULT '' CHECK (animal_dander_allergy IN ('yes', 'no', '')),
    latex_allergy VARCHAR(5) NOT NULL DEFAULT '' CHECK (latex_allergy IN ('yes', 'no', '')),
    insect_sting_allergy VARCHAR(5) NOT NULL DEFAULT '' CHECK (insect_sting_allergy IN ('yes', 'no', '')),
    insect_sting_severity VARCHAR(20) NOT NULL DEFAULT '' CHECK (insect_sting_severity IN ('mild', 'moderate', 'severe', 'anaphylaxis', '')),
    seasonal_pattern VARCHAR(20) NOT NULL DEFAULT '' CHECK (seasonal_pattern IN ('perennial', 'spring', 'summer', 'autumn', 'winter', 'multiple', '')),
    other_environmental_allergens TEXT NOT NULL DEFAULT '',
    asthma VARCHAR(5) NOT NULL DEFAULT '' CHECK (asthma IN ('yes', 'no', '')),
    asthma_severity VARCHAR(10) NOT NULL DEFAULT '' CHECK (asthma_severity IN ('mild', 'moderate', 'severe', '')),
    eczema VARCHAR(5) NOT NULL DEFAULT '' CHECK (eczema IN ('yes', 'no', '')),
    eczema_severity VARCHAR(10) NOT NULL DEFAULT '' CHECK (eczema_severity IN ('mild', 'moderate', 'severe', '')),
    rhinitis VARCHAR(5) NOT NULL DEFAULT '' CHECK (rhinitis IN ('yes', 'no', '')),
    rhinitis_severity VARCHAR(10) NOT NULL DEFAULT '' CHECK (rhinitis_severity IN ('mild', 'moderate', 'severe', '')),
    eosinophilic_oesophagitis VARCHAR(5) NOT NULL DEFAULT '' CHECK (eosinophilic_oesophagitis IN ('yes', 'no', '')),
    mast_cell_disorders VARCHAR(5) NOT NULL DEFAULT '' CHECK (mast_cell_disorders IN ('yes', 'no', '')),
    mast_cell_details TEXT NOT NULL DEFAULT '',
    mental_health_impact VARCHAR(5) NOT NULL DEFAULT '' CHECK (mental_health_impact IN ('yes', 'no', '')),
    mental_health_details TEXT NOT NULL DEFAULT '',
    quality_of_life_score INTEGER CHECK (quality_of_life_score IS NULL OR (quality_of_life_score >= 1 AND quality_of_life_score <= 10)),
    school_work_impact VARCHAR(5) NOT NULL DEFAULT '' CHECK (school_work_impact IN ('yes', 'no', '')),
    school_work_impact_details TEXT NOT NULL DEFAULT '',
    emergency_action_plan_status VARCHAR(20) NOT NULL DEFAULT '' CHECK (emergency_action_plan_status IN ('in-place', 'not-in-place', 'needs-update', '')),
    training_provided VARCHAR(5) NOT NULL DEFAULT '' CHECK (training_provided IN ('yes', 'no', '')),
    training_details TEXT NOT NULL DEFAULT '',
    follow_up_schedule TEXT NOT NULL DEFAULT ''
);

CREATE TRIGGER trigger_assessment_updated_at
    BEFORE UPDATE ON assessment
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE assessment IS
    'Flat assessment table: parent assessment merged with every assessment_<section> child. Generated by bin/generate-sql-flat.py.';

COMMENT ON COLUMN assessment.patient_id IS
    'Foreign key to the patient table.';
COMMENT ON COLUMN assessment.status IS
    'Lifecycle status of this row.';
COMMENT ON COLUMN assessment.age_of_onset IS
    'Age of onset.';
COMMENT ON COLUMN assessment.known_allergens IS
    'Known allergens.';
COMMENT ON COLUMN assessment.family_history_of_atopy IS
    'Family history of atopy. One of: yes, no.';
COMMENT ON COLUMN assessment.family_atopy_details IS
    'Family atopy details.';
COMMENT ON COLUMN assessment.family_history_of_allergy IS
    'Family history of allergy. One of: yes, no.';
COMMENT ON COLUMN assessment.family_allergy_details IS
    'Family allergy details.';
COMMENT ON COLUMN assessment.pollen_allergy IS
    'Pollen allergy. One of: yes, no.';
COMMENT ON COLUMN assessment.dust_mite_allergy IS
    'Dust mite allergy. One of: yes, no.';
COMMENT ON COLUMN assessment.mould_allergy IS
    'Mould allergy. One of: yes, no.';
COMMENT ON COLUMN assessment.animal_dander_allergy IS
    'Animal dander allergy. One of: yes, no.';
COMMENT ON COLUMN assessment.latex_allergy IS
    'Latex allergy. One of: yes, no.';
COMMENT ON COLUMN assessment.insect_sting_allergy IS
    'Insect sting allergy. One of: yes, no.';
COMMENT ON COLUMN assessment.insect_sting_severity IS
    'Insect sting severity. One of: mild, moderate, severe, anaphylaxis.';
COMMENT ON COLUMN assessment.seasonal_pattern IS
    'Seasonal pattern. One of: perennial, spring, summer, autumn, winter, multiple.';
COMMENT ON COLUMN assessment.other_environmental_allergens IS
    'Other environmental allergens.';
COMMENT ON COLUMN assessment.asthma IS
    'Asthma. One of: yes, no.';
COMMENT ON COLUMN assessment.asthma_severity IS
    'Asthma severity. One of: mild, moderate, severe.';
COMMENT ON COLUMN assessment.eczema IS
    'Eczema. One of: yes, no.';
COMMENT ON COLUMN assessment.eczema_severity IS
    'Eczema severity. One of: mild, moderate, severe.';
COMMENT ON COLUMN assessment.rhinitis IS
    'Rhinitis. One of: yes, no.';
COMMENT ON COLUMN assessment.rhinitis_severity IS
    'Rhinitis severity. One of: mild, moderate, severe.';
COMMENT ON COLUMN assessment.eosinophilic_oesophagitis IS
    'Eosinophilic oesophagitis. One of: yes, no.';
COMMENT ON COLUMN assessment.mast_cell_disorders IS
    'Mast cell disorders. One of: yes, no.';
COMMENT ON COLUMN assessment.mast_cell_details IS
    'Mast cell details.';
COMMENT ON COLUMN assessment.mental_health_impact IS
    'Mental health impact. One of: yes, no.';
COMMENT ON COLUMN assessment.mental_health_details IS
    'Mental health details.';
COMMENT ON COLUMN assessment.quality_of_life_score IS
    'Quality of life score.';
COMMENT ON COLUMN assessment.school_work_impact IS
    'School work impact. One of: yes, no.';
COMMENT ON COLUMN assessment.school_work_impact_details IS
    'School work impact details.';
COMMENT ON COLUMN assessment.emergency_action_plan_status IS
    'Emergency action plan status. One of: in-place, not-in-place, needs-update.';
COMMENT ON COLUMN assessment.training_provided IS
    'Training provided. One of: yes, no.';
COMMENT ON COLUMN assessment.training_details IS
    'Training details.';
COMMENT ON COLUMN assessment.follow_up_schedule IS
    'Follow up schedule.';
COMMENT ON COLUMN assessment.id IS
    'Primary key UUID, auto-generated.';
COMMENT ON COLUMN assessment.created_at IS
    'Timestamp when this row was created.';
COMMENT ON COLUMN assessment.updated_at IS
    'Timestamp when this row was updated.';
COMMENT ON COLUMN assessment.deleted_at IS
    'Timestamp when this row was deleted.';
