//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "bowel_cancer_screening_fit_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub result_class: String,
    pub management_action: String,
    pub symptomatic_pathway: bool,
    pub status: String,
    pub graded_at: DateTimeWithTimeZone,
    pub bowel_cancer_screening_fit_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bowel_cancer_screening_fit_grade_flags::Entity")]
    BowelCancerScreeningFitGradeFlags,
    #[sea_orm(has_many = "super::bowel_cancer_screening_fit_grade_rules::Entity")]
    BowelCancerScreeningFitGradeRules,
    #[sea_orm(
        belongs_to = "super::bowel_cancer_screening_fits::Entity",
        from = "Column::BowelCancerScreeningFitId",
        to = "super::bowel_cancer_screening_fits::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BowelCancerScreeningFits,
}

impl Related<super::bowel_cancer_screening_fit_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BowelCancerScreeningFitGradeFlags.def()
    }
}

impl Related<super::bowel_cancer_screening_fit_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BowelCancerScreeningFitGradeRules.def()
    }
}

impl Related<super::bowel_cancer_screening_fits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BowelCancerScreeningFits.def()
    }
}
