#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding substance-abuse-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    preferred_name:string! \
    gender_identity:string! \
    ethnicity:string! \
    preferred_language:string! \
    interpreter_required:string! \
    gp_name:string! \
    gp_practice:string! \
    referrer_name:string! \
    referrer_role:string! \
    --htmx

cargo loco generate scaffold assessment_alcohol_use_audit \
    assessment:references \
    audit_q1_frequency:int! \
    audit_q2_typical_quantity:int! \
    audit_q3_binge_frequency:int! \
    audit_q4_impaired_control:int! \
    audit_q5_failed_expectations:int! \
    audit_q6_morning_drinking:int! \
    audit_q7_guilt:int! \
    audit_q8_blackout:int! \
    audit_q9_injury:int! \
    audit_q10_concern:int! \
    audit_total_score:int \
    audit_risk_category:string! \
    alcohol_use_notes:text! \
    --htmx

cargo loco generate scaffold assessment_drug_use_dast \
    assessment:references \
    dast_q1_non_medical_use:string! \
    dast_q2_poly_drug:string! \
    dast_q3_able_to_stop:string! \
    dast_q4_blackouts:string! \
    dast_q5_guilt:string! \
    dast_q6_complaints:string! \
    dast_q7_neglect:string! \
    dast_q8_illegal_activities:string! \
    dast_q9_withdrawal:string! \
    dast_q10_medical_problems:string! \
    dast_total_score:int \
    dast_risk_category:string! \
    drug_use_notes:text! \
    --htmx

cargo loco generate scaffold assessment_substance_use_history \
    assessment:references \
    age_first_alcohol_use:int \
    age_first_drug_use:int \
    primary_substance:string! \
    primary_substance_other:text! \
    secondary_substances:text! \
    route_of_administration:string! \
    frequency_of_use:string! \
    duration_of_use:string! \
    last_use_date:date \
    current_use_status:string! \
    iv_drug_use:string! \
    needle_sharing:string! \
    substance_history_notes:text! \
    --htmx

cargo loco generate scaffold assessment_withdrawal \
    assessment:references \
    currently_in_withdrawal:string! \
    withdrawal_substance:string! \
    tremor:string! \
    sweating:string! \
    nausea_vomiting:string! \
    anxiety:string! \
    agitation:string! \
    seizure_history:string! \
    delirium_tremens_history:string! \
    hallucinations:string! \
    last_drink_drug_hours:int \
    withdrawal_severity:string! \
    medically_supervised_detox_needed:string! \
    withdrawal_notes:text! \
    --htmx

cargo loco generate scaffold assessment_mental_health_comorbidities \
    assessment:references \
    depression:string! \
    depression_severity:string! \
    anxiety_disorder:string! \
    anxiety_disorder_type:string! \
    ptsd:string! \
    ptsd_details:text! \
    bipolar_disorder:string! \
    psychosis:string! \
    personality_disorder:string! \
    eating_disorder:string! \
    adhd:string! \
    suicidal_ideation:string! \
    suicidal_ideation_current:string! \
    self_harm_history:string! \
    previous_suicide_attempts:string! \
    psychiatric_medication:string! \
    psychiatric_medication_details:text! \
    mental_health_notes:text! \
    --htmx

cargo loco generate scaffold assessment_physical_health_impact \
    assessment:references \
    liver_disease:string! \
    liver_disease_type:string! \
    hepatitis_b:string! \
    hepatitis_c:string! \
    hiv_status:string! \
    cardiovascular_issues:string! \
    cardiovascular_details:text! \
    respiratory_issues:string! \
    respiratory_details:text! \
    gastrointestinal_issues:string! \
    gastrointestinal_details:text! \
    neurological_issues:string! \
    neurological_details:text! \
    nutritional_deficiency:string! \
    chronic_pain:string! \
    chronic_pain_details:text! \
    overdose_history:string! \
    overdose_count:int \
    last_overdose_date:date \
    physical_health_notes:text! \
    --htmx

cargo loco generate scaffold assessment_social_legal_impact \
    assessment:references \
    employment_status:string! \
    occupation:string! \
    employment_affected:string! \
    housing_status:string! \
    relationship_status:string! \
    relationship_impact:string! \
    dependents:int \
    children_safeguarding_concerns:string! \
    social_support:string! \
    criminal_record:string! \
    criminal_record_details:text! \
    current_legal_issues:string! \
    current_legal_details:text! \
    dui_dwi_history:string! \
    driving_status:string! \
    financial_difficulties:string! \
    domestic_violence:string! \
    domestic_violence_details:text! \
    social_legal_notes:text! \
    --htmx

cargo loco generate scaffold assessment_previous_treatment \
    assessment:references \
    previous_treatment:string! \
    number_of_treatment_episodes:int \
    previous_detox:string! \
    detox_setting:string! \
    previous_rehab:string! \
    rehab_type:string! \
    previous_counselling:string! \
    counselling_type:string! \
    previous_medication_assisted:string! \
    mat_medication:string! \
    self_help_groups:string! \
    self_help_group_type:string! \
    longest_period_abstinent:string! \
    relapse_triggers:text! \
    treatment_history_notes:text! \
    --htmx

cargo loco generate scaffold assessment_treatment_planning \
    assessment:references \
    treatment_goal:string! \
    readiness_to_change:string! \
    motivation_level:string! \
    preferred_treatment_setting:string! \
    interested_in_counselling:string! \
    interested_in_medication:string! \
    interested_in_self_help:string! \
    barriers_to_treatment:text! \
    support_network_available:string! \
    support_network_details:text! \
    risk_of_relapse:string! \
    safety_plan_needed:string! \
    naloxone_provided:string! \
    follow_up_plan:text! \
    treatment_planning_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    audit_score:int \
    audit_risk_category:string! \
    dast_score:int \
    dast_risk_category:string! \
    overall_risk_level:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
