//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Model.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "architecture_decision_records")]
pub struct Model {
    /// Created at.
    pub created_at: DateTimeWithTimeZone,
    /// Updated at.
    pub updated_at: DateTimeWithTimeZone,
    /// ID.
    #[sea_orm(primary_key)]
    pub id: i64,
    /// Slug.
    pub slug: String,
    /// Number.
    pub number: Option<i32>,
    /// Title.
    pub title: String,
    /// Decision date.
    pub decision_date: Option<Date>,
    /// Status.
    pub status: String,
    /// Decision group.
    pub decision_group: String,
    /// Issue.
    #[sea_orm(column_type = "Text", nullable)]
    pub issue: String,
    /// Decision.
    #[sea_orm(column_type = "Text", nullable)]
    pub decision: String,
    /// Assumptions.
    #[sea_orm(column_type = "Text", nullable)]
    pub assumptions: String,
    /// Constraints.
    #[sea_orm(column_type = "Text", nullable)]
    pub constraints: String,
    /// Argument.
    #[sea_orm(column_type = "Text", nullable)]
    pub argument: String,
    /// Implications.
    #[sea_orm(column_type = "Text", nullable)]
    pub implications: String,
    /// Related decisions.
    #[sea_orm(column_type = "Text", nullable)]
    pub related_decisions: String,
    /// Related requirements.
    #[sea_orm(column_type = "Text", nullable)]
    pub related_requirements: String,
    /// Related artifacts.
    #[sea_orm(column_type = "Text", nullable)]
    pub related_artifacts: String,
    /// Related principles.
    #[sea_orm(column_type = "Text", nullable)]
    pub related_principles: String,
    /// Signed off by.
    pub signed_off_by: String,
    /// Signed off at.
    pub signed_off_at: Option<DateTimeWithTimeZone>,
    /// Author ID.
    pub author_id: i64,
    /// Organization ID.
    pub organization_id: i64,
}

/// Relation.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Architecture decision record notes.
    #[sea_orm(has_many = "super::architecture_decision_record_notes::Entity")]
    ArchitectureDecisionRecordNotes,
    /// Architecture decision record positions.
    #[sea_orm(has_many = "super::architecture_decision_record_positions::Entity")]
    ArchitectureDecisionRecordPositions,
    #[sea_orm(
        belongs_to = "super::authors::Entity",
        from = "Column::AuthorId",
        to = "super::authors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Authors.
    Authors,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrganizationId",
        to = "super::organizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Organizations.
    Organizations,
}

impl Related<super::architecture_decision_record_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArchitectureDecisionRecordNotes.def()
    }
}

impl Related<super::architecture_decision_record_positions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArchitectureDecisionRecordPositions.def()
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Authors.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}
