#![allow(clippy::missing_errors_doc)]
#![allow(clippy::unnecessary_struct_initialization)]
#![allow(clippy::unused_async)]
use loco_rs::prelude::*;
use serde::{Deserialize, Serialize};

use crate::models::_entities::pre_anaesthesia_assessments::{ActiveModel, Entity, Model};

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Params {
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub patient_id: i64,
    pub clinician_id: i64,
    pub status: String,
    pub site_name: String,
    pub assessment_date: Option<Date>,
    pub assessment_time: Option<String>,
    pub planned_procedure: String,
    pub surgical_specialty: String,
    pub urgency: String,
    pub laterality: String,
    pub surgical_severity: String,
    pub anticipated_blood_loss_ml: Option<i32>,
    pub anticipated_duration_minutes: Option<i32>,
    pub consultant_surgeon: String,
    pub planned_date: Option<Date>,
    pub systolic_bp: Option<i32>,
    pub diastolic_bp: Option<i32>,
    pub heart_rate: Option<i32>,
    pub respiratory_rate: Option<i32>,
    pub spo2_percent: Option<f64>,
    pub temperature_celsius: Option<f64>,
    pub capillary_refill_seconds: Option<f64>,
    pub pain_score_0_10: Option<i32>,
    pub on_room_air: String,
    pub supplemental_oxygen_litres: Option<f64>,
    pub mallampati_class: String,
    pub thyromental_distance_cm: Option<f64>,
    pub mouth_opening_cm: Option<f64>,
    pub inter_incisor_gap_cm: Option<f64>,
    pub neck_rom: String,
    pub cervical_spine_stability: String,
    pub dentition: String,
    pub beard: String,
    pub upper_lip_bite_test: String,
    pub prior_difficult_intubation: String,
    pub stopbang_snoring: String,
    pub stopbang_tired: String,
    pub stopbang_observed_apnoea: String,
    pub stopbang_pressure: String,
    pub stopbang_bmi_gt35: String,
    pub stopbang_age_gt50: String,
    pub stopbang_neck_gt40: String,
    pub stopbang_male: String,
    pub airway_notes: String,
    pub heart_rhythm: String,
    pub murmur_present: String,
    pub murmur_description: String,
    pub peripheral_pulses: String,
    pub jvp_raised: String,
    pub peripheral_oedema: String,
    pub ecg_performed: String,
    pub ecg_rhythm: String,
    pub ecg_rate_bpm: Option<i32>,
    pub ecg_axis: String,
    pub ecg_ischaemic_changes: String,
    pub ecg_notes: String,
    pub echo_performed: String,
    pub echo_ef_percent: Option<i32>,
    pub echo_notes: String,
    pub history_ihd: String,
    pub history_chf: String,
    pub history_stroke_tia: String,
    pub recent_mi_within_3_months: String,
    pub pacemaker_or_icd: String,
    pub severe_valve_dysfunction: String,
    pub active_angina: String,
    pub breath_sounds: String,
    pub wheeze: String,
    pub crackles: String,
    pub crepitations: String,
    pub chest_wall_deformity: String,
    pub asthma: String,
    pub copd: String,
    pub cxr_performed: String,
    pub cxr_findings: String,
    pub pft_performed: String,
    pub pft_fev1_percent_predicted: Option<f64>,
    pub pft_fev1_fvc_ratio: Option<f64>,
    pub smoking_status: String,
    pub pack_years: Option<f64>,
    pub covid_history: String,
    pub days_since_covid: Option<i32>,
    pub covid_unresolved_symptoms: String,
    pub gcs_total: Option<i32>,
    pub gcs_eye: Option<i32>,
    pub gcs_verbal: Option<i32>,
    pub gcs_motor: Option<i32>,
    pub cognition_tool: String,
    pub cognition_score: Option<i32>,
    pub cognitive_impairment: String,
    pub capacity_concern: String,
    pub cranial_nerves_notes: String,
    pub motor_power: String,
    pub sensory_notes: String,
    pub reflexes: String,
    pub recent_stroke_tia: String,
    pub days_since_stroke_tia: Option<i32>,
    pub seizure_disorder: String,
    pub creatinine_umol_l: Option<i32>,
    pub egfr_ml_min_1_73m2: Option<i32>,
    pub urea_mmol_l: Option<f64>,
    pub potassium_mmol_l: Option<f64>,
    pub sodium_mmol_l: Option<f64>,
    pub dialysis_status: String,
    pub ckd_stage: String,
    pub bilirubin_umol_l: Option<i32>,
    pub alt_u_l: Option<i32>,
    pub ast_u_l: Option<i32>,
    pub alp_u_l: Option<i32>,
    pub albumin_g_l: Option<f64>,
    pub chronic_liver_disease: String,
    pub child_pugh_class: String,
    pub hb_g_l: Option<i32>,
    pub wcc_10_9_l: Option<f64>,
    pub platelets_10_9_l: Option<i32>,
    pub mcv_fl: Option<f64>,
    pub ferritin_ug_l: Option<i32>,
    pub transferrin_saturation_percent: Option<f64>,
    pub inr: Option<f64>,
    pub aptt_seconds: Option<f64>,
    pub fibrinogen_g_l: Option<f64>,
    pub on_anticoagulant: String,
    pub anticoagulant_type: String,
    pub anticoagulant_hold_plan: String,
    pub group_and_save: String,
    pub crossmatch_units: Option<i32>,
    pub last_transfusion_date: Option<Date>,
    pub anaemia_severity: String,
    pub diabetes_type: String,
    pub diabetes_on_insulin: String,
    pub hba1c_mmol_mol: Option<i32>,
    pub fasting_glucose_mmol_l: Option<f64>,
    pub random_glucose_mmol_l: Option<f64>,
    pub diabetes_control: String,
    pub diabetes_complications: String,
    pub thyroid_status: String,
    pub tsh_mu_l: Option<f64>,
    pub adrenal_status: String,
    pub on_long_term_steroids: String,
    pub steroid_dose_mg: Option<f64>,
    pub steroid_cover_plan: String,
    pub abdominal_exam: String,
    pub abdominal_notes: String,
    pub reflux_symptoms: String,
    pub hiatus_hernia: String,
    pub previous_gastric_surgery: String,
    pub ng_tube: String,
    pub stoma: String,
    pub fasting_confirmed: String,
    pub last_solid_food_at: Option<DateTimeWithTimeZone>,
    pub last_clear_fluid_at: Option<DateTimeWithTimeZone>,
    pub rapid_sequence_induction_needed: String,
    pub spine_exam: String,
    pub spine_notes: String,
    pub neuraxial_suitable: String,
    pub joint_rom_hip: String,
    pub joint_rom_shoulder: String,
    pub joint_rom_neck: String,
    pub skin_iv_access: String,
    pub skin_block_site: String,
    pub pressure_ulcer_risk: String,
    pub name: String,
    pub dose: String,
    pub route: String,
    pub frequency: String,
    pub indication: String,
    pub class: String,
    pub perioperative_action: String,
    pub perioperative_notes: String,
    pub last_dose_at: Option<DateTimeWithTimeZone>,
    pub allergen: String,
    pub category: String,
    pub reaction_type: String,
    pub reaction_severity: String,
    pub reaction_notes: String,
    pub verified: String,
    pub mets_estimate: Option<f64>,
    pub dasi_score: Option<f64>,
    pub ecog_performance_status: Option<i32>,
    pub clinical_frailty_scale: Option<i32>,
    pub six_minute_walk_metres: Option<i32>,
    pub sts_one_minute_reps: Option<i32>,
    pub tug_seconds: Option<f64>,
    pub cpet_performed: String,
    pub cpet_vo2_peak_ml_kg_min: Option<f64>,
    pub cpet_anaerobic_threshold_ml_kg_min: Option<f64>,
    pub cpet_notes: String,
    pub malnutrition_risk: String,
    pub unintentional_weight_loss_kg: Option<f64>,
    pub technique: String,
    pub airway_plan: String,
    pub rsi_planned: String,
    pub monitoring_level: String,
    pub analgesia_plan: String,
    pub regional_block_planned: String,
    pub dvt_prophylaxis: String,
    pub antibiotic_prophylaxis: String,
    pub post_op_disposition: String,
    pub anticipated_length_of_stay_days: Option<i32>,
    pub special_equipment: String,
    pub blood_products_required: String,
    pub proforma_header_department: String,
    pub proforma_header_registration_date: String,
    pub proforma_header_pre_op_diagnosis: String,
    pub prev_anaes_anaesthetic_difficulty: bool,
    pub prev_anaes_abnormal_reaction: bool,
    pub prev_anaes_ponv: bool,
    pub prev_anaes_malignant_hyperpyrexia: bool,
    pub prev_anaes_difficult_intubation: bool,
    pub prev_anaes_difficult_spinal_or_epidural: bool,
    pub addiction_alcohol: bool,
    pub addiction_smoking: bool,
    pub addiction_fast_score3_or_more: bool,
    pub addiction_betel: bool,
    pub addiction_drugs: bool,
    pub addiction_other: bool,
    pub addiction_other_details: String,
    pub pmh_proforma_hypertension: bool,
    pub pmh_proforma_mi: bool,
    pub pmh_proforma_mi_within_past6_months: bool,
    pub pmh_proforma_angina_or_chest_pain: bool,
    pub pmh_proforma_angina_triggers: String,
    pub pmh_proforma_heart_failure: bool,
    pub pmh_proforma_dyspnoea: bool,
    pub pmh_proforma_dyspnoea_subtypes: String,
    pub pmh_proforma_palpitation: bool,
    pub pmh_proforma_arrhythmia: bool,
    pub pmh_proforma_syncope_or_fainting: bool,
    pub pmh_proforma_heart_murmur: bool,
    pub pmh_proforma_rheumatic_fever: bool,
    pub pmh_proforma_pacemaker: bool,
    pub pmh_proforma_pacemaker_last_check_within6_months: bool,
    pub pmh_proforma_implanted_icd_crtd: bool,
    pub pmh_proforma_angioplasty: bool,
    pub pmh_proforma_stenting: bool,
    pub pmh_proforma_stenting_within_past6_months: bool,
    pub pmh_proforma_stent_type: String,
    pub pmh_proforma_valve_disease: bool,
    pub pmh_proforma_cardiac_surgery: bool,
    pub pmh_proforma_cardiac_surgery_within_past_year: bool,
    pub pmh_proforma_peripheral_vascular_disease: bool,
    pub pmh_proforma_ischemic_heart_disease: bool,
    pub pmh_proforma_asthma: bool,
    pub pmh_proforma_copd: bool,
    pub pmh_proforma_tb: bool,
    pub pmh_proforma_bronchiectasis: bool,
    pub pmh_proforma_previous_hospital_admission: bool,
    pub pmh_proforma_icu_admission: bool,
    pub pmh_proforma_on_home_oxygen_or_nebulizers: bool,
    pub pmh_proforma_uses_inhaler_daily_or_more: bool,
    pub pmh_proforma_flu_cough_sputum: bool,
    pub pmh_proforma_haemoptysis: bool,
    pub pmh_proforma_sleep_apnoea: bool,
    pub pmh_proforma_sleep_apnoea_using_cpap: bool,
    pub pmh_proforma_stop_bang_risk: String,
    pub pmh_proforma_other_respiratory_disease: bool,
    pub pmh_proforma_diabetes_mellitus: bool,
    pub pmh_proforma_diabetes_diet_controlled: bool,
    pub pmh_proforma_diabetes_drug_controlled: bool,
    pub pmh_proforma_diabetes_insulin_controlled: bool,
    pub pmh_proforma_diabetes_hba1c_over69: bool,
    pub pmh_proforma_hypothyroid: bool,
    pub pmh_proforma_hyperthyroid: bool,
    pub pmh_proforma_stroke_or_tia: bool,
    pub pmh_proforma_stroke_within3_months: bool,
    pub pmh_proforma_stroke_residual_disability: String,
    pub pmh_proforma_epilepsy_or_seizures: bool,
    pub pmh_proforma_epilepsy_control: String,
    pub pmh_proforma_ms: bool,
    pub pmh_proforma_muscular_dystrophy: bool,
    pub pmh_proforma_other_neurological_disease: bool,
    pub pmh_proforma_other_neurological_disease_details: String,
    pub pmh_proforma_dementia: bool,
    pub pmh_proforma_creutzfeldt_jakob_disease: bool,
    pub pmh_proforma_growth_hormone_or_gonadotrophin: bool,
    pub pmh_proforma_brain_or_spinal_cord_surgery: bool,
    pub pmh_proforma_four_at_score: Option<i32>,
    pub pmh_proforma_complex_needs: bool,
    pub pmh_proforma_renal_impairment: bool,
    pub pmh_proforma_ckd_stage3: bool,
    pub pmh_proforma_ckd_stage4_or_hemodialysis: bool,
    pub pmh_proforma_liver_disease: bool,
    pub pmh_proforma_clotting_disorders_haemophilia: bool,
    pub pmh_proforma_easy_bruising_prolonged_bleeding: bool,
    pub pmh_proforma_dvt_or_pe: bool,
    pub pmh_proforma_dvt_or_pe_within_past3_months: bool,
    pub pmh_proforma_gord: bool,
    pub pmh_proforma_any_other_disease: bool,
    pub pmh_proforma_chronic_pain: bool,
    pub pmh_proforma_duke_activity_status_index: Option<i32>,
    pub pmh_proforma_mets_score: Option<f64>,
    pub pmh_proforma_ongoing_medications: String,
    pub pmh_proforma_cortisone_prednisone_steroid: bool,
    pub pmh_proforma_blood_transfusion_history: bool,
    pub pmh_proforma_chemotherapy_drugs: bool,
    pub pmh_proforma_radiotherapy: bool,
    pub airway_exam_proforma_mouth_opening: bool,
    pub airway_exam_proforma_loose_teeth: bool,
    pub airway_exam_proforma_denture_missing: bool,
    pub airway_exam_proforma_mp_grade: String,
    pub airway_exam_proforma_micrognathia: bool,
    pub airway_exam_proforma_tm_distance_over65: bool,
    pub airway_exam_proforma_mo_distance: bool,
    pub airway_exam_proforma_tm_joint: bool,
    pub airway_exam_proforma_short_neck_rom: bool,
    pub airway_exam_proforma_difficult_airway: bool,
    pub airway_exam_proforma_obesity_scoring: bool,
    pub airway_exam_proforma_spine_back: bool,
    pub airway_exam_proforma_scoliosis: bool,
    pub airway_exam_proforma_vitals_examination: bool,
    pub vitals_proforma_height_cm: Option<f64>,
    pub vitals_proforma_weight_kg: Option<f64>,
    pub vitals_proforma_hr: Option<i32>,
    pub vitals_proforma_bp: String,
    pub vitals_proforma_resp_rate: Option<i32>,
    pub vitals_proforma_spo2: Option<f64>,
    pub vitals_proforma_temp: Option<f64>,
    pub vitals_proforma_bmi: Option<f64>,
    pub gen_exam_proforma_pallor: bool,
    pub gen_exam_proforma_icterus: bool,
    pub gen_exam_proforma_cyanosis: bool,
    pub gen_exam_proforma_clubbing: bool,
    pub gen_exam_proforma_koilonychia: bool,
    pub gen_exam_proforma_lymphadenopathy: bool,
    pub gen_exam_proforma_edema: bool,
    pub gen_exam_proforma_jvp: bool,
    pub invest_proforma_blood_group_haemoglobin: String,
    pub invest_proforma_differential_n: String,
    pub invest_proforma_differential_l: String,
    pub invest_proforma_differential_e: String,
    pub invest_proforma_differential_m: String,
    pub invest_proforma_differential_b: String,
    pub invest_proforma_absolute: String,
    pub invest_proforma_nc: String,
    pub invest_proforma_tlc: String,
    pub invest_proforma_tpc: String,
    pub invest_proforma_esr: String,
    pub invest_proforma_crp: String,
    pub invest_proforma_pcv: String,
    pub invest_proforma_latex_rast: String,
    pub invest_proforma_fbs: String,
    pub invest_proforma_ppbs: String,
    pub invest_proforma_hba1c: String,
    pub invest_proforma_na: String,
    pub invest_proforma_k: String,
    pub invest_proforma_urea: String,
    pub invest_proforma_creatinine: String,
    pub invest_proforma_bilirubin_total: String,
    pub invest_proforma_bilirubin_direct: String,
    pub invest_proforma_alk_phosphatase: String,
    pub invest_proforma_sgpt_alt: String,
    pub invest_proforma_sgot_ast: String,
    pub invest_proforma_bt: String,
    pub invest_proforma_ct: String,
    pub invest_proforma_pt: String,
    pub invest_proforma_aptt: String,
    pub invest_proforma_inr: String,
    pub invest_proforma_ft3: String,
    pub invest_proforma_ft4: String,
    pub invest_proforma_tsh: String,
    pub invest_proforma_ecg: String,
    pub invest_proforma_chest_xray: String,
    pub invest_proforma_pft: String,
    pub invest_proforma_abg: String,
    pub invest_proforma_two_d_echo: String,
    pub invest_proforma_lvef_percent: Option<f64>,
    pub invest_proforma_tmt: String,
    pub invest_proforma_ct_scan: String,
    pub invest_proforma_mri: String,
    pub risk_factors_cardiac: bool,
    pub risk_factors_respiratory: bool,
    pub risk_factors_diabetes: bool,
    pub risk_factors_insulin: bool,
    pub risk_factors_bmi_over40: bool,
    pub risk_factors_anticoagulants: bool,
    pub risk_factors_allergies: bool,
    pub risk_factors_antiplatelets: bool,
    pub risk_factors_egfr_under30: bool,
    pub risk_factors_egfr30_to60: bool,
    pub risk_factors_age_over70: bool,
    pub risk_factors_pvd: bool,
    pub risk_factors_liver_disease: bool,
    pub risk_factors_vte_risk: bool,
    pub risk_factors_complex_needs: bool,
    pub risk_factors_anaemia: bool,
    pub risk_factors_neuromuscular_disorders: bool,
    pub risk_factors_others: bool,
    pub risk_factors_others_details: String,
    pub anaes_plan_proforma_anaesthetic_concerns: String,
    pub anaes_plan_proforma_plan_tiva: bool,
    pub anaes_plan_proforma_plan_ra: bool,
    pub anaes_plan_proforma_plan_other: bool,
    pub anaes_plan_proforma_plan_other_details: String,
    pub anaes_plan_proforma_list_for_ot_defer_not_fit: String,
    pub anaes_plan_proforma_nil_orally_after: String,
    pub anaes_plan_proforma_informed_written_consent: bool,
    pub anaes_plan_proforma_risks_benefits_alternatives_discussed: bool,
    pub anaes_plan_proforma_arrange_units_of_blood: String,
    pub anaes_plan_proforma_arrange_post_op_icu: bool,
    pub anaes_plan_proforma_backup: bool,
    pub anaes_plan_proforma_do_investigations: String,
    pub anaes_plan_proforma_do_special_orders: String,
    pub anaes_plan_proforma_reviewed_high_risk_anaesthesia: bool,
    pub anaes_plan_proforma_reviewed_consent: bool,
    pub anaes_plan_proforma_consultant_anaesthesiologist_name: String,
    pub anaes_plan_proforma_consultant_anaesthesiologist_signature: String,
    }

impl Params {
    fn update(&self, item: &mut ActiveModel) {
      item.deleted_at = Set(self.deleted_at);
      item.patient_id = Set(self.patient_id);
      item.clinician_id = Set(self.clinician_id);
      item.status = Set(self.status.clone());
      item.site_name = Set(self.site_name.clone());
      item.assessment_date = Set(self.assessment_date);
      item.assessment_time = Set(self.assessment_time.clone());
      item.planned_procedure = Set(self.planned_procedure.clone());
      item.surgical_specialty = Set(self.surgical_specialty.clone());
      item.urgency = Set(self.urgency.clone());
      item.laterality = Set(self.laterality.clone());
      item.surgical_severity = Set(self.surgical_severity.clone());
      item.anticipated_blood_loss_ml = Set(self.anticipated_blood_loss_ml);
      item.anticipated_duration_minutes = Set(self.anticipated_duration_minutes);
      item.consultant_surgeon = Set(self.consultant_surgeon.clone());
      item.planned_date = Set(self.planned_date);
      item.systolic_bp = Set(self.systolic_bp);
      item.diastolic_bp = Set(self.diastolic_bp);
      item.heart_rate = Set(self.heart_rate);
      item.respiratory_rate = Set(self.respiratory_rate);
      item.spo2_percent = Set(self.spo2_percent);
      item.temperature_celsius = Set(self.temperature_celsius);
      item.capillary_refill_seconds = Set(self.capillary_refill_seconds);
      item.pain_score_0_10 = Set(self.pain_score_0_10);
      item.on_room_air = Set(self.on_room_air.clone());
      item.supplemental_oxygen_litres = Set(self.supplemental_oxygen_litres);
      item.mallampati_class = Set(self.mallampati_class.clone());
      item.thyromental_distance_cm = Set(self.thyromental_distance_cm);
      item.mouth_opening_cm = Set(self.mouth_opening_cm);
      item.inter_incisor_gap_cm = Set(self.inter_incisor_gap_cm);
      item.neck_rom = Set(self.neck_rom.clone());
      item.cervical_spine_stability = Set(self.cervical_spine_stability.clone());
      item.dentition = Set(self.dentition.clone());
      item.beard = Set(self.beard.clone());
      item.upper_lip_bite_test = Set(self.upper_lip_bite_test.clone());
      item.prior_difficult_intubation = Set(self.prior_difficult_intubation.clone());
      item.stopbang_snoring = Set(self.stopbang_snoring.clone());
      item.stopbang_tired = Set(self.stopbang_tired.clone());
      item.stopbang_observed_apnoea = Set(self.stopbang_observed_apnoea.clone());
      item.stopbang_pressure = Set(self.stopbang_pressure.clone());
      item.stopbang_bmi_gt35 = Set(self.stopbang_bmi_gt35.clone());
      item.stopbang_age_gt50 = Set(self.stopbang_age_gt50.clone());
      item.stopbang_neck_gt40 = Set(self.stopbang_neck_gt40.clone());
      item.stopbang_male = Set(self.stopbang_male.clone());
      item.airway_notes = Set(self.airway_notes.clone());
      item.heart_rhythm = Set(self.heart_rhythm.clone());
      item.murmur_present = Set(self.murmur_present.clone());
      item.murmur_description = Set(self.murmur_description.clone());
      item.peripheral_pulses = Set(self.peripheral_pulses.clone());
      item.jvp_raised = Set(self.jvp_raised.clone());
      item.peripheral_oedema = Set(self.peripheral_oedema.clone());
      item.ecg_performed = Set(self.ecg_performed.clone());
      item.ecg_rhythm = Set(self.ecg_rhythm.clone());
      item.ecg_rate_bpm = Set(self.ecg_rate_bpm);
      item.ecg_axis = Set(self.ecg_axis.clone());
      item.ecg_ischaemic_changes = Set(self.ecg_ischaemic_changes.clone());
      item.ecg_notes = Set(self.ecg_notes.clone());
      item.echo_performed = Set(self.echo_performed.clone());
      item.echo_ef_percent = Set(self.echo_ef_percent);
      item.echo_notes = Set(self.echo_notes.clone());
      item.history_ihd = Set(self.history_ihd.clone());
      item.history_chf = Set(self.history_chf.clone());
      item.history_stroke_tia = Set(self.history_stroke_tia.clone());
      item.recent_mi_within_3_months = Set(self.recent_mi_within_3_months.clone());
      item.pacemaker_or_icd = Set(self.pacemaker_or_icd.clone());
      item.severe_valve_dysfunction = Set(self.severe_valve_dysfunction.clone());
      item.active_angina = Set(self.active_angina.clone());
      item.breath_sounds = Set(self.breath_sounds.clone());
      item.wheeze = Set(self.wheeze.clone());
      item.crackles = Set(self.crackles.clone());
      item.crepitations = Set(self.crepitations.clone());
      item.chest_wall_deformity = Set(self.chest_wall_deformity.clone());
      item.asthma = Set(self.asthma.clone());
      item.copd = Set(self.copd.clone());
      item.cxr_performed = Set(self.cxr_performed.clone());
      item.cxr_findings = Set(self.cxr_findings.clone());
      item.pft_performed = Set(self.pft_performed.clone());
      item.pft_fev1_percent_predicted = Set(self.pft_fev1_percent_predicted);
      item.pft_fev1_fvc_ratio = Set(self.pft_fev1_fvc_ratio);
      item.smoking_status = Set(self.smoking_status.clone());
      item.pack_years = Set(self.pack_years);
      item.covid_history = Set(self.covid_history.clone());
      item.days_since_covid = Set(self.days_since_covid);
      item.covid_unresolved_symptoms = Set(self.covid_unresolved_symptoms.clone());
      item.gcs_total = Set(self.gcs_total);
      item.gcs_eye = Set(self.gcs_eye);
      item.gcs_verbal = Set(self.gcs_verbal);
      item.gcs_motor = Set(self.gcs_motor);
      item.cognition_tool = Set(self.cognition_tool.clone());
      item.cognition_score = Set(self.cognition_score);
      item.cognitive_impairment = Set(self.cognitive_impairment.clone());
      item.capacity_concern = Set(self.capacity_concern.clone());
      item.cranial_nerves_notes = Set(self.cranial_nerves_notes.clone());
      item.motor_power = Set(self.motor_power.clone());
      item.sensory_notes = Set(self.sensory_notes.clone());
      item.reflexes = Set(self.reflexes.clone());
      item.recent_stroke_tia = Set(self.recent_stroke_tia.clone());
      item.days_since_stroke_tia = Set(self.days_since_stroke_tia);
      item.seizure_disorder = Set(self.seizure_disorder.clone());
      item.creatinine_umol_l = Set(self.creatinine_umol_l);
      item.egfr_ml_min_1_73m2 = Set(self.egfr_ml_min_1_73m2);
      item.urea_mmol_l = Set(self.urea_mmol_l);
      item.potassium_mmol_l = Set(self.potassium_mmol_l);
      item.sodium_mmol_l = Set(self.sodium_mmol_l);
      item.dialysis_status = Set(self.dialysis_status.clone());
      item.ckd_stage = Set(self.ckd_stage.clone());
      item.bilirubin_umol_l = Set(self.bilirubin_umol_l);
      item.alt_u_l = Set(self.alt_u_l);
      item.ast_u_l = Set(self.ast_u_l);
      item.alp_u_l = Set(self.alp_u_l);
      item.albumin_g_l = Set(self.albumin_g_l);
      item.chronic_liver_disease = Set(self.chronic_liver_disease.clone());
      item.child_pugh_class = Set(self.child_pugh_class.clone());
      item.hb_g_l = Set(self.hb_g_l);
      item.wcc_10_9_l = Set(self.wcc_10_9_l);
      item.platelets_10_9_l = Set(self.platelets_10_9_l);
      item.mcv_fl = Set(self.mcv_fl);
      item.ferritin_ug_l = Set(self.ferritin_ug_l);
      item.transferrin_saturation_percent = Set(self.transferrin_saturation_percent);
      item.inr = Set(self.inr);
      item.aptt_seconds = Set(self.aptt_seconds);
      item.fibrinogen_g_l = Set(self.fibrinogen_g_l);
      item.on_anticoagulant = Set(self.on_anticoagulant.clone());
      item.anticoagulant_type = Set(self.anticoagulant_type.clone());
      item.anticoagulant_hold_plan = Set(self.anticoagulant_hold_plan.clone());
      item.group_and_save = Set(self.group_and_save.clone());
      item.crossmatch_units = Set(self.crossmatch_units);
      item.last_transfusion_date = Set(self.last_transfusion_date);
      item.anaemia_severity = Set(self.anaemia_severity.clone());
      item.diabetes_type = Set(self.diabetes_type.clone());
      item.diabetes_on_insulin = Set(self.diabetes_on_insulin.clone());
      item.hba1c_mmol_mol = Set(self.hba1c_mmol_mol);
      item.fasting_glucose_mmol_l = Set(self.fasting_glucose_mmol_l);
      item.random_glucose_mmol_l = Set(self.random_glucose_mmol_l);
      item.diabetes_control = Set(self.diabetes_control.clone());
      item.diabetes_complications = Set(self.diabetes_complications.clone());
      item.thyroid_status = Set(self.thyroid_status.clone());
      item.tsh_mu_l = Set(self.tsh_mu_l);
      item.adrenal_status = Set(self.adrenal_status.clone());
      item.on_long_term_steroids = Set(self.on_long_term_steroids.clone());
      item.steroid_dose_mg = Set(self.steroid_dose_mg);
      item.steroid_cover_plan = Set(self.steroid_cover_plan.clone());
      item.abdominal_exam = Set(self.abdominal_exam.clone());
      item.abdominal_notes = Set(self.abdominal_notes.clone());
      item.reflux_symptoms = Set(self.reflux_symptoms.clone());
      item.hiatus_hernia = Set(self.hiatus_hernia.clone());
      item.previous_gastric_surgery = Set(self.previous_gastric_surgery.clone());
      item.ng_tube = Set(self.ng_tube.clone());
      item.stoma = Set(self.stoma.clone());
      item.fasting_confirmed = Set(self.fasting_confirmed.clone());
      item.last_solid_food_at = Set(self.last_solid_food_at);
      item.last_clear_fluid_at = Set(self.last_clear_fluid_at);
      item.rapid_sequence_induction_needed = Set(self.rapid_sequence_induction_needed.clone());
      item.spine_exam = Set(self.spine_exam.clone());
      item.spine_notes = Set(self.spine_notes.clone());
      item.neuraxial_suitable = Set(self.neuraxial_suitable.clone());
      item.joint_rom_hip = Set(self.joint_rom_hip.clone());
      item.joint_rom_shoulder = Set(self.joint_rom_shoulder.clone());
      item.joint_rom_neck = Set(self.joint_rom_neck.clone());
      item.skin_iv_access = Set(self.skin_iv_access.clone());
      item.skin_block_site = Set(self.skin_block_site.clone());
      item.pressure_ulcer_risk = Set(self.pressure_ulcer_risk.clone());
      item.name = Set(self.name.clone());
      item.dose = Set(self.dose.clone());
      item.route = Set(self.route.clone());
      item.frequency = Set(self.frequency.clone());
      item.indication = Set(self.indication.clone());
      item.class = Set(self.class.clone());
      item.perioperative_action = Set(self.perioperative_action.clone());
      item.perioperative_notes = Set(self.perioperative_notes.clone());
      item.last_dose_at = Set(self.last_dose_at);
      item.allergen = Set(self.allergen.clone());
      item.category = Set(self.category.clone());
      item.reaction_type = Set(self.reaction_type.clone());
      item.reaction_severity = Set(self.reaction_severity.clone());
      item.reaction_notes = Set(self.reaction_notes.clone());
      item.verified = Set(self.verified.clone());
      item.mets_estimate = Set(self.mets_estimate);
      item.dasi_score = Set(self.dasi_score);
      item.ecog_performance_status = Set(self.ecog_performance_status);
      item.clinical_frailty_scale = Set(self.clinical_frailty_scale);
      item.six_minute_walk_metres = Set(self.six_minute_walk_metres);
      item.sts_one_minute_reps = Set(self.sts_one_minute_reps);
      item.tug_seconds = Set(self.tug_seconds);
      item.cpet_performed = Set(self.cpet_performed.clone());
      item.cpet_vo2_peak_ml_kg_min = Set(self.cpet_vo2_peak_ml_kg_min);
      item.cpet_anaerobic_threshold_ml_kg_min = Set(self.cpet_anaerobic_threshold_ml_kg_min);
      item.cpet_notes = Set(self.cpet_notes.clone());
      item.malnutrition_risk = Set(self.malnutrition_risk.clone());
      item.unintentional_weight_loss_kg = Set(self.unintentional_weight_loss_kg);
      item.technique = Set(self.technique.clone());
      item.airway_plan = Set(self.airway_plan.clone());
      item.rsi_planned = Set(self.rsi_planned.clone());
      item.monitoring_level = Set(self.monitoring_level.clone());
      item.analgesia_plan = Set(self.analgesia_plan.clone());
      item.regional_block_planned = Set(self.regional_block_planned.clone());
      item.dvt_prophylaxis = Set(self.dvt_prophylaxis.clone());
      item.antibiotic_prophylaxis = Set(self.antibiotic_prophylaxis.clone());
      item.post_op_disposition = Set(self.post_op_disposition.clone());
      item.anticipated_length_of_stay_days = Set(self.anticipated_length_of_stay_days);
      item.special_equipment = Set(self.special_equipment.clone());
      item.blood_products_required = Set(self.blood_products_required.clone());
      item.proforma_header_department = Set(self.proforma_header_department.clone());
      item.proforma_header_registration_date = Set(self.proforma_header_registration_date.clone());
      item.proforma_header_pre_op_diagnosis = Set(self.proforma_header_pre_op_diagnosis.clone());
      item.prev_anaes_anaesthetic_difficulty = Set(self.prev_anaes_anaesthetic_difficulty);
      item.prev_anaes_abnormal_reaction = Set(self.prev_anaes_abnormal_reaction);
      item.prev_anaes_ponv = Set(self.prev_anaes_ponv);
      item.prev_anaes_malignant_hyperpyrexia = Set(self.prev_anaes_malignant_hyperpyrexia);
      item.prev_anaes_difficult_intubation = Set(self.prev_anaes_difficult_intubation);
      item.prev_anaes_difficult_spinal_or_epidural = Set(self.prev_anaes_difficult_spinal_or_epidural);
      item.addiction_alcohol = Set(self.addiction_alcohol);
      item.addiction_smoking = Set(self.addiction_smoking);
      item.addiction_fast_score3_or_more = Set(self.addiction_fast_score3_or_more);
      item.addiction_betel = Set(self.addiction_betel);
      item.addiction_drugs = Set(self.addiction_drugs);
      item.addiction_other = Set(self.addiction_other);
      item.addiction_other_details = Set(self.addiction_other_details.clone());
      item.pmh_proforma_hypertension = Set(self.pmh_proforma_hypertension);
      item.pmh_proforma_mi = Set(self.pmh_proforma_mi);
      item.pmh_proforma_mi_within_past6_months = Set(self.pmh_proforma_mi_within_past6_months);
      item.pmh_proforma_angina_or_chest_pain = Set(self.pmh_proforma_angina_or_chest_pain);
      item.pmh_proforma_angina_triggers = Set(self.pmh_proforma_angina_triggers.clone());
      item.pmh_proforma_heart_failure = Set(self.pmh_proforma_heart_failure);
      item.pmh_proforma_dyspnoea = Set(self.pmh_proforma_dyspnoea);
      item.pmh_proforma_dyspnoea_subtypes = Set(self.pmh_proforma_dyspnoea_subtypes.clone());
      item.pmh_proforma_palpitation = Set(self.pmh_proforma_palpitation);
      item.pmh_proforma_arrhythmia = Set(self.pmh_proforma_arrhythmia);
      item.pmh_proforma_syncope_or_fainting = Set(self.pmh_proforma_syncope_or_fainting);
      item.pmh_proforma_heart_murmur = Set(self.pmh_proforma_heart_murmur);
      item.pmh_proforma_rheumatic_fever = Set(self.pmh_proforma_rheumatic_fever);
      item.pmh_proforma_pacemaker = Set(self.pmh_proforma_pacemaker);
      item.pmh_proforma_pacemaker_last_check_within6_months = Set(self.pmh_proforma_pacemaker_last_check_within6_months);
      item.pmh_proforma_implanted_icd_crtd = Set(self.pmh_proforma_implanted_icd_crtd);
      item.pmh_proforma_angioplasty = Set(self.pmh_proforma_angioplasty);
      item.pmh_proforma_stenting = Set(self.pmh_proforma_stenting);
      item.pmh_proforma_stenting_within_past6_months = Set(self.pmh_proforma_stenting_within_past6_months);
      item.pmh_proforma_stent_type = Set(self.pmh_proforma_stent_type.clone());
      item.pmh_proforma_valve_disease = Set(self.pmh_proforma_valve_disease);
      item.pmh_proforma_cardiac_surgery = Set(self.pmh_proforma_cardiac_surgery);
      item.pmh_proforma_cardiac_surgery_within_past_year = Set(self.pmh_proforma_cardiac_surgery_within_past_year);
      item.pmh_proforma_peripheral_vascular_disease = Set(self.pmh_proforma_peripheral_vascular_disease);
      item.pmh_proforma_ischemic_heart_disease = Set(self.pmh_proforma_ischemic_heart_disease);
      item.pmh_proforma_asthma = Set(self.pmh_proforma_asthma);
      item.pmh_proforma_copd = Set(self.pmh_proforma_copd);
      item.pmh_proforma_tb = Set(self.pmh_proforma_tb);
      item.pmh_proforma_bronchiectasis = Set(self.pmh_proforma_bronchiectasis);
      item.pmh_proforma_previous_hospital_admission = Set(self.pmh_proforma_previous_hospital_admission);
      item.pmh_proforma_icu_admission = Set(self.pmh_proforma_icu_admission);
      item.pmh_proforma_on_home_oxygen_or_nebulizers = Set(self.pmh_proforma_on_home_oxygen_or_nebulizers);
      item.pmh_proforma_uses_inhaler_daily_or_more = Set(self.pmh_proforma_uses_inhaler_daily_or_more);
      item.pmh_proforma_flu_cough_sputum = Set(self.pmh_proforma_flu_cough_sputum);
      item.pmh_proforma_haemoptysis = Set(self.pmh_proforma_haemoptysis);
      item.pmh_proforma_sleep_apnoea = Set(self.pmh_proforma_sleep_apnoea);
      item.pmh_proforma_sleep_apnoea_using_cpap = Set(self.pmh_proforma_sleep_apnoea_using_cpap);
      item.pmh_proforma_stop_bang_risk = Set(self.pmh_proforma_stop_bang_risk.clone());
      item.pmh_proforma_other_respiratory_disease = Set(self.pmh_proforma_other_respiratory_disease);
      item.pmh_proforma_diabetes_mellitus = Set(self.pmh_proforma_diabetes_mellitus);
      item.pmh_proforma_diabetes_diet_controlled = Set(self.pmh_proforma_diabetes_diet_controlled);
      item.pmh_proforma_diabetes_drug_controlled = Set(self.pmh_proforma_diabetes_drug_controlled);
      item.pmh_proforma_diabetes_insulin_controlled = Set(self.pmh_proforma_diabetes_insulin_controlled);
      item.pmh_proforma_diabetes_hba1c_over69 = Set(self.pmh_proforma_diabetes_hba1c_over69);
      item.pmh_proforma_hypothyroid = Set(self.pmh_proforma_hypothyroid);
      item.pmh_proforma_hyperthyroid = Set(self.pmh_proforma_hyperthyroid);
      item.pmh_proforma_stroke_or_tia = Set(self.pmh_proforma_stroke_or_tia);
      item.pmh_proforma_stroke_within3_months = Set(self.pmh_proforma_stroke_within3_months);
      item.pmh_proforma_stroke_residual_disability = Set(self.pmh_proforma_stroke_residual_disability.clone());
      item.pmh_proforma_epilepsy_or_seizures = Set(self.pmh_proforma_epilepsy_or_seizures);
      item.pmh_proforma_epilepsy_control = Set(self.pmh_proforma_epilepsy_control.clone());
      item.pmh_proforma_ms = Set(self.pmh_proforma_ms);
      item.pmh_proforma_muscular_dystrophy = Set(self.pmh_proforma_muscular_dystrophy);
      item.pmh_proforma_other_neurological_disease = Set(self.pmh_proforma_other_neurological_disease);
      item.pmh_proforma_other_neurological_disease_details = Set(self.pmh_proforma_other_neurological_disease_details.clone());
      item.pmh_proforma_dementia = Set(self.pmh_proforma_dementia);
      item.pmh_proforma_creutzfeldt_jakob_disease = Set(self.pmh_proforma_creutzfeldt_jakob_disease);
      item.pmh_proforma_growth_hormone_or_gonadotrophin = Set(self.pmh_proforma_growth_hormone_or_gonadotrophin);
      item.pmh_proforma_brain_or_spinal_cord_surgery = Set(self.pmh_proforma_brain_or_spinal_cord_surgery);
      item.pmh_proforma_four_at_score = Set(self.pmh_proforma_four_at_score);
      item.pmh_proforma_complex_needs = Set(self.pmh_proforma_complex_needs);
      item.pmh_proforma_renal_impairment = Set(self.pmh_proforma_renal_impairment);
      item.pmh_proforma_ckd_stage3 = Set(self.pmh_proforma_ckd_stage3);
      item.pmh_proforma_ckd_stage4_or_hemodialysis = Set(self.pmh_proforma_ckd_stage4_or_hemodialysis);
      item.pmh_proforma_liver_disease = Set(self.pmh_proforma_liver_disease);
      item.pmh_proforma_clotting_disorders_haemophilia = Set(self.pmh_proforma_clotting_disorders_haemophilia);
      item.pmh_proforma_easy_bruising_prolonged_bleeding = Set(self.pmh_proforma_easy_bruising_prolonged_bleeding);
      item.pmh_proforma_dvt_or_pe = Set(self.pmh_proforma_dvt_or_pe);
      item.pmh_proforma_dvt_or_pe_within_past3_months = Set(self.pmh_proforma_dvt_or_pe_within_past3_months);
      item.pmh_proforma_gord = Set(self.pmh_proforma_gord);
      item.pmh_proforma_any_other_disease = Set(self.pmh_proforma_any_other_disease);
      item.pmh_proforma_chronic_pain = Set(self.pmh_proforma_chronic_pain);
      item.pmh_proforma_duke_activity_status_index = Set(self.pmh_proforma_duke_activity_status_index);
      item.pmh_proforma_mets_score = Set(self.pmh_proforma_mets_score);
      item.pmh_proforma_ongoing_medications = Set(self.pmh_proforma_ongoing_medications.clone());
      item.pmh_proforma_cortisone_prednisone_steroid = Set(self.pmh_proforma_cortisone_prednisone_steroid);
      item.pmh_proforma_blood_transfusion_history = Set(self.pmh_proforma_blood_transfusion_history);
      item.pmh_proforma_chemotherapy_drugs = Set(self.pmh_proforma_chemotherapy_drugs);
      item.pmh_proforma_radiotherapy = Set(self.pmh_proforma_radiotherapy);
      item.airway_exam_proforma_mouth_opening = Set(self.airway_exam_proforma_mouth_opening);
      item.airway_exam_proforma_loose_teeth = Set(self.airway_exam_proforma_loose_teeth);
      item.airway_exam_proforma_denture_missing = Set(self.airway_exam_proforma_denture_missing);
      item.airway_exam_proforma_mp_grade = Set(self.airway_exam_proforma_mp_grade.clone());
      item.airway_exam_proforma_micrognathia = Set(self.airway_exam_proforma_micrognathia);
      item.airway_exam_proforma_tm_distance_over65 = Set(self.airway_exam_proforma_tm_distance_over65);
      item.airway_exam_proforma_mo_distance = Set(self.airway_exam_proforma_mo_distance);
      item.airway_exam_proforma_tm_joint = Set(self.airway_exam_proforma_tm_joint);
      item.airway_exam_proforma_short_neck_rom = Set(self.airway_exam_proforma_short_neck_rom);
      item.airway_exam_proforma_difficult_airway = Set(self.airway_exam_proforma_difficult_airway);
      item.airway_exam_proforma_obesity_scoring = Set(self.airway_exam_proforma_obesity_scoring);
      item.airway_exam_proforma_spine_back = Set(self.airway_exam_proforma_spine_back);
      item.airway_exam_proforma_scoliosis = Set(self.airway_exam_proforma_scoliosis);
      item.airway_exam_proforma_vitals_examination = Set(self.airway_exam_proforma_vitals_examination);
      item.vitals_proforma_height_cm = Set(self.vitals_proforma_height_cm);
      item.vitals_proforma_weight_kg = Set(self.vitals_proforma_weight_kg);
      item.vitals_proforma_hr = Set(self.vitals_proforma_hr);
      item.vitals_proforma_bp = Set(self.vitals_proforma_bp.clone());
      item.vitals_proforma_resp_rate = Set(self.vitals_proforma_resp_rate);
      item.vitals_proforma_spo2 = Set(self.vitals_proforma_spo2);
      item.vitals_proforma_temp = Set(self.vitals_proforma_temp);
      item.vitals_proforma_bmi = Set(self.vitals_proforma_bmi);
      item.gen_exam_proforma_pallor = Set(self.gen_exam_proforma_pallor);
      item.gen_exam_proforma_icterus = Set(self.gen_exam_proforma_icterus);
      item.gen_exam_proforma_cyanosis = Set(self.gen_exam_proforma_cyanosis);
      item.gen_exam_proforma_clubbing = Set(self.gen_exam_proforma_clubbing);
      item.gen_exam_proforma_koilonychia = Set(self.gen_exam_proforma_koilonychia);
      item.gen_exam_proforma_lymphadenopathy = Set(self.gen_exam_proforma_lymphadenopathy);
      item.gen_exam_proforma_edema = Set(self.gen_exam_proforma_edema);
      item.gen_exam_proforma_jvp = Set(self.gen_exam_proforma_jvp);
      item.invest_proforma_blood_group_haemoglobin = Set(self.invest_proforma_blood_group_haemoglobin.clone());
      item.invest_proforma_differential_n = Set(self.invest_proforma_differential_n.clone());
      item.invest_proforma_differential_l = Set(self.invest_proforma_differential_l.clone());
      item.invest_proforma_differential_e = Set(self.invest_proforma_differential_e.clone());
      item.invest_proforma_differential_m = Set(self.invest_proforma_differential_m.clone());
      item.invest_proforma_differential_b = Set(self.invest_proforma_differential_b.clone());
      item.invest_proforma_absolute = Set(self.invest_proforma_absolute.clone());
      item.invest_proforma_nc = Set(self.invest_proforma_nc.clone());
      item.invest_proforma_tlc = Set(self.invest_proforma_tlc.clone());
      item.invest_proforma_tpc = Set(self.invest_proforma_tpc.clone());
      item.invest_proforma_esr = Set(self.invest_proforma_esr.clone());
      item.invest_proforma_crp = Set(self.invest_proforma_crp.clone());
      item.invest_proforma_pcv = Set(self.invest_proforma_pcv.clone());
      item.invest_proforma_latex_rast = Set(self.invest_proforma_latex_rast.clone());
      item.invest_proforma_fbs = Set(self.invest_proforma_fbs.clone());
      item.invest_proforma_ppbs = Set(self.invest_proforma_ppbs.clone());
      item.invest_proforma_hba1c = Set(self.invest_proforma_hba1c.clone());
      item.invest_proforma_na = Set(self.invest_proforma_na.clone());
      item.invest_proforma_k = Set(self.invest_proforma_k.clone());
      item.invest_proforma_urea = Set(self.invest_proforma_urea.clone());
      item.invest_proforma_creatinine = Set(self.invest_proforma_creatinine.clone());
      item.invest_proforma_bilirubin_total = Set(self.invest_proforma_bilirubin_total.clone());
      item.invest_proforma_bilirubin_direct = Set(self.invest_proforma_bilirubin_direct.clone());
      item.invest_proforma_alk_phosphatase = Set(self.invest_proforma_alk_phosphatase.clone());
      item.invest_proforma_sgpt_alt = Set(self.invest_proforma_sgpt_alt.clone());
      item.invest_proforma_sgot_ast = Set(self.invest_proforma_sgot_ast.clone());
      item.invest_proforma_bt = Set(self.invest_proforma_bt.clone());
      item.invest_proforma_ct = Set(self.invest_proforma_ct.clone());
      item.invest_proforma_pt = Set(self.invest_proforma_pt.clone());
      item.invest_proforma_aptt = Set(self.invest_proforma_aptt.clone());
      item.invest_proforma_inr = Set(self.invest_proforma_inr.clone());
      item.invest_proforma_ft3 = Set(self.invest_proforma_ft3.clone());
      item.invest_proforma_ft4 = Set(self.invest_proforma_ft4.clone());
      item.invest_proforma_tsh = Set(self.invest_proforma_tsh.clone());
      item.invest_proforma_ecg = Set(self.invest_proforma_ecg.clone());
      item.invest_proforma_chest_xray = Set(self.invest_proforma_chest_xray.clone());
      item.invest_proforma_pft = Set(self.invest_proforma_pft.clone());
      item.invest_proforma_abg = Set(self.invest_proforma_abg.clone());
      item.invest_proforma_two_d_echo = Set(self.invest_proforma_two_d_echo.clone());
      item.invest_proforma_lvef_percent = Set(self.invest_proforma_lvef_percent);
      item.invest_proforma_tmt = Set(self.invest_proforma_tmt.clone());
      item.invest_proforma_ct_scan = Set(self.invest_proforma_ct_scan.clone());
      item.invest_proforma_mri = Set(self.invest_proforma_mri.clone());
      item.risk_factors_cardiac = Set(self.risk_factors_cardiac);
      item.risk_factors_respiratory = Set(self.risk_factors_respiratory);
      item.risk_factors_diabetes = Set(self.risk_factors_diabetes);
      item.risk_factors_insulin = Set(self.risk_factors_insulin);
      item.risk_factors_bmi_over40 = Set(self.risk_factors_bmi_over40);
      item.risk_factors_anticoagulants = Set(self.risk_factors_anticoagulants);
      item.risk_factors_allergies = Set(self.risk_factors_allergies);
      item.risk_factors_antiplatelets = Set(self.risk_factors_antiplatelets);
      item.risk_factors_egfr_under30 = Set(self.risk_factors_egfr_under30);
      item.risk_factors_egfr30_to60 = Set(self.risk_factors_egfr30_to60);
      item.risk_factors_age_over70 = Set(self.risk_factors_age_over70);
      item.risk_factors_pvd = Set(self.risk_factors_pvd);
      item.risk_factors_liver_disease = Set(self.risk_factors_liver_disease);
      item.risk_factors_vte_risk = Set(self.risk_factors_vte_risk);
      item.risk_factors_complex_needs = Set(self.risk_factors_complex_needs);
      item.risk_factors_anaemia = Set(self.risk_factors_anaemia);
      item.risk_factors_neuromuscular_disorders = Set(self.risk_factors_neuromuscular_disorders);
      item.risk_factors_others = Set(self.risk_factors_others);
      item.risk_factors_others_details = Set(self.risk_factors_others_details.clone());
      item.anaes_plan_proforma_anaesthetic_concerns = Set(self.anaes_plan_proforma_anaesthetic_concerns.clone());
      item.anaes_plan_proforma_plan_tiva = Set(self.anaes_plan_proforma_plan_tiva);
      item.anaes_plan_proforma_plan_ra = Set(self.anaes_plan_proforma_plan_ra);
      item.anaes_plan_proforma_plan_other = Set(self.anaes_plan_proforma_plan_other);
      item.anaes_plan_proforma_plan_other_details = Set(self.anaes_plan_proforma_plan_other_details.clone());
      item.anaes_plan_proforma_list_for_ot_defer_not_fit = Set(self.anaes_plan_proforma_list_for_ot_defer_not_fit.clone());
      item.anaes_plan_proforma_nil_orally_after = Set(self.anaes_plan_proforma_nil_orally_after.clone());
      item.anaes_plan_proforma_informed_written_consent = Set(self.anaes_plan_proforma_informed_written_consent);
      item.anaes_plan_proforma_risks_benefits_alternatives_discussed = Set(self.anaes_plan_proforma_risks_benefits_alternatives_discussed);
      item.anaes_plan_proforma_arrange_units_of_blood = Set(self.anaes_plan_proforma_arrange_units_of_blood.clone());
      item.anaes_plan_proforma_arrange_post_op_icu = Set(self.anaes_plan_proforma_arrange_post_op_icu);
      item.anaes_plan_proforma_backup = Set(self.anaes_plan_proforma_backup);
      item.anaes_plan_proforma_do_investigations = Set(self.anaes_plan_proforma_do_investigations.clone());
      item.anaes_plan_proforma_do_special_orders = Set(self.anaes_plan_proforma_do_special_orders.clone());
      item.anaes_plan_proforma_reviewed_high_risk_anaesthesia = Set(self.anaes_plan_proforma_reviewed_high_risk_anaesthesia);
      item.anaes_plan_proforma_reviewed_consent = Set(self.anaes_plan_proforma_reviewed_consent);
      item.anaes_plan_proforma_consultant_anaesthesiologist_name = Set(self.anaes_plan_proforma_consultant_anaesthesiologist_name.clone());
      item.anaes_plan_proforma_consultant_anaesthesiologist_signature = Set(self.anaes_plan_proforma_consultant_anaesthesiologist_signature.clone());
      }
}

async fn load_item(ctx: &AppContext, id: i64) -> Result<Model> {
    let item = Entity::find_by_id(id).one(&ctx.db).await?;
    item.ok_or_else(|| Error::NotFound)
}

#[debug_handler]
pub async fn list(State(ctx): State<AppContext>) -> Result<Response> {
    format::json(Entity::find().all(&ctx.db).await?)
}

#[debug_handler]
pub async fn add(State(ctx): State<AppContext>, Json(params): Json<Params>) -> Result<Response> {
    let mut item = ActiveModel {
        ..Default::default()
    };
    params.update(&mut item);
    let item = item.insert(&ctx.db).await?;
    format::json(item)
}

#[debug_handler]
pub async fn update(
    Path(id): Path<i64>,
    State(ctx): State<AppContext>,
    Json(params): Json<Params>,
) -> Result<Response> {
    let item = load_item(&ctx, id).await?;
    let mut item = item.into_active_model();
    params.update(&mut item);
    let item = item.update(&ctx.db).await?;
    format::json(item)
}

#[debug_handler]
pub async fn remove(Path(id): Path<i64>, State(ctx): State<AppContext>) -> Result<Response> {
    load_item(&ctx, id).await?.delete(&ctx.db).await?;
    format::empty()
}

#[debug_handler]
pub async fn get_one(Path(id): Path<i64>, State(ctx): State<AppContext>) -> Result<Response> {
    format::json(load_item(&ctx, id).await?)
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("api/pre_anaesthesia_assessments/")
        .add("/", get(list))
        .add("/", post(add))
        .add("{id}", get(get_one))
        .add("{id}", delete(remove))
        .add("{id}", put(update))
        .add("{id}", patch(update))
}
