/** Creates a default empty assessment data structure for the Diabetes Assessment. */
export function createDefaultAssessment() {
  return {
    patientInformation: {
      fullName: '',
      dateOfBirth: '',
      nhsNumber: '',
      address: '',
      telephone: '',
      email: '',
      gpName: '',
      gpPractice: '',
    },
    diabetesHistory: {
      diabetesType: '',
      ageAtDiagnosis: null,
      yearsDuration: null,
      diagnosisMethod: '',
      familyHistory: '',
      autoantibodiesTested: '',
    },
    glycaemicControl: {
      hba1cValue: null,
      hba1cUnit: '',
      hba1cTarget: null,
      fastingGlucose: null,
      postprandialGlucose: null,
      glucoseMonitoringType: '',
      hypoglycaemiaFrequency: '',
      severeHypoglycaemia: '',
      timeInRange: null,
    },
    medications: {
      metformin: '',
      sulfonylurea: '',
      sglt2Inhibitor: '',
      glp1Agonist: '',
      dpp4Inhibitor: '',
      insulin: '',
      insulinRegimen: '',
      insulinDailyDose: null,
      medicationAdherence: null,
      otherMedications: '',
    },
    complicationsScreening: {
      retinopathyStatus: '',
      lastEyeScreening: '',
      nephropathyStatus: '',
      egfr: null,
      urineAcr: null,
      neuropathySymptoms: '',
      autonomicNeuropathy: '',
      erectileDysfunction: '',
    },
    cardiovascularRisk: {
      systolicBp: null,
      diastolicBp: null,
      onAntihypertensive: '',
      totalCholesterol: null,
      ldlCholesterol: null,
      onStatin: '',
      smokingStatus: '',
      previousCvdEvent: '',
      qriskScore: null,
    },
    selfCareLifestyle: {
      dietAdherence: null,
      carbCounting: '',
      physicalActivity: '',
      bmi: null,
      weightChange: '',
      alcoholConsumption: '',
      smokingCessation: '',
    },
    psychologicalWellbeing: {
      diabetesDistress: null,
      depressionScreening: null,
      anxietyScreening: null,
      eatingDisorder: '',
      fearOfHypoglycaemia: null,
      copingAbility: null,
      needsSupport: '',
    },
    footAssessment: {
      footPulses: '',
      monofilamentTest: '',
      vibrationSense: '',
      footDeformity: '',
      callusPresent: '',
      ulcerPresent: '',
      previousAmputation: '',
      footRiskCategory: '',
    },
    reviewCarePlan: {
      clinicianName: '',
      reviewDate: '',
      hba1cTargetAgreed: null,
      carePlanUpdated: '',
      clinicalNotes: '',
      referrals: '',
      nextReviewDate: '',
    },
  };
}
