//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "records_to_releases")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub record_types: String,
    pub specific_date_range: String,
    pub date_from: Option<Date>,
    pub date_to: Option<Date>,
    #[sea_orm(column_type = "Text")]
    pub specific_record_details: String,
    pub release_form_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::release_forms::Entity",
        from = "Column::ReleaseFormId",
        to = "super::release_forms::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ReleaseForms,
}

impl Related<super::release_forms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReleaseForms.def()
    }
}
