//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "validation_additional_flags")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub flag_id: String,
    pub category: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub priority: String,
    pub validation_result_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::validation_results::Entity",
        from = "Column::ValidationResultId",
        to = "super::validation_results::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ValidationResults,
}

impl Related<super::validation_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ValidationResults.def()
    }
}
