import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		severityScore: 5,
		primarySymptom: 'Heartburn',
		redFlagCount: 0,
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		severityScore: 18,
		primarySymptom: 'Chronic diarrhoea',
		redFlagCount: 1,
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		severityScore: 32,
		primarySymptom: 'Rectal bleeding with weight loss',
		redFlagCount: 3,
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		severityScore: 12,
		primarySymptom: 'Dyspepsia',
		redFlagCount: 0,
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		severityScore: 45,
		primarySymptom: 'Dysphagia with jaundice',
		redFlagCount: 4,
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		severityScore: 3,
		primarySymptom: 'Occasional nausea',
		redFlagCount: 0,
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		severityScore: 25,
		primarySymptom: 'IBD flare - bloody diarrhoea',
		redFlagCount: 2,
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		severityScore: 15,
		primarySymptom: 'Constipation with bloating',
		redFlagCount: 0,
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		severityScore: 28,
		primarySymptom: 'Abdominal pain with weight loss',
		redFlagCount: 2,
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		severityScore: 8,
		primarySymptom: 'Acid reflux',
		redFlagCount: 0,
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		severityScore: 22,
		primarySymptom: 'Change in bowel habit with family history',
		redFlagCount: 1,
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		severityScore: 38,
		primarySymptom: 'Jaundice with pale stools',
		redFlagCount: 3,
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		severityScore: 10,
		primarySymptom: 'Epigastric pain',
		redFlagCount: 0,
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		severityScore: 30,
		primarySymptom: 'Rectal bleeding with tenesmus',
		redFlagCount: 2,
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		severityScore: 6,
		primarySymptom: 'Intermittent nausea',
		redFlagCount: 0,
	},
];
