//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "pre_operative_assessment_by_clinicians")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub site_name: String,
    pub assessment_date: Option<Date>,
    pub assessment_time: Option<String>,
    pub planned_procedure: String,
    pub surgical_specialty: String,
    pub urgency: String,
    pub laterality: String,
    pub surgical_severity: String,
    pub anticipated_blood_loss_ml: Option<i32>,
    pub anticipated_duration_minutes: Option<i32>,
    pub consultant_surgeon: String,
    pub planned_date: Option<Date>,
    pub systolic_bp: Option<i32>,
    pub diastolic_bp: Option<i32>,
    pub heart_rate: Option<i32>,
    pub respiratory_rate: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub spo2_percent: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub temperature_celsius: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub capillary_refill_seconds: Option<f64>,
    pub pain_score_0_10: Option<i32>,
    pub on_room_air: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub supplemental_oxygen_litres: Option<f64>,
    pub mallampati_class: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub thyromental_distance_cm: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub mouth_opening_cm: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub inter_incisor_gap_cm: Option<f64>,
    pub neck_rom: String,
    pub cervical_spine_stability: String,
    pub dentition: String,
    pub beard: String,
    pub upper_lip_bite_test: String,
    pub prior_difficult_intubation: String,
    pub stopbang_snoring: String,
    pub stopbang_tired: String,
    pub stopbang_observed_apnoea: String,
    pub stopbang_pressure: String,
    pub stopbang_bmi_gt35: String,
    pub stopbang_age_gt50: String,
    pub stopbang_neck_gt40: String,
    pub stopbang_male: String,
    #[sea_orm(column_type = "Text")]
    pub airway_notes: String,
    pub heart_rhythm: String,
    pub murmur_present: String,
    pub murmur_description: String,
    pub peripheral_pulses: String,
    pub jvp_raised: String,
    pub peripheral_oedema: String,
    pub ecg_performed: String,
    pub ecg_rhythm: String,
    pub ecg_rate_bpm: Option<i32>,
    pub ecg_axis: String,
    pub ecg_ischaemic_changes: String,
    #[sea_orm(column_type = "Text")]
    pub ecg_notes: String,
    pub echo_performed: String,
    pub echo_ef_percent: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub echo_notes: String,
    pub history_ihd: String,
    pub history_chf: String,
    pub history_stroke_tia: String,
    pub recent_mi_within_3_months: String,
    pub pacemaker_or_icd: String,
    pub severe_valve_dysfunction: String,
    pub active_angina: String,
    pub breath_sounds: String,
    pub wheeze: String,
    pub crackles: String,
    pub crepitations: String,
    pub chest_wall_deformity: String,
    pub asthma: String,
    pub copd: String,
    pub cxr_performed: String,
    #[sea_orm(column_type = "Text")]
    pub cxr_findings: String,
    pub pft_performed: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub pft_fev1_percent_predicted: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub pft_fev1_fvc_ratio: Option<f64>,
    pub smoking_status: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub pack_years: Option<f64>,
    pub covid_history: String,
    pub days_since_covid: Option<i32>,
    pub covid_unresolved_symptoms: String,
    pub gcs_total: Option<i32>,
    pub gcs_eye: Option<i32>,
    pub gcs_verbal: Option<i32>,
    pub gcs_motor: Option<i32>,
    pub cognition_tool: String,
    pub cognition_score: Option<i32>,
    pub cognitive_impairment: String,
    pub capacity_concern: String,
    #[sea_orm(column_type = "Text")]
    pub cranial_nerves_notes: String,
    pub motor_power: String,
    #[sea_orm(column_type = "Text")]
    pub sensory_notes: String,
    pub reflexes: String,
    pub recent_stroke_tia: String,
    pub days_since_stroke_tia: Option<i32>,
    pub seizure_disorder: String,
    pub creatinine_umol_l: Option<i32>,
    pub egfr_ml_min_1_73m2: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub urea_mmol_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub potassium_mmol_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub sodium_mmol_l: Option<f64>,
    pub dialysis_status: String,
    pub ckd_stage: String,
    pub bilirubin_umol_l: Option<i32>,
    pub alt_u_l: Option<i32>,
    pub ast_u_l: Option<i32>,
    pub alp_u_l: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub albumin_g_l: Option<f64>,
    pub chronic_liver_disease: String,
    pub child_pugh_class: String,
    pub hb_g_l: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub wcc_10_9_l: Option<f64>,
    pub platelets_10_9_l: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub mcv_fl: Option<f64>,
    pub ferritin_ug_l: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub transferrin_saturation_percent: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub inr: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub aptt_seconds: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fibrinogen_g_l: Option<f64>,
    pub on_anticoagulant: String,
    pub anticoagulant_type: String,
    pub anticoagulant_hold_plan: String,
    pub group_and_save: String,
    pub crossmatch_units: Option<i32>,
    pub last_transfusion_date: Option<Date>,
    pub anaemia_severity: String,
    pub diabetes_type: String,
    pub diabetes_on_insulin: String,
    pub hba1c_mmol_mol: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub fasting_glucose_mmol_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub random_glucose_mmol_l: Option<f64>,
    pub diabetes_control: String,
    pub diabetes_complications: String,
    pub thyroid_status: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub tsh_mu_l: Option<f64>,
    pub adrenal_status: String,
    pub on_long_term_steroids: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub steroid_dose_mg: Option<f64>,
    pub steroid_cover_plan: String,
    pub abdominal_exam: String,
    #[sea_orm(column_type = "Text")]
    pub abdominal_notes: String,
    pub reflux_symptoms: String,
    pub hiatus_hernia: String,
    pub previous_gastric_surgery: String,
    pub ng_tube: String,
    pub stoma: String,
    pub fasting_confirmed: String,
    pub last_solid_food_at: Option<DateTimeWithTimeZone>,
    pub last_clear_fluid_at: Option<DateTimeWithTimeZone>,
    pub rapid_sequence_induction_needed: String,
    pub spine_exam: String,
    #[sea_orm(column_type = "Text")]
    pub spine_notes: String,
    pub neuraxial_suitable: String,
    pub joint_rom_hip: String,
    pub joint_rom_shoulder: String,
    pub joint_rom_neck: String,
    pub skin_iv_access: String,
    pub skin_block_site: String,
    pub pressure_ulcer_risk: String,
    pub name: String,
    pub dose: String,
    pub route: String,
    pub frequency: String,
    pub indication: String,
    pub class: String,
    pub perioperative_action: String,
    pub perioperative_notes: String,
    pub last_dose_at: Option<DateTimeWithTimeZone>,
    pub on_glp1_receptor_agonist: String,
    pub glp1_agonist_name: String,
    pub glp1_formulation: String,
    pub glp1_last_dose_at: Option<DateTimeWithTimeZone>,
    pub glp1_held_per_guideline: String,
    pub glp1_extended_clear_fluids_confirmed: String,
    pub glp1_gi_symptoms: String,
    pub glp1_gi_symptoms_details: String,
    pub glp1_gastric_ultrasound_performed: String,
    pub glp1_gastric_ultrasound_findings: String,
    pub glp1_full_stomach_precautions_planned: String,
    pub glp1_notes: String,
    pub allergen: String,
    pub category: String,
    pub reaction_type: String,
    pub reaction_severity: String,
    pub reaction_notes: String,
    pub verified: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub mets_estimate: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub dasi_score: Option<f64>,
    pub ecog_performance_status: Option<i32>,
    pub clinical_frailty_scale: Option<i32>,
    pub six_minute_walk_metres: Option<i32>,
    pub sts_one_minute_reps: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tug_seconds: Option<f64>,
    pub cpet_performed: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub cpet_vo2_peak_ml_kg_min: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cpet_anaerobic_threshold_ml_kg_min: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub cpet_notes: String,
    pub malnutrition_risk: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub unintentional_weight_loss_kg: Option<f64>,
    pub fried_weakness: String,
    pub fried_slowness: String,
    pub fried_low_physical_activity: String,
    pub fried_exhaustion: String,
    pub fried_unintentional_weight_loss: String,
    pub risk_analysis_index_score: Option<i32>,
    pub mini_cog_performed: String,
    pub mini_cog_score: Option<i32>,
    pub prehabilitation_indicated: String,
    pub prehabilitation_type: String,
    pub prehabilitation_start_date: Option<Date>,
    pub protein_supplementation_recommended: String,
    pub technique: String,
    pub airway_plan: String,
    pub rsi_planned: String,
    pub monitoring_level: String,
    pub analgesia_plan: String,
    pub regional_block_planned: String,
    pub dvt_prophylaxis: String,
    pub antibiotic_prophylaxis: String,
    pub post_op_disposition: String,
    pub anticipated_length_of_stay_days: Option<i32>,
    pub special_equipment: String,
    pub blood_products_required: String,
    pub patient_id: i64,
    pub clinician_id: i64,
    pub hospital_number: String,
    pub indication_for_surgery: String,
    pub anaesthetist_name: String,
    pub previous_surgeries: String,
    pub previous_anaesthetic_issues: String,
    pub previous_anaesthetic_issues_details: String,
    pub family_history_anaesthetic_complications: String,
    pub family_history_anaesthetic_complications_details: String,
    pub urinalysis_findings: String,
    pub living_situation: String,
    pub support_at_home: String,
    pub mobility_status: String,
    pub falls_risk_within_year: String,
    pub vte_risk_level: String,
    pub covid_screening_result: String,
    pub discharge_destination: String,
    pub follow_up_requirements: String,
    pub social_services_involvement: String,
    pub reablement_physiotherapy_needs: String,
    pub consent_status: String,
    pub interpreter_required: String,
    pub discussion_procedure: String,
    pub discussion_anaesthetic: String,
    pub discussion_risks_benefits: String,
    pub discussion_alternatives: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::pre_operative_assessment_by_clinician_grades::Entity")]
    PreOperativeAssessmentByClinicianGrades,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::pre_operative_assessment_by_clinician_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PreOperativeAssessmentByClinicianGrades.def()
    }
}
