//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "respect")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub person_name: String,
    pub date_of_birth: Option<Date>,
    #[sea_orm(column_type = "Text")]
    pub identifier: String,
    #[sea_orm(column_type = "Text")]
    pub address: String,
    #[sea_orm(column_type = "Text")]
    pub key_contact: String,
    #[sea_orm(column_type = "Text")]
    pub health_summary: String,
    #[sea_orm(column_type = "Text")]
    pub diagnoses: String,
    #[sea_orm(column_type = "Text")]
    pub existing_documents: String,
    #[sea_orm(column_type = "Text")]
    pub what_matters: String,
    #[sea_orm(column_type = "Text")]
    pub care_preferences: String,
    pub priority_balance: String,
    #[sea_orm(column_type = "Text")]
    pub recommended_interventions: String,
    #[sea_orm(column_type = "Text")]
    pub not_recommended_interventions: String,
    pub cpr_recommendation: String,
    #[sea_orm(column_type = "Text")]
    pub cpr_rationale: String,
    pub cpr_discussed: String,
    pub hospital_transfer: String,
    pub critical_care_admission: String,
    #[sea_orm(column_type = "Text")]
    pub treatment_ceilings: String,
    pub has_capacity: String,
    #[sea_orm(column_type = "Text")]
    pub capacity_assessment: String,
    pub involvement: String,
    #[sea_orm(column_type = "Text")]
    pub proxy_details: String,
    #[sea_orm(column_type = "Text")]
    pub clinician_name: String,
    pub clinician_role: String,
    #[sea_orm(column_type = "Text")]
    pub clinician_registration: String,
    #[sea_orm(column_type = "Text")]
    pub signature: String,
    pub signed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub senior_endorsement: String,
    #[sea_orm(column_type = "Text")]
    pub emergency_contacts: String,
    pub review_date: Option<Date>,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::respect_grades::Entity")]
    RespectGrades,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::respect_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RespectGrades.def()
    }
}
