#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding birth-control-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    preferred_name:string! \
    gender_identity:string! \
    ethnicity:string! \
    preferred_language:string! \
    interpreter_required:string! \
    gp_name:string! \
    gp_practice:string! \
    referrer_name:string! \
    referrer_role:string! \
    --htmx

cargo loco generate scaffold assessment_menstrual_history \
    assessment:references \
    menarche_age:int \
    cycle_regularity:string! \
    cycle_length_days:int \
    period_duration_days:int \
    flow_heaviness:string! \
    intermenstrual_bleeding:string! \
    postcoital_bleeding:string! \
    dysmenorrhoea:string! \
    last_menstrual_period:date \
    amenorrhoea:string! \
    amenorrhoea_duration_months:int \
    menstrual_notes:text! \
    --htmx

cargo loco generate scaffold assessment_contraceptive_history \
    assessment:references \
    previous_contraception:string! \
    previous_coc:string! \
    coc_details:text! \
    previous_pop:string! \
    pop_details:text! \
    previous_implant:string! \
    implant_details:text! \
    previous_injection:string! \
    injection_details:text! \
    previous_iud:string! \
    iud_details:text! \
    previous_ius:string! \
    ius_details:text! \
    previous_patch_ring:string! \
    patch_ring_details:text! \
    previous_barrier:string! \
    reason_for_change:text! \
    adverse_effects:text! \
    contraceptive_history_notes:text! \
    --htmx

cargo loco generate scaffold assessment_medical_history \
    assessment:references \
    migraine:string! \
    migraine_with_aura:string! \
    migraine_frequency:string! \
    breast_cancer:string! \
    cervical_cancer:string! \
    liver_disease:string! \
    gallbladder_disease:string! \
    inflammatory_bowel_disease:string! \
    systemic_lupus_erythematosus:string! \
    sle_antiphospholipid:string! \
    epilepsy:string! \
    diabetes:string! \
    diabetes_complications:string! \
    sexually_transmitted_infection:string! \
    sti_details:text! \
    pelvic_inflammatory_disease:string! \
    medical_history_notes:text! \
    --htmx

cargo loco generate scaffold assessment_cardiovascular_risk \
    assessment:references \
    hypertension:string! \
    systolic_bp_mmhg:int \
    diastolic_bp_mmhg:int \
    bp_controlled:string! \
    ischaemic_heart_disease:string! \
    stroke_history:string! \
    valvular_heart_disease:string! \
    valvular_complications:string! \
    hyperlipidaemia:string! \
    family_history_vte:string! \
    family_history_cvd:string! \
    family_cvd_details:text! \
    cardiovascular_notes:text! \
    --htmx

cargo loco generate scaffold assessment_thromboembolism_risk \
    assessment:references \
    previous_dvt:string! \
    dvt_details:text! \
    previous_pe:string! \
    pe_details:text! \
    known_thrombophilia:string! \
    thrombophilia_type:string! \
    immobility_risk:string! \
    immobility_details:text! \
    recent_major_surgery:string! \
    surgery_details:text! \
    long_haul_travel:string! \
    varicose_veins:string! \
    thromboembolism_notes:text! \
    --htmx

cargo loco generate scaffold assessment_current_medications \
    assessment:references \
    on_enzyme_inducing_drugs:string! \
    enzyme_inducing_details:text! \
    on_anticoagulants:string! \
    anticoagulant_details:text! \
    on_antiepileptics:string! \
    antiepileptic_details:text! \
    on_antiretrovirals:string! \
    antiretroviral_details:text! \
    on_antibiotics:string! \
    antibiotic_details:text! \
    on_ssri_snri:string! \
    ssri_snri_details:text! \
    herbal_remedies:string! \
    herbal_details:text! \
    other_medications:text! \
    drug_allergies:string! \
    drug_allergy_details:text! \
    medication_notes:text! \
    --htmx

cargo loco generate scaffold assessment_lifestyle \
    assessment:references \
    smoking_status:string! \
    cigarettes_per_day:int \
    age_over_35_smoker:string! \
    alcohol_consumption:string! \
    alcohol_units_per_week:int \
    recreational_drug_use:string! \
    recreational_drug_details:text! \
    exercise_frequency:string! \
    sexual_activity:string! \
    number_of_partners:string! \
    pregnancy_risk_awareness:string! \
    lifestyle_notes:text! \
    --htmx

cargo loco generate scaffold assessment_contraceptive_preferences \
    assessment:references \
    preferred_method:string! \
    hormonal_acceptable:string! \
    long_acting_acceptable:string! \
    daily_pill_acceptable:string! \
    intrauterine_acceptable:string! \
    fertility_plans:string! \
    breastfeeding:string! \
    postpartum_weeks:int \
    concerns:text! \
    preference_notes:text! \
    --htmx

cargo loco generate scaffold assessment_clinical_recommendation \
    assessment:references \
    recommended_method:string! \
    alternative_methods:text! \
    methods_contraindicated:text! \
    counselling_provided:string! \
    counselling_topics:text! \
    follow_up_required:string! \
    follow_up_interval:string! \
    referral_required:string! \
    referral_details:text! \
    clinical_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    mec_category_coc:string! \
    mec_category_pop:string! \
    mec_category_implant:string! \
    mec_category_injection:string! \
    mec_category_iud:string! \
    mec_category_ius:string! \
    overall_risk_level:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
