//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "hipaa_authorizations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub state_template: String,
    pub revoked_at: Option<DateTimeWithTimeZone>,
    pub revocation_method: String,
    pub patient_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::authorized_recipients::Entity")]
    AuthorizedRecipients,
    #[sea_orm(has_many = "super::disclosing_sources::Entity")]
    DisclosingSources,
    #[sea_orm(has_many = "super::expirations::Entity")]
    Expirations,
    #[sea_orm(has_many = "super::patient_rights_acknowledgements::Entity")]
    PatientRightsAcknowledgements,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::purpose_of_disclosures::Entity")]
    PurposeOfDisclosures,
    #[sea_orm(has_many = "super::records_to_discloses::Entity")]
    RecordsToDiscloses,
    #[sea_orm(has_many = "super::signature_witnesses::Entity")]
    SignatureWitnesses,
    #[sea_orm(has_many = "super::signers::Entity")]
    Signers,
    #[sea_orm(has_many = "super::validation_results::Entity")]
    ValidationResults,
}

impl Related<super::authorized_recipients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorizedRecipients.def()
    }
}

impl Related<super::disclosing_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DisclosingSources.def()
    }
}

impl Related<super::expirations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Expirations.def()
    }
}

impl Related<super::patient_rights_acknowledgements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PatientRightsAcknowledgements.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::purpose_of_disclosures::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PurposeOfDisclosures.def()
    }
}

impl Related<super::records_to_discloses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecordsToDiscloses.def()
    }
}

impl Related<super::signature_witnesses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SignatureWitnesses.def()
    }
}

impl Related<super::signers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Signers.def()
    }
}

impl Related<super::validation_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ValidationResults.def()
    }
}
