//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "signers")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub relationship: String,
    pub representative_name: String,
    #[sea_orm(column_type = "Text")]
    pub representative_authority_description: String,
    pub representative_authority_proof_attached: String,
    pub hipaa_authorization_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hipaa_authorizations::Entity",
        from = "Column::HipaaAuthorizationId",
        to = "super::hipaa_authorizations::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    HipaaAuthorizations,
}

impl Related<super::hipaa_authorizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HipaaAuthorizations.def()
    }
}
