//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "fluid_balance_charts")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub clinician_name: String,
    pub clinician_role: String,
    #[sea_orm(column_type = "Text")]
    pub patient_identifier: String,
    #[sea_orm(column_type = "Text")]
    pub ward_or_unit: String,
    pub chart_start_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Double", nullable)]
    pub chart_period_hours: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight_kg: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub clinical_note: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::fluid_balance_chart_entries::Entity")]
    FluidBalanceChartEntries,
    #[sea_orm(has_many = "super::fluid_balance_chart_grades::Entity")]
    FluidBalanceChartGrades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::fluid_balance_chart_entries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FluidBalanceChartEntries.def()
    }
}

impl Related<super::fluid_balance_chart_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FluidBalanceChartGrades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
