//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "centor_score_for_streptococcal_pharyngitis")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub clinician_name: String,
    pub clinician_role: String,
    pub assessed_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    pub patient_identifier: String,
    pub age_years: Option<i32>,
    pub sex: String,
    pub tonsillar_exudate: String,
    pub tender_anterior_cervical_nodes: String,
    pub fever_over_38: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub measured_temperature_celsius: Option<f64>,
    pub absence_of_cough: String,
    pub stridor_or_breathing_difficulty: String,
    pub drooling_or_cannot_swallow: String,
    pub trismus: String,
    pub muffled_voice: String,
    pub unilateral_neck_swelling: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_note: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::centor_score_for_streptococcal_pharyngitis_grades::Entity")]
    CentorScoreForStreptococcalPharyngitisGrades,
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::centor_score_for_streptococcal_pharyngitis_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CentorScoreForStreptococcalPharyngitisGrades.def()
    }
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
