//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "centor_score_for_streptococcal_pharyngitis_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub centor_score: Option<i32>,
    pub age_modifier: Option<i32>,
    pub mcisaac_score: Option<i32>,
    pub risk_band: String,
    #[sea_orm(column_type = "Text")]
    pub management: String,
    pub graded_at: DateTimeWithTimeZone,
    pub centor_score_for_streptococcal_pharyngitis_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::centor_score_for_streptococcal_pharyngitis::Entity",
        from = "Column::CentorScoreForStreptococcalPharyngitisId",
        to = "super::centor_score_for_streptococcal_pharyngitis::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CentorScoreForStreptococcalPharyngitis,
    #[sea_orm(has_many = "super::centor_score_for_streptococcal_pharyngitis_grade_flags::Entity")]
    CentorScoreForStreptococcalPharyngitisGradeFlags,
    #[sea_orm(has_many = "super::centor_score_for_streptococcal_pharyngitis_grade_rules::Entity")]
    CentorScoreForStreptococcalPharyngitisGradeRules,
}

impl Related<super::centor_score_for_streptococcal_pharyngitis::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CentorScoreForStreptococcalPharyngitis.def()
    }
}

impl Related<super::centor_score_for_streptococcal_pharyngitis_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CentorScoreForStreptococcalPharyngitisGradeFlags.def()
    }
}

impl Related<super::centor_score_for_streptococcal_pharyngitis_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CentorScoreForStreptococcalPharyngitisGradeRules.def()
    }
}
