#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding prenatal-assessment (14 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_pregnancy_details \
    assessment:references \
    estimated_due_date:date \
    gestational_age_weeks:int \
    gestational_age_days:int \
    dating_method:string! \
    last_menstrual_period:date \
    pregnancy_type:string! \
    conception_method:string! \
    planned_pregnancy:string! \
    booking_visit_completed:string! \
    booking_visit_date:date \
    blood_group:string! \
    rhesus_status:string! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_obstetric_history \
    assessment:references \
    gravida:int \
    para:int \
    living_children:int \
    miscarriages:int \
    terminations:int \
    ectopic_pregnancies:int \
    stillbirths:int \
    neonatal_deaths:int \
    previous_caesarean:string! \
    caesarean_count:int \
    previous_preterm_birth:string! \
    previous_preeclampsia:string! \
    previous_gestational_diabetes:string! \
    previous_postpartum_haemorrhage:string! \
    previous_complications_details:text! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_medical_history \
    assessment:references \
    hypertension:string! \
    diabetes:string! \
    thyroid_disorder:string! \
    thyroid_disorder_details:text! \
    autoimmune_conditions:string! \
    autoimmune_details:text! \
    epilepsy:string! \
    cardiac_conditions:string! \
    cardiac_details:text! \
    renal_conditions:string! \
    renal_details:text! \
    thrombophilia:string! \
    previous_vte:string! \
    psychiatric_history:string! \
    psychiatric_details:text! \
    previous_surgeries:string! \
    surgery_details:text! \
    known_allergies:string! \
    allergy_details:text! \
    current_medications:text! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_current_symptoms \
    assessment:references \
    nausea_vomiting:string! \
    hyperemesis_gravidarum:string! \
    vaginal_bleeding:string! \
    bleeding_details:text! \
    abdominal_pain:string! \
    abdominal_pain_details:text! \
    headaches:string! \
    visual_disturbances:string! \
    oedema:string! \
    oedema_location:text! \
    reduced_fetal_movement:string! \
    urinary_symptoms:string! \
    urinary_symptom_details:text! \
    pelvic_pain:string! \
    shortness_of_breath:string! \
    additional_symptoms:text! \
    --htmx

cargo loco generate scaffold assessment_vital_signs \
    assessment:references \
    systolic_bp_mmhg:int \
    diastolic_bp_mmhg:int \
    heart_rate_bpm:int \
    temperature_celsius:double \
    respiratory_rate:int \
    oxygen_saturation_pct:double \
    weight_kg:double \
    pre_pregnancy_weight_kg:double \
    weight_gain_kg:double \
    fundal_height_cm:double \
    fetal_heart_rate_bpm:int \
    fetal_lie:string! \
    fetal_presentation:string! \
    proteinuria:string! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_laboratory_results \
    assessment:references \
    haemoglobin_gdl:double \
    haematocrit_pct:double \
    platelet_count:int \
    white_blood_cell_count:double \
    blood_glucose_mmol:double \
    hba1c_pct:double \
    gtt_result:string! \
    ferritin_ngml:double \
    thyroid_tsh:double \
    hiv_screening:string! \
    hepatitis_b:string! \
    hepatitis_c:string! \
    syphilis_screening:string! \
    rubella_immunity:string! \
    group_b_strep:string! \
    urine_culture:string! \
    urine_culture_organism:text! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_lifestyle_nutrition \
    assessment:references \
    smoking_status:string! \
    cigarettes_per_day:int \
    smoking_cessation_advice:string! \
    alcohol_use:string! \
    alcohol_units_per_week:int \
    recreational_drug_use:string! \
    drug_use_details:text! \
    folic_acid_supplementation:string! \
    folic_acid_dose:string! \
    vitamin_d_supplementation:string! \
    iron_supplementation:string! \
    dietary_restrictions:text! \
    exercise_frequency:string! \
    occupation:string! \
    occupational_hazards:string! \
    occupational_hazard_details:text! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_mental_health \
    assessment:references \
    previous_mental_health_condition:string! \
    previous_condition_details:text! \
    previous_postnatal_depression:string! \
    current_mood:string! \
    feeling_anxious:string! \
    phq2_score:int \
    gad2_score:int \
    bonding_concerns:string! \
    domestic_abuse_screening:string! \
    domestic_abuse_disclosed:string! \
    social_support_adequate:string! \
    self_harm_thoughts:string! \
    current_mental_health_treatment:string! \
    treatment_details:text! \
    referral_needed:string! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_birth_plan \
    assessment:references \
    preferred_birth_location:string! \
    preferred_delivery_method:string! \
    pain_relief_preference:string! \
    birth_partner:string! \
    birth_partner_details:text! \
    skin_to_skin:string! \
    delayed_cord_clamping:string! \
    infant_feeding_intention:string! \
    vitamin_k_consent:string! \
    vitamin_k_route:string! \
    cord_blood_banking:string! \
    cultural_religious_needs:text! \
    special_requests:text! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    risk_level:string! \
    risk_score:int! \
    obstetric_risk:string! \
    medical_risk:string! \
    mental_health_risk:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    risk_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
