//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "united_kingdom_statement_of_fitness_for_works")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub assessment_date: Option<Date>,
    pub assessment_method: String,
    pub general_fitness_considered: String,
    #[sea_orm(column_type = "Text")]
    pub diagnosis_text: String,
    pub diagnosis_snomed_code: String,
    pub diagnosis_snomed_display: String,
    pub diagnosis_category: String,
    pub condition_first_recorded_date: Option<Date>,
    pub is_automatic_disability: String,
    pub is_non_medical: String,
    pub fitness_for_work: String,
    pub adaptation_phased_return: String,
    pub adaptation_altered_hours: String,
    pub adaptation_amended_duties: String,
    pub adaptation_workplace_adaptations: String,
    #[sea_orm(column_type = "Text")]
    pub comments: String,
    pub period_type: String,
    pub period_duration_value: Option<i32>,
    pub period_duration_unit: String,
    pub period_from: Option<Date>,
    pub period_to: Option<Date>,
    pub will_assess_again: String,
    pub planned_review_date: Option<Date>,
    pub issued_at: Option<DateTimeWithTimeZone>,
    pub issued_via: String,
    pub issue_setting: String,
    pub safeguarding_concern: String,
    #[sea_orm(column_type = "Text")]
    pub safeguarding_notes: String,
    #[sea_orm(column_type = "Text")]
    pub clinician_signature_svg: String,
    pub clinician_signed_at: Option<DateTimeWithTimeZone>,
    pub patient_id: i64,
    pub clinician_id: i64,
    pub medical_practice_id: i64,
    pub united_kingdom_statement_of_fitness_for_work_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::medical_practices::Entity",
        from = "Column::MedicalPracticeId",
        to = "super::medical_practices::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MedicalPractices,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::united_kingdom_statement_of_fitness_for_work_grades::Entity")]
    UnitedKingdomStatementOfFitnessForWorkGrades,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::UnitedKingdomStatementOfFitnessForWorkId",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::medical_practices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalPractices.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::united_kingdom_statement_of_fitness_for_work_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UnitedKingdomStatementOfFitnessForWorkGrades.def()
    }
}
