//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub overall_highest_ukmec_category: i32,
    pub ukmec_cocp: Option<i32>,
    pub ukmec_pop: Option<i32>,
    pub ukmec_patch: Option<i32>,
    pub ukmec_ring: Option<i32>,
    pub ukmec_injection: Option<i32>,
    pub ukmec_implant: Option<i32>,
    pub ukmec_cu_iud: Option<i32>,
    pub ukmec_lng_ius: Option<i32>,
    pub ukmec_condom_male: Option<i32>,
    pub ukmec_condom_female: Option<i32>,
    pub ukmec_diaphragm: Option<i32>,
    pub graded_at: DateTimeWithTimeZone,
    pub assessment_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assessments::Entity",
        from = "Column::AssessmentId",
        to = "super::assessments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Assessments,
    #[sea_orm(has_many = "super::grading_additional_flags::Entity")]
    GradingAdditionalFlags,
    #[sea_orm(has_many = "super::grading_fired_rules::Entity")]
    GradingFiredRules,
}

impl Related<super::assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assessments.def()
    }
}

impl Related<super::grading_additional_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GradingAdditionalFlags.def()
    }
}

impl Related<super::grading_fired_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GradingFiredRules.def()
    }
}
