//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "stomatology_waiting_list_card_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub waiting_time_status: String,
    pub clinical_priority: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub target_wait_weeks: Option<f64>,
    pub days_waited: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub weeks_waited: Option<f64>,
    pub days_to_target: Option<i32>,
    pub days_to_breach: Option<i32>,
    pub days_to_appointment: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub grader_notes: String,
    pub graded_at: DateTimeWithTimeZone,
    pub stomatology_waiting_list_card_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::stomatology_waiting_list_card_grade_flags::Entity")]
    StomatologyWaitingListCardGradeFlags,
    #[sea_orm(has_many = "super::stomatology_waiting_list_card_grade_rules::Entity")]
    StomatologyWaitingListCardGradeRules,
    #[sea_orm(
        belongs_to = "super::stomatology_waiting_list_cards::Entity",
        from = "Column::StomatologyWaitingListCardId",
        to = "super::stomatology_waiting_list_cards::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StomatologyWaitingListCards,
}

impl Related<super::stomatology_waiting_list_card_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StomatologyWaitingListCardGradeFlags.def()
    }
}

impl Related<super::stomatology_waiting_list_card_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StomatologyWaitingListCardGradeRules.def()
    }
}

impl Related<super::stomatology_waiting_list_cards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StomatologyWaitingListCards.def()
    }
}
