//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "modified_early_warning_score_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub aggregate_score: Option<i32>,
    pub systolic_blood_pressure_score: Option<i32>,
    pub heart_rate_score: Option<i32>,
    pub respiratory_rate_score: Option<i32>,
    pub temperature_score: Option<i32>,
    pub avpu_score: Option<i32>,
    pub single_parameter_trigger: String,
    pub risk_band: String,
    #[sea_orm(column_type = "Text")]
    pub monitoring_frequency: String,
    pub graded_at: DateTimeWithTimeZone,
    pub modified_early_warning_score_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::modified_early_warning_score_grade_flags::Entity")]
    ModifiedEarlyWarningScoreGradeFlags,
    #[sea_orm(has_many = "super::modified_early_warning_score_grade_rules::Entity")]
    ModifiedEarlyWarningScoreGradeRules,
    #[sea_orm(
        belongs_to = "super::modified_early_warning_scores::Entity",
        from = "Column::ModifiedEarlyWarningScoreId",
        to = "super::modified_early_warning_scores::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ModifiedEarlyWarningScores,
}

impl Related<super::modified_early_warning_score_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModifiedEarlyWarningScoreGradeFlags.def()
    }
}

impl Related<super::modified_early_warning_score_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModifiedEarlyWarningScoreGradeRules.def()
    }
}

impl Related<super::modified_early_warning_scores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModifiedEarlyWarningScores.def()
    }
}
