//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "anion_gap_calculator_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Double", nullable)]
    pub anion_gap: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub corrected_anion_gap: Option<f64>,
    pub classification: String,
    pub graded_at: DateTimeWithTimeZone,
    pub anion_gap_calculator_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::anion_gap_calculator_grade_flags::Entity")]
    AnionGapCalculatorGradeFlags,
    #[sea_orm(has_many = "super::anion_gap_calculator_grade_rules::Entity")]
    AnionGapCalculatorGradeRules,
    #[sea_orm(
        belongs_to = "super::anion_gap_calculators::Entity",
        from = "Column::AnionGapCalculatorId",
        to = "super::anion_gap_calculators::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AnionGapCalculators,
}

impl Related<super::anion_gap_calculator_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnionGapCalculatorGradeFlags.def()
    }
}

impl Related<super::anion_gap_calculator_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnionGapCalculatorGradeRules.def()
    }
}

impl Related<super::anion_gap_calculators::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnionGapCalculators.def()
    }
}
