//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "anion_gap_calculators")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub clinician_name: String,
    pub clinician_role: String,
    pub calculated_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_context: String,
    pub patient_identifier: String,
    pub age_band: String,
    pub sex: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub sodium_mmol_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub potassium_mmol_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub chloride_mmol_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub bicarbonate_mmol_l: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub albumin_g_l: Option<f64>,
    pub include_potassium: String,
    pub patient_id: i64,
    pub clinician_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::anion_gap_calculator_grades::Entity")]
    AnionGapCalculatorGrades,
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::anion_gap_calculator_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AnionGapCalculatorGrades.def()
    }
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
