//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "padua_venous_thromboembolism_risk_assessments")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub clinician_name: String,
    pub clinician_role: String,
    pub assessed_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    #[sea_orm(column_type = "Text")]
    pub admission_reason: String,
    pub patient_identifier: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub age_years: Option<f64>,
    pub sex: String,
    pub active_cancer: String,
    pub previous_vte: String,
    pub reduced_mobility: String,
    pub known_thrombophilia: String,
    pub recent_trauma_or_surgery: String,
    pub heart_or_respiratory_failure: String,
    pub acute_mi_or_ischaemic_stroke: String,
    pub acute_infection_or_rheumatological: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub body_mass_index: Option<f64>,
    pub ongoing_hormonal_treatment: String,
    pub active_bleeding: String,
    pub high_bleeding_risk: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_note: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::padua_venous_thromboembolism_risk_assessment_grades::Entity")]
    PaduaVenousThromboembolismRiskAssessmentGrades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::padua_venous_thromboembolism_risk_assessment_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaduaVenousThromboembolismRiskAssessmentGrades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
