import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		tinettiScore: 26,
		tugTime: 9,
		fallRisk: 'Low fall risk',
		assistiveDevice: 'None',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		tinettiScore: 20,
		tugTime: 13,
		fallRisk: 'Moderate fall risk',
		assistiveDevice: 'Cane',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		tinettiScore: 12,
		tugTime: 22,
		fallRisk: 'High fall risk',
		assistiveDevice: 'Walker',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		tinettiScore: 27,
		tugTime: 8,
		fallRisk: 'Low fall risk',
		assistiveDevice: 'None',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		tinettiScore: 10,
		tugTime: 28,
		fallRisk: 'High fall risk',
		assistiveDevice: 'Rollator',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		tinettiScore: 24,
		tugTime: 11,
		fallRisk: 'Moderate fall risk',
		assistiveDevice: 'None',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		tinettiScore: 15,
		tugTime: 18,
		fallRisk: 'High fall risk',
		assistiveDevice: 'Quad cane',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		tinettiScore: 22,
		tugTime: 12,
		fallRisk: 'Moderate fall risk',
		assistiveDevice: 'Cane',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		tinettiScore: 8,
		tugTime: 32,
		fallRisk: 'High fall risk',
		assistiveDevice: 'Wheelchair',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		tinettiScore: 28,
		tugTime: 7,
		fallRisk: 'Low fall risk',
		assistiveDevice: 'None',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		tinettiScore: 19,
		tugTime: 14,
		fallRisk: 'Moderate fall risk',
		assistiveDevice: 'Cane',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		tinettiScore: 6,
		tugTime: 35,
		fallRisk: 'High fall risk',
		assistiveDevice: 'Walker',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		tinettiScore: 25,
		tugTime: 10,
		fallRisk: 'Low fall risk',
		assistiveDevice: 'None',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		tinettiScore: 17,
		tugTime: 16,
		fallRisk: 'High fall risk',
		assistiveDevice: 'Rollator',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		tinettiScore: 23,
		tugTime: 11,
		fallRisk: 'Moderate fall risk',
		assistiveDevice: 'Orthotics',
	},
];
