//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "ottawa_knee_rules")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub patient_identifier: String,
    pub assessed_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    pub injury_mechanism: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub hours_since_injury: Option<f64>,
    pub sex: String,
    pub injured_side: String,
    pub age_years: Option<i32>,
    pub patellar_tenderness: String,
    pub other_bony_tenderness: String,
    pub fibular_head_tenderness: String,
    pub unable_to_flex_90: String,
    pub unable_to_bear_weight: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_notes: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::ottawa_knee_rule_grades::Entity")]
    OttawaKneeRuleGrades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::ottawa_knee_rule_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OttawaKneeRuleGrades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
