//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "ottawa_knee_rule_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub xray_indicated: String,
    pub decision: String,
    #[sea_orm(column_type = "Text")]
    pub recommended_action: String,
    pub graded_at: DateTimeWithTimeZone,
    pub ottawa_knee_rule_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ottawa_knee_rule_grade_flags::Entity")]
    OttawaKneeRuleGradeFlags,
    #[sea_orm(has_many = "super::ottawa_knee_rule_grade_rules::Entity")]
    OttawaKneeRuleGradeRules,
    #[sea_orm(
        belongs_to = "super::ottawa_knee_rules::Entity",
        from = "Column::OttawaKneeRuleId",
        to = "super::ottawa_knee_rules::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    OttawaKneeRules,
}

impl Related<super::ottawa_knee_rule_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OttawaKneeRuleGradeFlags.def()
    }
}

impl Related<super::ottawa_knee_rule_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OttawaKneeRuleGradeRules.def()
    }
}

impl Related<super::ottawa_knee_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OttawaKneeRules.def()
    }
}
