//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Model.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "cardiology_request_grade_flags")]
pub struct Model {
    /// Created at.
    pub created_at: DateTimeWithTimeZone,
    /// Updated at.
    pub updated_at: DateTimeWithTimeZone,
    /// ID.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// Deleted at.
    pub deleted_at: Option<DateTimeWithTimeZone>,
    /// Flag ID.
    pub flag_id: String,
    /// Category.
    pub category: String,
    /// Priority.
    pub priority: String,
    /// Description.
    pub description: String,
    /// Suggested action.
    pub suggested_action: String,
    /// Cardiology request grade ID.
    pub cardiology_request_grade_id: Uuid,
}

/// Relation.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cardiology_request_grades::Entity",
        from = "Column::CardiologyRequestGradeId",
        to = "super::cardiology_request_grades::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Cardiology request grades.
    CardiologyRequestGrades,
}

impl Related<super::cardiology_request_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardiologyRequestGrades.def()
    }
}
