//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Model.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "clinicians")]
pub struct Model {
    /// Created at.
    pub created_at: DateTimeWithTimeZone,
    /// Updated at.
    pub updated_at: DateTimeWithTimeZone,
    /// ID.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// Deleted at.
    pub deleted_at: Option<DateTimeWithTimeZone>,
    /// Name.
    #[sea_orm(column_type = "Text")]
    pub name: String,
    /// Email.
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    /// Phone.
    #[sea_orm(column_type = "Text", nullable)]
    pub phone: Option<String>,
    /// Postal address as full text.
    #[sea_orm(column_type = "Text", nullable)]
    pub postal_address_as_full_text: Option<String>,
    /// Country as iso 3166 1 alpha 2.
    pub country_as_iso_3166_1_alpha_2: Option<String>,
    /// Postcode.
    #[sea_orm(column_type = "Text", nullable)]
    pub postcode: Option<String>,
    /// Role.
    #[sea_orm(column_type = "Text")]
    pub role: String,
    /// Registration body.
    #[sea_orm(column_type = "Text")]
    pub registration_body: String,
    /// Registration number.
    #[sea_orm(column_type = "Text")]
    pub registration_number: String,
    /// United kingdom NHS number.
    #[sea_orm(unique)]
    pub united_kingdom_nhs_number: String,
}

/// Relation.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Cardiology requests.
    #[sea_orm(has_many = "super::cardiology_requests::Entity")]
    CardiologyRequests,
}

impl Related<super::cardiology_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardiologyRequests.def()
    }
}
