//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "glasgow_coma_scale_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub eye_score: Option<i32>,
    pub verbal_score: Option<i32>,
    pub motor_score: Option<i32>,
    pub total_score: Option<i32>,
    pub breakdown: String,
    pub total_display: String,
    pub severity_band: String,
    pub pupil_reactivity_score: Option<i32>,
    pub gcs_p: Option<i32>,
    pub graded_at: DateTimeWithTimeZone,
    pub glasgow_coma_scale_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::glasgow_coma_scale_grade_flags::Entity")]
    GlasgowComaScaleGradeFlags,
    #[sea_orm(has_many = "super::glasgow_coma_scale_grade_rules::Entity")]
    GlasgowComaScaleGradeRules,
    #[sea_orm(
        belongs_to = "super::glasgow_coma_scales::Entity",
        from = "Column::GlasgowComaScaleId",
        to = "super::glasgow_coma_scales::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    GlasgowComaScales,
}

impl Related<super::glasgow_coma_scale_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlasgowComaScaleGradeFlags.def()
    }
}

impl Related<super::glasgow_coma_scale_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlasgowComaScaleGradeRules.def()
    }
}

impl Related<super::glasgow_coma_scales::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlasgowComaScales.def()
    }
}
