-- ============================================================
-- 02_assessment.sql
-- A single pre-operative assessment visit.
-- ============================================================
-- Each assessment belongs to one patient and captures the
-- clinical snapshot at the time of the surgical episode.
-- Subsystem details are stored in 1:1 child tables (03-18).
-- ============================================================

CREATE TABLE assessment (
    -- Primary key: UUIDv4 generated by the database
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign key to the patient this assessment belongs to
    patient_id          UUID NOT NULL REFERENCES patient(id) ON DELETE CASCADE,

    -- Assessment-level fields from Demographics interface
    weight              NUMERIC(5,1)    CHECK (weight IS NULL OR weight > 0),
    height              NUMERIC(5,1)    CHECK (height IS NULL OR height > 0),
    bmi                 NUMERIC(4,1)    CHECK (bmi IS NULL OR (bmi >= 10 AND bmi <= 100)),

    -- Planned procedure details
    planned_procedure   TEXT NOT NULL DEFAULT '',
    procedure_urgency   TEXT NOT NULL DEFAULT ''
                        CHECK (procedure_urgency IN ('elective', 'urgent', 'emergency', '')),

    -- Assessment status tracking
    status              TEXT NOT NULL DEFAULT 'in_progress'
                        CHECK (status IN ('in_progress', 'completed', 'reviewed')),

    -- Audit timestamps
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for the most common query: all assessments for a patient
CREATE INDEX idx_assessment_patient_id ON assessment(patient_id);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_assessment_updated_at
    BEFORE UPDATE ON assessment
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE assessment IS
    'A single pre-operative assessment visit. Child tables hold system-specific clinical data.';
COMMENT ON COLUMN assessment.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN assessment.patient_id IS
    'FK to patient. One patient may have many assessments.';
COMMENT ON COLUMN assessment.weight IS
    'Weight in kilograms at time of assessment. NULL if not recorded.';
COMMENT ON COLUMN assessment.height IS
    'Height in centimetres at time of assessment. NULL if not recorded.';
COMMENT ON COLUMN assessment.bmi IS
    'Body Mass Index, computed from weight and height. Range 10-100. NULL if not computable.';
COMMENT ON COLUMN assessment.planned_procedure IS
    'Free-text description of the planned surgical procedure.';
COMMENT ON COLUMN assessment.procedure_urgency IS
    'Urgency classification: elective, urgent, emergency, or empty string if unanswered.';
COMMENT ON COLUMN assessment.status IS
    'Workflow status: in_progress (patient filling in), completed (submitted), reviewed (clinician signed off).';
COMMENT ON COLUMN assessment.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN assessment.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
