//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "partogram_observations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub observed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Double", nullable)]
    pub cervical_dilatation_cm: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub descent_fifths: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub contractions_per_10_min: Option<f64>,
    pub contraction_duration_band: String,
    pub contraction_strength: String,
    pub fetal_heart_rate: Option<i32>,
    pub liquor_state: String,
    pub moulding: String,
    pub systolic_blood_pressure: Option<i32>,
    pub diastolic_blood_pressure: Option<i32>,
    pub pulse: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub temperature: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub urine_volume_ml: Option<f64>,
    pub urine_protein: String,
    pub urine_ketones: String,
    pub urine_glucose: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub oxytocin_rate: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub drugs_and_fluids: String,
    pub partogram_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::partograms::Entity",
        from = "Column::PartogramId",
        to = "super::partograms::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Partograms,
}

impl Related<super::partograms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Partograms.def()
    }
}
