#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding urology-assessment (15 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    ethnicity:string! \
    occupation:string! \
    referring_physician:string! \
    referral_date:date \
    smoking_status:string! \
    alcohol_use:string! \
    --htmx

cargo loco generate scaffold assessment_chief_complaint \
    assessment:references \
    primary_complaint:text! \
    symptom_onset_date:date \
    symptom_duration_weeks:int \
    symptom_progression:string! \
    previous_urological_evaluation:string! \
    previous_evaluation_details:text! \
    impact_on_quality_of_life:string! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold assessment_ipss_questionnaire \
    assessment:references \
    ipss_q1_incomplete_emptying:int \
    ipss_q2_frequency:int \
    ipss_q3_intermittency:int \
    ipss_q4_urgency:int \
    ipss_q5_weak_stream:int \
    ipss_q6_straining:int \
    ipss_q7_nocturia:int \
    --htmx

cargo loco generate scaffold assessment_quality_of_life \
    assessment:references \
    ipss_qol_score:int \
    sleep_disruption_from_nocturia:string! \
    social_activity_limitation:string! \
    anxiety_about_symptoms:string! \
    embarrassment_from_symptoms:string! \
    travel_restriction:string! \
    fluid_intake_restriction:string! \
    overall_wellbeing:string! \
    --htmx

cargo loco generate scaffold assessment_urinary_symptoms \
    assessment:references \
    urinary_frequency_daytime:int \
    urgency:string! \
    urge_incontinence:string! \
    stress_incontinence:string! \
    pad_use:string! \
    pads_per_day:int \
    hesitancy:string! \
    poor_stream:string! \
    terminal_dribbling:string! \
    post_void_dribbling:string! \
    feeling_of_incomplete_emptying:string! \
    urinary_retention_history:string! \
    haematuria:string! \
    haematuria_type:string! \
    dysuria:string! \
    suprapubic_pain:string! \
    loin_pain:string! \
    recurrent_utis:string! \
    uti_frequency_per_year:int \
    --htmx

cargo loco generate scaffold assessment_renal_function \
    assessment:references \
    creatinine_umol_l:double \
    egfr_ml_min:double \
    urea_mmol_l:double \
    psa_ng_ml:double \
    psa_previous_value:double \
    psa_previous_date:date \
    urinalysis_performed:string! \
    urinalysis_leukocytes:string! \
    urinalysis_nitrites:string! \
    urinalysis_blood:string! \
    urinalysis_protein:string! \
    post_void_residual_ml:int \
    uroflowmetry_performed:string! \
    max_flow_rate_ml_s:double \
    ultrasound_performed:string! \
    ultrasound_findings:text! \
    prostate_volume_ml:double \
    lab_date:date \
    --htmx

cargo loco generate scaffold assessment_sexual_health \
    assessment:references \
    sexually_active:string! \
    erectile_dysfunction:string! \
    erectile_dysfunction_severity:string! \
    erectile_dysfunction_duration_months:int \
    iief5_score:int \
    ejaculatory_dysfunction:string! \
    ejaculatory_dysfunction_type:string! \
    decreased_libido:string! \
    testosterone_level_nmol_l:double \
    pde5_inhibitor_use:string! \
    pde5_inhibitor_name:text! \
    fertility_concerns:string! \
    fertility_details:text! \
    --htmx

cargo loco generate scaffold assessment_medical_history \
    assessment:references \
    previous_urological_surgery:string! \
    urological_surgery_details:text! \
    benign_prostatic_hyperplasia:string! \
    prostate_cancer_history:string! \
    prostate_cancer_details:text! \
    bladder_cancer_history:string! \
    kidney_stones_history:string! \
    kidney_stones_details:text! \
    catheterisation_history:string! \
    diabetes:string! \
    hypertension:string! \
    cardiovascular_disease:string! \
    neurological_disease:string! \
    neurological_disease_details:text! \
    chronic_kidney_disease:string! \
    previous_pelvic_surgery:string! \
    pelvic_surgery_details:text! \
    previous_radiotherapy:string! \
    radiotherapy_details:text! \
    --htmx

cargo loco generate scaffold assessment_current_medications \
    assessment:references \
    alpha_blocker_use:string! \
    alpha_blocker_name:text! \
    five_alpha_reductase_inhibitor:string! \
    five_ari_name:text! \
    anticholinergic_use:string! \
    anticholinergic_name:text! \
    beta3_agonist_use:string! \
    beta3_agonist_name:text! \
    pde5_inhibitor_use:string! \
    diuretic_use:string! \
    diuretic_name:text! \
    antihypertensive_use:string! \
    antihypertensive_details:text! \
    anticoagulant_use:string! \
    anticoagulant_name:text! \
    other_medications:text! \
    known_drug_allergies:text! \
    --htmx

cargo loco generate scaffold assessment_family_history \
    assessment:references \
    family_history_prostate_cancer:string! \
    prostate_cancer_relationship:text! \
    prostate_cancer_age_at_diagnosis:int \
    family_history_bladder_cancer:string! \
    family_history_kidney_cancer:string! \
    family_history_kidney_stones:string! \
    family_history_bph:string! \
    family_history_brca_mutation:string! \
    family_history_breast_cancer:string! \
    additional_family_history:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    ipss_total_score:int \
    ipss_qol_score:int \
    symptom_severity:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
