import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		asrsScore: 52,
		classification: 'highly-likely',
		subtype: 'combined',
		comorbidities: 'Anxiety, Depression',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		asrsScore: 34,
		classification: 'likely',
		subtype: 'inattentive',
		comorbidities: 'None',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		asrsScore: 18,
		classification: 'unlikely',
		subtype: 'unspecified',
		comorbidities: 'Sleep disorder',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		asrsScore: 42,
		classification: 'likely',
		subtype: 'hyperactive-impulsive',
		comorbidities: 'Substance use',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		asrsScore: 58,
		classification: 'highly-likely',
		subtype: 'combined',
		comorbidities: 'Anxiety, ASD',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		asrsScore: 12,
		classification: 'unlikely',
		subtype: 'unspecified',
		comorbidities: 'None',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		asrsScore: 26,
		classification: 'possible',
		subtype: 'inattentive',
		comorbidities: 'Depression',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		asrsScore: 38,
		classification: 'likely',
		subtype: 'combined',
		comorbidities: 'None',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		asrsScore: 48,
		classification: 'highly-likely',
		subtype: 'inattentive',
		comorbidities: 'Anxiety, Learning disability',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		asrsScore: 22,
		classification: 'possible',
		subtype: 'hyperactive-impulsive',
		comorbidities: 'None',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		asrsScore: 30,
		classification: 'likely',
		subtype: 'inattentive',
		comorbidities: 'Anxiety',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		asrsScore: 56,
		classification: 'highly-likely',
		subtype: 'combined',
		comorbidities: 'Depression, Substance use',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		asrsScore: 15,
		classification: 'unlikely',
		subtype: 'unspecified',
		comorbidities: 'None',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		asrsScore: 44,
		classification: 'likely',
		subtype: 'combined',
		comorbidities: 'Sleep disorder',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		asrsScore: 24,
		classification: 'possible',
		subtype: 'inattentive',
		comorbidities: 'ASD',
	},
];
