#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding dermatology-assessment (14 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    full_name:string! \
    date_of_birth:date \
    nhs_number:string! \
    address:text! \
    telephone:string! \
    email:string! \
    gp_name:string! \
    gp_practice:string! \
    --htmx

cargo loco generate scaffold assessment_chief_complaint \
    assessment:references \
    chief_complaint:text! \
    onset_date:date \
    duration:string! \
    body_area_affected:text! \
    symptom_progression:string! \
    pruritus:string! \
    pruritus_severity:string! \
    pain:string! \
    bleeding:string! \
    previous_treatment:text! \
    previous_treatment_response:string! \
    --htmx

cargo loco generate scaffold assessment_dlqi_questionnaire \
    assessment:references \
    q1_symptoms:int \
    q2_embarrassment:int \
    q3_daily_activities:int \
    q4_clothing:int \
    q5_social_leisure:int \
    q6_sport:int \
    q7_work_study:int \
    q8_relationships:int \
    q9_sexual:int \
    q10_treatment:int \
    dlqi_total:int \
    --htmx

cargo loco generate scaffold assessment_lesion_characteristics \
    assessment:references \
    lesion_type:string! \
    lesion_type_other:text! \
    lesion_colour:string! \
    lesion_shape:string! \
    lesion_border:string! \
    lesion_surface:string! \
    lesion_distribution:string! \
    lesion_size_mm:double \
    number_of_lesions:string! \
    body_site:text! \
    dermoscopy_performed:string! \
    dermoscopy_findings:text! \
    photography_taken:string! \
    clinical_notes:text! \
    --htmx

cargo loco generate scaffold assessment_medical_history \
    assessment:references \
    has_eczema:string! \
    eczema_details:text! \
    has_psoriasis:string! \
    psoriasis_details:text! \
    has_acne:string! \
    acne_details:text! \
    has_skin_cancer_history:string! \
    skin_cancer_details:text! \
    has_autoimmune_condition:string! \
    autoimmune_details:text! \
    has_diabetes:string! \
    has_thyroid_disease:string! \
    has_immunosuppression:string! \
    immunosuppression_details:text! \
    previous_skin_biopsies:string! \
    biopsy_details:text! \
    previous_dermatological_procedures:text! \
    other_conditions:text! \
    --htmx

cargo loco generate scaffold assessment_current_medications \
    assessment:references \
    takes_topical_steroids:string! \
    topical_steroid_name:string! \
    topical_steroid_potency:string! \
    takes_systemic_immunosuppressants:string! \
    immunosuppressant_name:string! \
    takes_biologics:string! \
    biologic_name:string! \
    takes_retinoids:string! \
    retinoid_name:string! \
    takes_antibiotics:string! \
    antibiotic_name:string! \
    takes_antihistamines:string! \
    antihistamine_name:string! \
    uses_emollients:string! \
    emollient_name:string! \
    phototherapy_history:string! \
    phototherapy_details:text! \
    other_medications:text! \
    --htmx

cargo loco generate scaffold assessment_allergies \
    assessment:references \
    has_drug_allergies:string! \
    drug_allergy_details:text! \
    has_contact_allergies:string! \
    contact_allergy_details:text! \
    patch_testing_performed:string! \
    patch_testing_results:text! \
    has_latex_allergy:string! \
    has_nickel_allergy:string! \
    has_fragrance_allergy:string! \
    has_preservative_allergy:string! \
    has_cosmetic_sensitivities:string! \
    cosmetic_sensitivity_details:text! \
    has_food_allergies:string! \
    food_allergy_details:text! \
    other_allergies:text! \
    --htmx

cargo loco generate scaffold assessment_family_history \
    assessment:references \
    family_eczema:string! \
    family_eczema_relationship:string! \
    family_psoriasis:string! \
    family_psoriasis_relationship:string! \
    family_skin_cancer:string! \
    family_skin_cancer_type:string! \
    family_skin_cancer_relationship:string! \
    family_autoimmune:string! \
    family_autoimmune_details:text! \
    family_atopy:string! \
    family_atopy_details:text! \
    family_alopecia:string! \
    family_vitiligo:string! \
    other_family_skin_conditions:text! \
    --htmx

cargo loco generate scaffold assessment_social_history \
    assessment:references \
    occupation:string! \
    occupational_skin_exposure:string! \
    occupational_exposure_details:text! \
    sun_exposure_level:string! \
    sunscreen_use:string! \
    history_of_sunburn:string! \
    sunburn_frequency:string! \
    sunbed_use:string! \
    skin_type:string! \
    tobacco_use:string! \
    alcohol_use:string! \
    stress_level:string! \
    psychological_impact:text! \
    hobbies_affecting_skin:text! \
    additional_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    dlqi_score:int! \
    impact_level:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
