//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "issue_trackers")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub reported_at: DateTimeWithTimeZone,
    pub discovered_at: Option<DateTimeWithTimeZone>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub resolved_at: Option<DateTimeWithTimeZone>,
    pub issue_category: String,
    pub environment: String,
    pub system_name: String,
    pub component: String,
    pub customer_or_project_tag: String,
    pub external_reference: String,
    pub cc_summary: String,
    #[sea_orm(column_type = "Text")]
    pub cc_long_description: String,
    pub cc_reported_by_name: String,
    pub cc_reported_via: String,
    pub pt_discoverer_name: String,
    pub pt_affected_users_count: Option<i32>,
    pub pt_affected_user_groups: String,
    pub pt_assignees: String,
    pub pt_stakeholders_to_inform: String,
    pub pt_observers: String,
    #[sea_orm(column_type = "Text")]
    pub sx_external_signals: String,
    pub sx_alert_ids: String,
    #[sea_orm(column_type = "Text")]
    pub sx_error_messages: String,
    pub sx_screenshots_url: String,
    pub sx_logs_url: String,
    pub sx_first_observed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub fx_broken_components: String,
    pub fx_failed_services: String,
    pub fx_stuck_processes: String,
    pub fx_hardware_faults: String,
    pub fx_data_corruption: String,
    pub hx_related_issues: String,
    pub hx_prior_occurrences: Option<i32>,
    pub hx_recent_change_url: String,
    #[sea_orm(column_type = "Text")]
    pub hx_references: String,
    #[sea_orm(column_type = "Text")]
    pub hx_timeline: String,
    #[sea_orm(column_type = "Text")]
    pub ix_hypotheses: String,
    #[sea_orm(column_type = "Text")]
    pub ix_repro_steps: String,
    #[sea_orm(column_type = "Text")]
    pub ix_diagnostic_queries: String,
    pub ix_tests_run: String,
    #[sea_orm(column_type = "Text")]
    pub ix_blocking_unknowns: String,
    #[sea_orm(column_type = "Text")]
    pub dx_root_cause: String,
    #[sea_orm(column_type = "Text")]
    pub dx_contributing_causes: String,
    pub dx_scope: String,
    pub dx_confirmed: String,
    #[sea_orm(column_type = "Text")]
    pub tx_mitigation_steps: String,
    #[sea_orm(column_type = "Text")]
    pub tx_fix_plan: String,
    #[sea_orm(column_type = "Text")]
    pub tx_workaround: String,
    #[sea_orm(column_type = "Text")]
    pub tx_rollback_plan: String,
    pub tx_communication_plan: String,
    pub px_expected_resolution_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub px_residual_risk: String,
    #[sea_orm(column_type = "Text")]
    pub px_monitoring_plan: String,
    pub px_recurrence_likelihood: String,
    #[sea_orm(column_type = "Text")]
    pub px_lessons_learned: String,
    pub score_by_priority_rank: Option<i32>,
    pub score_by_severity_of_impact: Option<i32>,
    pub score_by_magnitude_of_damage: Option<i32>,
    pub score_by_harm_grade: Option<i32>,
    pub score_by_failure_condition: String,
    pub score_by_moscow_requirement: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub score_by_frequency_percent: Option<f64>,
    pub reporter_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::issue_tracker_grades::Entity")]
    IssueTrackerGrades,
    #[sea_orm(
        belongs_to = "super::reporters::Entity",
        from = "Column::ReporterId",
        to = "super::reporters::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Reporters,
}

impl Related<super::issue_tracker_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueTrackerGrades.def()
    }
}

impl Related<super::reporters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reporters.def()
    }
}
