import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, Jane',
		mrsScore: 22,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Favourable',
		currentHRT: 'None',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		mrsScore: 15,
		menopauseStatus: 'Peri-menopausal',
		riskClassification: 'Favourable',
		currentHRT: 'Estradiol patch 50mcg',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		mrsScore: 31,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Cautious',
		currentHRT: 'None',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, Sarah',
		mrsScore: 8,
		menopauseStatus: 'Peri-menopausal',
		riskClassification: 'Favourable',
		currentHRT: 'Conjugated oestrogens 0.625mg',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Elizabeth',
		mrsScore: 28,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Contraindicated',
		currentHRT: 'Discontinued',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, Helen',
		mrsScore: 4,
		menopauseStatus: 'Pre-menopausal',
		riskClassification: 'Favourable',
		currentHRT: 'None',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Susan',
		mrsScore: 19,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Acceptable',
		currentHRT: 'Estradiol gel 0.06%',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Patricia',
		mrsScore: 12,
		menopauseStatus: 'Peri-menopausal',
		riskClassification: 'Favourable',
		currentHRT: 'None',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		mrsScore: 35,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Cautious',
		currentHRT: 'Tibolone 2.5mg',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Mary',
		mrsScore: 6,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Favourable',
		currentHRT: 'Vaginal oestrogen only',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		mrsScore: 24,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Acceptable',
		currentHRT: 'Sequential combined HRT',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, Dorothy',
		mrsScore: 38,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Contraindicated',
		currentHRT: 'None',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Linda',
		mrsScore: 11,
		menopauseStatus: 'Peri-menopausal',
		riskClassification: 'Favourable',
		currentHRT: 'Continuous combined HRT',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Barbara',
		mrsScore: 17,
		menopauseStatus: 'Post-menopausal',
		riskClassification: 'Cautious',
		currentHRT: 'Estradiol patch 25mcg',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Ann',
		mrsScore: 3,
		menopauseStatus: 'Pre-menopausal',
		riskClassification: 'Favourable',
		currentHRT: 'None',
	},
];
