//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "medication_reconciliations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub reconciliation_type: String,
    pub care_setting: String,
    pub reconciled_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub clinician_name: String,
    pub clinician_role: String,
    #[sea_orm(column_type = "Text")]
    pub patient_identifier: String,
    pub age_band: String,
    pub sex: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight_kg: Option<f64>,
    pub allergy_status: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::medication_reconciliation_allergies::Entity")]
    MedicationReconciliationAllergies,
    #[sea_orm(has_many = "super::medication_reconciliation_discrepancies::Entity")]
    MedicationReconciliationDiscrepancies,
    #[sea_orm(has_many = "super::medication_reconciliation_grades::Entity")]
    MedicationReconciliationGrades,
    #[sea_orm(has_many = "super::medication_reconciliation_information_sources::Entity")]
    MedicationReconciliationInformationSources,
    #[sea_orm(has_many = "super::medication_reconciliation_line_items::Entity")]
    MedicationReconciliationLineItems,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::medication_reconciliation_allergies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicationReconciliationAllergies.def()
    }
}

impl Related<super::medication_reconciliation_discrepancies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicationReconciliationDiscrepancies.def()
    }
}

impl Related<super::medication_reconciliation_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicationReconciliationGrades.def()
    }
}

impl Related<super::medication_reconciliation_information_sources::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicationReconciliationInformationSources.def()
    }
}

impl Related<super::medication_reconciliation_line_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicationReconciliationLineItems.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
