-- ============================================================
-- 03_assessment_demographics.sql
-- Demographics subsection (1:1 with assessment).
-- ============================================================
-- Stores assessment-time demographic data that supplements
-- the static identity in the patient table. Corresponds to
-- the Demographics TypeScript interface minus fields already
-- on the assessment table (weight, height, bmi, procedure).
-- ============================================================

CREATE TABLE assessment_demographics (
    -- Primary key: UUIDv4 generated by the database
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- 1:1 relationship with assessment (UNIQUE constraint)
    assessment_id   UUID NOT NULL UNIQUE REFERENCES assessment(id) ON DELETE CASCADE,

    -- Note: first_name, last_name, date_of_birth, sex live on patient table.
    -- Note: weight, height, bmi, planned_procedure, procedure_urgency live on assessment table.
    -- This table exists for extensibility; additional demographic
    -- fields collected at assessment time can be added here.

    -- Audit timestamps
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_assessment_demographics_updated_at
    BEFORE UPDATE ON assessment_demographics
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE assessment_demographics IS
    '1:1 with assessment. Holds assessment-time demographic data beyond what is on the patient and assessment tables.';
COMMENT ON COLUMN assessment_demographics.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN assessment_demographics.assessment_id IS
    'FK to assessment (UNIQUE = 1:1 relationship).';
COMMENT ON COLUMN assessment_demographics.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN assessment_demographics.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
