-- ============================================================
-- 01_patient.sql
-- Root entity: a unique individual in the system.
-- ============================================================
-- A patient can have many ergonomic assessments over time
-- (e.g. for different workstations or periodic reviews).
-- Identity data lives here; clinical data lives in
-- the assessment tables.
-- ============================================================

CREATE TABLE patient (
    -- Primary key: UUIDv4 generated by the database
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Patient identity
    first_name      TEXT NOT NULL,
    last_name       TEXT NOT NULL,
    date_of_birth   DATE NOT NULL,

    -- Biological sex
    sex             TEXT NOT NULL DEFAULT ''
                    CHECK (sex IN ('male', 'female', 'other', '')),

    -- Occupational identity
    occupation      TEXT NOT NULL DEFAULT '',
    employer        TEXT NOT NULL DEFAULT '',
    job_title       TEXT NOT NULL DEFAULT '',
    years_in_role   INTEGER CHECK (years_in_role IS NULL OR (years_in_role >= 0 AND years_in_role <= 60)),

    -- Audit timestamps
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at on every row change
CREATE TRIGGER trg_patient_updated_at
    BEFORE UPDATE ON patient
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE patient IS
    'Root entity representing a unique individual. Identity and occupational data; clinical data is per-assessment.';
COMMENT ON COLUMN patient.id IS
    'UUIDv4 primary key, auto-generated.';
COMMENT ON COLUMN patient.first_name IS
    'Patient given name.';
COMMENT ON COLUMN patient.last_name IS
    'Patient family name.';
COMMENT ON COLUMN patient.date_of_birth IS
    'Date of birth, used for age-based evaluation.';
COMMENT ON COLUMN patient.sex IS
    'Biological sex: male, female, other, or empty string if unanswered.';
COMMENT ON COLUMN patient.occupation IS
    'Patient current occupation.';
COMMENT ON COLUMN patient.employer IS
    'Name of employer or organisation.';
COMMENT ON COLUMN patient.job_title IS
    'Specific job title within the organisation.';
COMMENT ON COLUMN patient.years_in_role IS
    'Number of years in the current role. NULL if not provided.';
COMMENT ON COLUMN patient.created_at IS
    'Row creation timestamp.';
COMMENT ON COLUMN patient.updated_at IS
    'Last modification timestamp, auto-updated by trigger.';
