//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "structured_medication_review_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub review_status: String,
    pub anticholinergic_burden_score: i32,
    pub anticholinergic_band: String,
    pub polypharmacy_band: String,
    pub burden_band: String,
    pub medicine_count: i32,
    pub regular_medicine_count: i32,
    pub graded_at: DateTimeWithTimeZone,
    pub structured_medication_review_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::structured_medication_review_grade_flags::Entity")]
    StructuredMedicationReviewGradeFlags,
    #[sea_orm(has_many = "super::structured_medication_review_grade_rules::Entity")]
    StructuredMedicationReviewGradeRules,
    #[sea_orm(
        belongs_to = "super::structured_medication_reviews::Entity",
        from = "Column::StructuredMedicationReviewId",
        to = "super::structured_medication_reviews::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    StructuredMedicationReviews,
}

impl Related<super::structured_medication_review_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StructuredMedicationReviewGradeFlags.def()
    }
}

impl Related<super::structured_medication_review_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StructuredMedicationReviewGradeRules.def()
    }
}

impl Related<super::structured_medication_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StructuredMedicationReviews.def()
    }
}
