//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "structured_medication_reviews")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub clinician_name: String,
    pub clinician_role: String,
    pub reviewed_at: Option<DateTimeWithTimeZone>,
    pub care_setting: String,
    pub consultation_mode: String,
    #[sea_orm(column_type = "Text")]
    pub patient_identifier: String,
    pub age_band: String,
    pub sex: String,
    pub frailty_status: String,
    pub lives_in_care_home: String,
    #[sea_orm(column_type = "Text")]
    pub long_term_conditions: String,
    #[sea_orm(column_type = "Text")]
    pub presenting_problems: String,
    #[sea_orm(column_type = "Text")]
    pub patient_reported_issues: String,
    #[sea_orm(column_type = "Text")]
    pub what_matters_to_patient: String,
    #[sea_orm(column_type = "Text")]
    pub shared_decisions: String,
    #[sea_orm(column_type = "Text")]
    pub monitoring_due: String,
    pub overdue_monitoring_count: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub follow_up_plan: String,
    pub follow_up_date: Option<Date>,
    pub review_completed: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::structured_medication_review_grades::Entity")]
    StructuredMedicationReviewGrades,
    #[sea_orm(has_many = "super::structured_medication_review_medicines::Entity")]
    StructuredMedicationReviewMedicines,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::structured_medication_review_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StructuredMedicationReviewGrades.def()
    }
}

impl Related<super::structured_medication_review_medicines::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StructuredMedicationReviewMedicines.def()
    }
}
