//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "assessments")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub age_of_onset: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub known_allergens: String,
    pub family_history_of_atopy: String,
    #[sea_orm(column_type = "Text")]
    pub family_atopy_details: String,
    pub family_history_of_allergy: String,
    #[sea_orm(column_type = "Text")]
    pub family_allergy_details: String,
    pub pollen_allergy: String,
    pub dust_mite_allergy: String,
    pub mould_allergy: String,
    pub animal_dander_allergy: String,
    pub latex_allergy: String,
    pub insect_sting_allergy: String,
    pub insect_sting_severity: String,
    pub seasonal_pattern: String,
    #[sea_orm(column_type = "Text")]
    pub other_environmental_allergens: String,
    pub asthma: String,
    pub asthma_severity: String,
    pub eczema: String,
    pub eczema_severity: String,
    pub rhinitis: String,
    pub rhinitis_severity: String,
    pub eosinophilic_oesophagitis: String,
    pub mast_cell_disorders: String,
    #[sea_orm(column_type = "Text")]
    pub mast_cell_details: String,
    pub mental_health_impact: String,
    #[sea_orm(column_type = "Text")]
    pub mental_health_details: String,
    pub quality_of_life_score: Option<i32>,
    pub school_work_impact: String,
    #[sea_orm(column_type = "Text")]
    pub school_work_impact_details: String,
    pub emergency_action_plan_status: String,
    pub training_provided: String,
    #[sea_orm(column_type = "Text")]
    pub training_details: String,
    #[sea_orm(column_type = "Text")]
    pub follow_up_schedule: String,
    pub patient_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assessment_drug_allergies::Entity")]
    AssessmentDrugAllergies,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::assessment_drug_allergies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssessmentDrugAllergies.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
