import type { PrescriptionRow } from './types.ts';

/** Sample prescription request data for the clinician dashboard */
export const prescriptions: PrescriptionRow[] = [
  {
    id: '1',
    nhsNumber: '943 476 5919',
    patientName: 'Doe, Jane',
    clinicianName: 'Dr Smith',
    medicationName: 'Amoxicillin',
    dosage: '500mg TDS',
    requestType: 'New',
    priorityLevel: 'routine',
    requestDate: '2026-04-15',
    status: 'submitted',
  },
  {
    id: '2',
    nhsNumber: '721 938 4102',
    patientName: 'Patel, Priya',
    clinicianName: 'Dr Jones',
    medicationName: 'Metformin',
    dosage: '500mg BD',
    requestType: 'Refill',
    priorityLevel: 'routine',
    requestDate: '2026-04-14',
    status: 'approved',
  },
  {
    id: '3',
    nhsNumber: '384 615 7230',
    patientName: 'Jones, Margaret',
    clinicianName: 'Dr Williams',
    medicationName: 'Salbutamol Inhaler',
    dosage: '100mcg PRN',
    requestType: 'New',
    priorityLevel: 'emergency',
    requestDate: '2026-04-15',
    status: 'submitted',
  },
  {
    id: '4',
    nhsNumber: '512 847 9063',
    patientName: 'Williams, David',
    clinicianName: 'Dr Smith',
    medicationName: 'Ramipril',
    dosage: '10mg OD',
    requestType: 'Refill',
    priorityLevel: 'routine',
    requestDate: '2026-04-13',
    status: 'approved',
  },
  {
    id: '5',
    nhsNumber: '167 293 8451',
    patientName: 'Brown, Sarah',
    clinicianName: 'Dr Taylor',
    medicationName: 'Insulin Glargine',
    dosage: '20 units OD',
    requestType: 'Refill',
    priorityLevel: 'urgent',
    requestDate: '2026-04-15',
    status: 'submitted',
  },
  {
    id: '6',
    nhsNumber: '835 162 4097',
    patientName: 'Taylor, James',
    clinicianName: 'Dr Smith',
    medicationName: 'Omeprazole',
    dosage: '20mg OD',
    requestType: 'New',
    priorityLevel: 'routine',
    requestDate: '2026-04-12',
    status: 'reviewed',
  },
  {
    id: '7',
    nhsNumber: '294 708 5316',
    patientName: 'Davies, Helen',
    clinicianName: 'Dr Jones',
    medicationName: 'Sertraline',
    dosage: '50mg OD',
    requestType: 'New',
    priorityLevel: 'urgent',
    requestDate: '2026-04-14',
    status: 'submitted',
  },
  {
    id: '8',
    nhsNumber: '608 341 2975',
    patientName: 'Wilson, Robert',
    clinicianName: 'Dr Williams',
    medicationName: 'Amlodipine',
    dosage: '5mg OD',
    requestType: 'Refill',
    priorityLevel: 'routine',
    requestDate: '2026-04-11',
    status: 'approved',
  },
  {
    id: '9',
    nhsNumber: '473 926 1084',
    patientName: 'Evans, Catherine',
    clinicianName: 'Dr Taylor',
    medicationName: 'EpiPen',
    dosage: '0.3mg PRN',
    requestType: 'New',
    priorityLevel: 'emergency',
    requestDate: '2026-04-15',
    status: 'submitted',
  },
  {
    id: '10',
    nhsNumber: '159 684 7302',
    patientName: 'Thomas, Michael',
    clinicianName: 'Dr Smith',
    medicationName: 'Atorvastatin',
    dosage: '20mg OD',
    requestType: 'Refill',
    priorityLevel: 'routine',
    requestDate: '2026-04-10',
    status: 'approved',
  },
  {
    id: '11',
    nhsNumber: '742 051 3896',
    patientName: 'Robinson, Emma',
    clinicianName: 'Dr Jones',
    medicationName: 'Fluoxetine',
    dosage: '20mg OD',
    requestType: 'New',
    priorityLevel: 'urgent',
    requestDate: '2026-04-14',
    status: 'reviewed',
  },
  {
    id: '12',
    nhsNumber: '386 219 5740',
    patientName: 'Clark, George',
    clinicianName: 'Dr Williams',
    medicationName: 'GTN Spray',
    dosage: '400mcg PRN',
    requestType: 'New',
    priorityLevel: 'emergency',
    requestDate: '2026-04-15',
    status: 'submitted',
  },
];
