//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "access_schedulings")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub ease_of_scheduling: Option<i32>,
    pub wait_for_appointment: Option<i32>,
    pub wait_in_waiting_room: Option<i32>,
    pub encounter_satisfaction_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::encounter_satisfactions::Entity",
        from = "Column::EncounterSatisfactionId",
        to = "super::encounter_satisfactions::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    EncounterSatisfactions,
}

impl Related<super::encounter_satisfactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EncounterSatisfactions.def()
    }
}
