import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, John',
		riskLevel: 'Low',
		referralReason: 'Routine carrier screening',
		testingStatus: 'Complete',
		counselingStatus: 'Not required',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Priya',
		riskLevel: 'High',
		referralReason: 'BRCA family history',
		testingStatus: 'Pending',
		counselingStatus: 'Scheduled',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		riskLevel: 'Moderate',
		referralReason: 'Recurrent miscarriages',
		testingStatus: 'In progress',
		counselingStatus: 'Complete',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		riskLevel: 'High',
		referralReason: 'Huntington disease family history',
		testingStatus: 'Awaiting consent',
		counselingStatus: 'Scheduled',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		riskLevel: 'High',
		referralReason: 'Multiple family cancers',
		testingStatus: 'Complete',
		counselingStatus: 'Complete',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		riskLevel: 'Low',
		referralReason: 'Preconception screening',
		testingStatus: 'Complete',
		counselingStatus: 'Not required',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		riskLevel: 'Moderate',
		referralReason: 'Carrier status confirmed',
		testingStatus: 'Complete',
		counselingStatus: 'Scheduled',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		riskLevel: 'High',
		referralReason: 'Sudden cardiac death in family',
		testingStatus: 'Pending',
		counselingStatus: 'Urgent',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		riskLevel: 'Moderate',
		referralReason: 'Ashkenazi Jewish heritage with cancer',
		testingStatus: 'In progress',
		counselingStatus: 'Scheduled',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		riskLevel: 'Low',
		referralReason: 'Family history query',
		testingStatus: 'Not started',
		counselingStatus: 'Not required',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		riskLevel: 'High',
		referralReason: 'Known BRCA1 pathogenic variant',
		testingStatus: 'Complete',
		counselingStatus: 'Complete',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		riskLevel: 'Moderate',
		referralReason: 'Consanguineous relationship',
		testingStatus: 'Pending',
		counselingStatus: 'Scheduled',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		riskLevel: 'Low',
		referralReason: 'Prenatal screening',
		testingStatus: 'Complete',
		counselingStatus: 'Complete',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		riskLevel: 'High',
		referralReason: 'Previous affected child - cystic fibrosis',
		testingStatus: 'Complete',
		counselingStatus: 'Ongoing',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		riskLevel: 'Moderate',
		referralReason: 'VUS reclassification review',
		testingStatus: 'In progress',
		counselingStatus: 'Scheduled',
	},
];
