#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding hearing-aid-assessment (14 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    ethnicity:string! \
    primary_language:string! \
    interpreter_required:string! \
    marital_status:string! \
    living_situation:string! \
    occupation:string! \
    retired:string! \
    emergency_contact_name:string! \
    emergency_contact_phone:string! \
    emergency_contact_relationship:string! \
    gp_name:string! \
    gp_practice:string! \
    --htmx

cargo loco generate scaffold assessment_hearing_history \
    assessment:references \
    onset_of_hearing_loss:string! \
    duration_of_hearing_loss:string! \
    hearing_loss_laterality:string! \
    worse_ear:string! \
    noise_exposure_history:string! \
    noise_exposure_details:text! \
    ototoxic_medication_history:string! \
    ototoxic_medication_details:text! \
    family_history_hearing_loss:string! \
    family_hearing_loss_details:text! \
    tinnitus:string! \
    tinnitus_laterality:string! \
    tinnitus_severity:int \
    vertigo_dizziness:string! \
    vertigo_details:text! \
    ear_surgery_history:string! \
    ear_surgery_details:text! \
    hearing_history_notes:text! \
    --htmx

cargo loco generate scaffold assessment_hhies_questionnaire \
    assessment:references \
    s1_telephone_difficulty:int \
    s2_embarrassment:int \
    s3_difficulty_group_conversation:int \
    s4_handicapped_feeling:int \
    s5_difficulty_visiting:int \
    s6_difficulty_religious_services:int \
    s7_arguments_due_to_hearing:int \
    s8_difficulty_tv_radio:int \
    s9_personal_social_life_affected:int \
    s10_difficulty_restaurant:int \
    hhies_total_score:int \
    --htmx

cargo loco generate scaffold assessment_communication_difficulties \
    assessment:references \
    difficulty_quiet_conversation:string! \
    difficulty_noisy_environment:string! \
    difficulty_group_settings:string! \
    difficulty_on_telephone:string! \
    difficulty_television:string! \
    difficulty_understanding_speech:string! \
    asks_people_to_repeat:string! \
    lip_reading_reliance:string! \
    social_withdrawal:string! \
    communication_partner_concerns:string! \
    communication_partner_details:text! \
    communication_notes:text! \
    --htmx

cargo loco generate scaffold assessment_current_hearing_aids \
    assessment:references \
    currently_uses_hearing_aids:string! \
    hearing_aid_side:string! \
    hearing_aid_type:string! \
    hearing_aid_make:string! \
    hearing_aid_model:string! \
    hearing_aid_age_years:int \
    daily_usage_hours:int \
    satisfaction_with_current_aid:string! \
    problems_with_current_aid:string! \
    problem_details:text! \
    previous_hearing_aids:string! \
    previous_aid_details:text! \
    uses_assistive_listening_devices:string! \
    assistive_device_details:text! \
    hearing_aid_notes:text! \
    --htmx

cargo loco generate scaffold assessment_ear_examination \
    assessment:references \
    left_ear_canal:string! \
    left_ear_canal_details:text! \
    right_ear_canal:string! \
    right_ear_canal_details:text! \
    left_tympanic_membrane:string! \
    left_tympanic_membrane_details:text! \
    right_tympanic_membrane:string! \
    right_tympanic_membrane_details:text! \
    left_pinna:string! \
    left_pinna_details:text! \
    right_pinna:string! \
    right_pinna_details:text! \
    otoscopy_referral_needed:string! \
    ear_examination_notes:text! \
    --htmx

cargo loco generate scaffold assessment_audiogram_results \
    assessment:references \
    audiogram_date:date \
    left_pta_db:int \
    right_pta_db:int \
    left_hearing_loss_degree:string! \
    right_hearing_loss_degree:string! \
    left_hearing_loss_type:string! \
    right_hearing_loss_type:string! \
    left_hearing_loss_configuration:string! \
    right_hearing_loss_configuration:string! \
    speech_recognition_left_pct:int \
    speech_recognition_right_pct:int \
    tympanometry_left:string! \
    tympanometry_right:string! \
    asymmetric_hearing_loss:string! \
    audiogram_notes:text! \
    --htmx

cargo loco generate scaffold assessment_lifestyle_and_needs \
    assessment:references \
    primary_listening_environment:string! \
    frequent_phone_use:string! \
    frequent_music_listening:string! \
    active_social_life:string! \
    exercises_regularly:string! \
    dexterity_issues:string! \
    dexterity_details:text! \
    vision_issues:string! \
    vision_details:text! \
    cognitive_concerns:string! \
    technology_comfort:string! \
    smartphone_use:string! \
    bluetooth_connectivity_desired:string! \
    cosmetic_preference:string! \
    budget_considerations:text! \
    lifestyle_notes:text! \
    --htmx

cargo loco generate scaffold assessment_expectations_and_goals \
    assessment:references \
    motivation_level:string! \
    self_referral:string! \
    referral_source:string! \
    primary_goal:text! \
    secondary_goal:text! \
    realistic_expectations:string! \
    willingness_to_wear_daily:string! \
    support_from_family:string! \
    previous_hearing_aid_experience:string! \
    concerns_about_hearing_aids:text! \
    preferred_hearing_aid_style:string! \
    follow_up_commitment:string! \
    expectations_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    handicap_level:string! \
    hhies_total_score:int! \
    hearing_aid_candidacy:string! \
    left_ear_recommendation:string! \
    right_ear_recommendation:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    handicap_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
