#!/bin/sh
# cargo-loco-generate-scaffold/generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding autism-assessment (14 tables)..."

cargo loco generate scaffold patient \
    first_name:string! \
    last_name:string! \
    date_of_birth:date! \
    nhs_number:string^ \
    sex:string! \
    weight_kg:double \
    height_cm:double \
    bmi:double \
    --htmx

cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    --htmx

cargo loco generate scaffold assessment_demographics \
    assessment:references \
    preferred_name:string! \
    gender_identity:string! \
    ethnicity:string! \
    preferred_language:string! \
    interpreter_required:string! \
    gp_name:string! \
    gp_practice:string! \
    referrer_name:string! \
    referrer_role:string! \
    --htmx

cargo loco generate scaffold assessment_screening_purpose \
    assessment:references \
    reason_for_referral:text! \
    who_requested_screening:string! \
    who_requested_screening_other:text! \
    previous_autism_assessment:string! \
    previous_assessment_details:text! \
    previous_assessment_date:date \
    main_concerns:text! \
    impact_on_daily_life:text! \
    --htmx

cargo loco generate scaffold assessment_aq10_questionnaire \
    assessment:references \
    q01_notice_small_sounds:string! \
    q02_concentrate_whole_picture:string! \
    q03_easy_multitask:string! \
    q04_easy_go_back_and_forth:string! \
    q05_easy_read_between_lines:string! \
    q06_easy_detect_feeling_bored:string! \
    q07_easy_work_out_intentions:string! \
    q08_easy_imagine_as_character:string! \
    q09_find_social_situations_easy:string! \
    q10_difficult_work_out_friends:string! \
    --htmx

cargo loco generate scaffold assessment_social_communication \
    assessment:references \
    eye_contact_difficulty:string! \
    understanding_sarcasm:string! \
    difficulty_starting_conversations:string! \
    difficulty_maintaining_conversations:string! \
    literal_interpretation:string! \
    difficulty_reading_body_language:string! \
    difficulty_making_friends:string! \
    preference_for_solitary_activities:string! \
    social_communication_notes:text! \
    --htmx

cargo loco generate scaffold assessment_repetitive_behaviors \
    assessment:references \
    repetitive_movements:string! \
    repetitive_movement_details:text! \
    insistence_on_sameness:string! \
    distress_with_change:string! \
    rigid_routines:string! \
    rigid_routine_details:text! \
    special_interests:string! \
    special_interest_details:text! \
    special_interest_intensity:string! \
    echolalia:string! \
    repetitive_behaviors_notes:text! \
    --htmx

cargo loco generate scaffold assessment_sensory_profile \
    assessment:references \
    hypersensitivity_sound:string! \
    hypersensitivity_light:string! \
    hypersensitivity_touch:string! \
    hypersensitivity_taste_smell:string! \
    hyposensitivity_pain:string! \
    hyposensitivity_temperature:string! \
    sensory_seeking_behaviors:string! \
    sensory_seeking_details:text! \
    sensory_avoidance_behaviors:string! \
    sensory_avoidance_details:text! \
    sensory_overload_frequency:string! \
    sensory_profile_notes:text! \
    --htmx

cargo loco generate scaffold assessment_developmental_history \
    assessment:references \
    age_first_words_months:int \
    age_first_sentences_months:int \
    speech_delay:string! \
    motor_milestone_delay:string! \
    motor_milestone_details:text! \
    toilet_training_delay:string! \
    educational_support_history:text! \
    ehcp_or_statement:string! \
    school_type:string! \
    learning_difficulties:string! \
    learning_difficulties_details:text! \
    developmental_regression:string! \
    developmental_regression_details:text! \
    --htmx

cargo loco generate scaffold assessment_current_support \
    assessment:references \
    receiving_mental_health_support:string! \
    mental_health_support_details:text! \
    current_medications:text! \
    receiving_occupational_therapy:string! \
    receiving_speech_therapy:string! \
    receiving_behavioural_support:string! \
    social_care_involvement:string! \
    social_care_details:text! \
    employment_status:string! \
    employment_support_needs:text! \
    independent_living:string! \
    current_support_notes:text! \
    --htmx

cargo loco generate scaffold assessment_family_history \
    assessment:references \
    family_history_of_autism:string! \
    family_autism_details:text! \
    family_history_of_adhd:string! \
    family_adhd_details:text! \
    family_history_of_learning_disability:string! \
    family_learning_disability_details:text! \
    family_history_of_mental_health:string! \
    family_mental_health_details:text! \
    family_history_of_epilepsy:string! \
    consanguinity:string! \
    family_history_notes:text! \
    --htmx

cargo loco generate scaffold grading_result \
    assessment:references \
    aq10_score:int! \
    threshold_category:string! \
    graded_at:ts! \
    --htmx

cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    severity_level:string! \
    --htmx

cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
