//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "dietic_assessment_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub must_bmi_score: Option<i32>,
    pub must_weight_loss_score: Option<i32>,
    pub must_acute_disease_score: Option<i32>,
    pub must_score: Option<i32>,
    pub computed_must_risk: String,
    pub final_must_risk: String,
    pub must_is_estimated: bool,
    pub glim_phenotypic_criteria: String,
    pub glim_etiologic_criteria: String,
    pub glim_diagnosis: String,
    pub nrs_2002_score: Option<i32>,
    pub sarcf_score: Option<i32>,
    pub scoff_score: Option<i32>,
    pub refeeding_risk: String,
    pub energy_requirement_kcal: Option<i32>,
    pub protein_requirement_g: Option<i32>,
    pub computed_composite_risk: String,
    pub final_composite_risk: String,
    pub override_reason: String,
    pub recommendation: String,
    #[sea_orm(column_type = "Text")]
    pub dietitian_notes: String,
    pub signed_by_name: String,
    pub signed_at: Option<DateTimeWithTimeZone>,
    pub graded_at: DateTimeWithTimeZone,
    pub dietic_assessment_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::dietic_assessment_grade_flags::Entity")]
    DieticAssessmentGradeFlags,
    #[sea_orm(has_many = "super::dietic_assessment_grade_rules::Entity")]
    DieticAssessmentGradeRules,
    #[sea_orm(
        belongs_to = "super::dietic_assessments::Entity",
        from = "Column::DieticAssessmentId",
        to = "super::dietic_assessments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    DieticAssessments,
}

impl Related<super::dietic_assessment_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DieticAssessmentGradeFlags.def()
    }
}

impl Related<super::dietic_assessment_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DieticAssessmentGradeRules.def()
    }
}

impl Related<super::dietic_assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DieticAssessments.def()
    }
}
