//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "newborn_and_infant_physical_examinations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub practitioner_name: String,
    pub practitioner_role: String,
    pub examined_at: Option<DateTimeWithTimeZone>,
    pub examination_context: String,
    pub care_setting: String,
    pub baby_identifier: String,
    pub baby_name: String,
    pub date_of_birth: Option<Date>,
    pub sex: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub gestational_age_weeks: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub birth_weight_grams: Option<f64>,
    pub breech_presentation: String,
    pub family_history_hip_problems: String,
    #[sea_orm(column_type = "Text")]
    pub antenatal_concerns: String,
    pub eyes_red_reflex_right: String,
    pub eyes_red_reflex_left: String,
    pub eyes_appearance: String,
    pub heart_murmur: String,
    pub femoral_pulses_right: String,
    pub femoral_pulses_left: String,
    pub central_cyanosis: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub oxygen_saturation_preductal: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub oxygen_saturation_postductal: Option<f64>,
    pub barlow_test: String,
    pub ortolani_test: String,
    pub hip_abduction: String,
    pub testis_right: String,
    pub testis_left: String,
    pub general_appearance: String,
    pub skin: String,
    pub head_and_fontanelles: String,
    pub face_and_palate: String,
    pub neck_and_clavicles: String,
    pub chest_and_lungs: String,
    pub abdomen: String,
    pub genitalia: String,
    pub anus_and_spine: String,
    pub limbs_and_digits: String,
    pub feet: String,
    pub tone_and_movement: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub weight_grams: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub head_circumference_cm: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub length_cm: Option<f64>,
    pub eyes_result_recorded: String,
    pub heart_result_recorded: String,
    pub hips_result_recorded: String,
    pub testes_result_recorded: String,
    #[sea_orm(column_type = "Text")]
    pub clinical_note: String,
    pub patient_id: i64,
    pub clinician_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::newborn_and_infant_physical_examination_grades::Entity")]
    NewbornAndInfantPhysicalExaminationGrades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::newborn_and_infant_physical_examination_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NewbornAndInfantPhysicalExaminationGrades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}
