//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "assessment_current_medications")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub inhaler_use: String,
    pub inhaler_technique_assessed: String,
    pub inhaler_technique_adequate: String,
    pub short_acting_bronchodilator: String,
    #[sea_orm(column_type = "Text")]
    pub saba_frequency: String,
    pub long_acting_bronchodilator: String,
    pub inhaled_corticosteroid: String,
    pub combination_inhaler: String,
    pub long_term_oxygen_therapy: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub oxygen_flow_rate_lmin: Option<f64>,
    pub oxygen_hours_per_day: Option<i32>,
    pub nebuliser_use: String,
    #[sea_orm(column_type = "Text")]
    pub oral_medications: String,
    pub medication_adherence: String,
    #[sea_orm(column_type = "Text")]
    pub additional_notes: String,
    pub assessment_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assessments::Entity",
        from = "Column::AssessmentId",
        to = "super::assessments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Assessments,
}

impl Related<super::assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assessments.def()
    }
}
