//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "recognition_of_stroke_in_the_emergency_room_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub rosier_score: Option<i32>,
    pub stroke_likely: String,
    pub glucose_excluded: String,
    pub graded_at: DateTimeWithTimeZone,
    pub recognition_of_stroke_in_the_emergency_room_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recognition_of_stroke_in_the_emergency_room_grade_flags::Entity")]
    RecognitionOfStrokeInTheEmergencyRoomGradeFlags,
    #[sea_orm(has_many = "super::recognition_of_stroke_in_the_emergency_room_grade_rules::Entity")]
    RecognitionOfStrokeInTheEmergencyRoomGradeRules,
    #[sea_orm(
        belongs_to = "super::recognition_of_stroke_in_the_emergency_rooms::Entity",
        from = "Column::RecognitionOfStrokeInTheEmergencyRoomId",
        to = "super::recognition_of_stroke_in_the_emergency_rooms::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RecognitionOfStrokeInTheEmergencyRooms,
}

impl Related<super::recognition_of_stroke_in_the_emergency_room_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecognitionOfStrokeInTheEmergencyRoomGradeFlags.def()
    }
}

impl Related<super::recognition_of_stroke_in_the_emergency_room_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecognitionOfStrokeInTheEmergencyRoomGradeRules.def()
    }
}

impl Related<super::recognition_of_stroke_in_the_emergency_rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecognitionOfStrokeInTheEmergencyRooms.def()
    }
}
