//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "cervical_screening_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub result_class: String,
    pub management_action: String,
    pub status: String,
    pub graded_at: DateTimeWithTimeZone,
    pub cervical_screening_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cervical_screening_grade_flags::Entity")]
    CervicalScreeningGradeFlags,
    #[sea_orm(has_many = "super::cervical_screening_grade_rules::Entity")]
    CervicalScreeningGradeRules,
    #[sea_orm(
        belongs_to = "super::cervical_screenings::Entity",
        from = "Column::CervicalScreeningId",
        to = "super::cervical_screenings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    CervicalScreenings,
}

impl Related<super::cervical_screening_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CervicalScreeningGradeFlags.def()
    }
}

impl Related<super::cervical_screening_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CervicalScreeningGradeRules.def()
    }
}

impl Related<super::cervical_screenings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CervicalScreenings.def()
    }
}
