//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "attorneys")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub title: String,
    pub given_names: String,
    pub family_name: String,
    pub birth_date: Option<Date>,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub phone: String,
    #[sea_orm(column_type = "Text")]
    pub postal_address_as_full_text: String,
    pub country_as_iso_3166_1_alpha_2: String,
    #[sea_orm(column_type = "Text")]
    pub postcode: String,
    pub relationship_to_donor: String,
    pub is_bankrupt: String,
    pub capacity_declared: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::lpa_attorneys::Entity")]
    LpaAttorneys,
}

impl Related<super::lpa_attorneys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LpaAttorneys.def()
    }
}
