//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "lpa_decision_rules")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub decision_rule: String,
    #[sea_orm(column_type = "Text")]
    pub joint_decision_set: String,
    pub lpa_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::lpas::Entity",
        from = "Column::LpaId",
        to = "super::lpas::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Lpas,
}

impl Related<super::lpas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lpas.def()
    }
}
