//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "prescription_requests")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    pub patient_id: i64,
    pub clinician_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clinicians::Entity",
        from = "Column::ClinicianId",
        to = "super::clinicians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Clinicians,
    #[sea_orm(has_many = "super::grades::Entity")]
    Grades,
    #[sea_orm(
        belongs_to = "super::patients::Entity",
        from = "Column::PatientId",
        to = "super::patients::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Patients,
    #[sea_orm(has_many = "super::prescription_details::Entity")]
    PrescriptionDetails,
    #[sea_orm(has_many = "super::prescription_request_types::Entity")]
    PrescriptionRequestTypes,
    #[sea_orm(has_many = "super::prescription_substitution_options::Entity")]
    PrescriptionSubstitutionOptions,
}

impl Related<super::clinicians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clinicians.def()
    }
}

impl Related<super::grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Grades.def()
    }
}

impl Related<super::patients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Patients.def()
    }
}

impl Related<super::prescription_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrescriptionDetails.def()
    }
}

impl Related<super::prescription_request_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrescriptionRequestTypes.def()
    }
}

impl Related<super::prescription_substitution_options::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrescriptionSubstitutionOptions.def()
    }
}
