//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "prescription_details")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub request_date: Date,
    pub medication_name: String,
    pub dosage: String,
    pub frequency: String,
    pub route_of_administration: String,
    #[sea_orm(column_type = "Text")]
    pub treatment_instructions: String,
    pub prescription_request_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prescription_requests::Entity",
        from = "Column::PrescriptionRequestId",
        to = "super::prescription_requests::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PrescriptionRequests,
}

impl Related<super::prescription_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrescriptionRequests.def()
    }
}
