//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "curb_65_pneumonia_severity_score_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub confusion_score: Option<i32>,
    pub urea_score: Option<i32>,
    pub respiratory_rate_score: Option<i32>,
    pub blood_pressure_score: Option<i32>,
    pub age_score: Option<i32>,
    pub total_score: Option<i32>,
    pub score_variant: String,
    pub risk_band: String,
    #[sea_orm(column_type = "Text")]
    pub recommended_setting: String,
    pub graded_at: DateTimeWithTimeZone,
    pub curb_65_pneumonia_severity_score_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::curb_65_pneumonia_severity_score_grade_flags::Entity")]
    Curb65PneumoniaSeverityScoreGradeFlags,
    #[sea_orm(has_many = "super::curb_65_pneumonia_severity_score_grade_rules::Entity")]
    Curb65PneumoniaSeverityScoreGradeRules,
    #[sea_orm(
        belongs_to = "super::curb_65_pneumonia_severity_scores::Entity",
        from = "Column::Curb65PneumoniaSeverityScoreId",
        to = "super::curb_65_pneumonia_severity_scores::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Curb65PneumoniaSeverityScores,
}

impl Related<super::curb_65_pneumonia_severity_score_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Curb65PneumoniaSeverityScoreGradeFlags.def()
    }
}

impl Related<super::curb_65_pneumonia_severity_score_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Curb65PneumoniaSeverityScoreGradeRules.def()
    }
}

impl Related<super::curb_65_pneumonia_severity_scores::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Curb65PneumoniaSeverityScores.def()
    }
}
