#!/bin/sh
# cargo-loco-generate/cargo-loco-generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding medical-records-release-permission (13 tables)..."

cargo loco generate scaffold patient \
    deleted_at:ts \
    name:string! \
    birth_date:date \
    united_kingdom_nhs_number:string^ \
    waist_as_cm:double \
    height_as_cm:double \
    weight_as_kg:double \
    body_mass_index:double \
    waist_height_ratio:double \
    vo2_max:double \
    --htmx && \
cargo loco generate scaffold clinician \
    deleted_at:ts \
    name:text! \
    role:text! \
    registration_body:text! \
    registration_number:text! \
    united_kingdom_nhs_number:string^ \
    --htmx && \
cargo loco generate scaffold release_form \
    patient:references \
    status:string! \
    --htmx && \
cargo loco generate scaffold authorized_recipient \
    release_form:references \
    recipient_name:string! \
    recipient_organization:string! \
    recipient_address:text! \
    recipient_phone:string! \
    recipient_email:string! \
    recipient_role:string! \
    --htmx && \
cargo loco generate scaffold records_to_release \
    release_form:references \
    record_types:text! \
    specific_date_range:string! \
    date_from:date \
    date_to:date \
    specific_record_details:text! \
    --htmx && \
cargo loco generate scaffold purpose_of_release \
    release_form:references \
    purpose:string! \
    other_details:text! \
    --htmx && \
cargo loco generate scaffold authorization_period \
    release_form:references \
    start_date:date! \
    end_date:date! \
    single_use:string! \
    --htmx && \
cargo loco generate scaffold restrictions_limitations \
    release_form:references \
    exclude_hiv:string! \
    exclude_substance_abuse:string! \
    exclude_mental_health:string! \
    exclude_genetic_info:string! \
    exclude_sti:string! \
    additional_restrictions:text! \
    --htmx && \
cargo loco generate scaffold patient_rights \
    release_form:references \
    acknowledged_right_to_revoke:string! \
    acknowledged_no_charge_for_access:string! \
    acknowledged_data_protection:string! \
    --htmx && \
cargo loco generate scaffold signature_consent \
    release_form:references \
    patient_signature_confirmed:string! \
    signature_date:date \
    witness_name:string! \
    witness_signature_confirmed:string! \
    witness_date:date \
    parent_guardian_name:string! \
    --htmx && \
cargo loco generate scaffold validation_result \
    release_form:references \
    completeness_score:int! \
    completeness_status:string! \
    validation_status:string! \
    validated_at:ts \
    --htmx && \
cargo loco generate scaffold validation_fired_rule \
    validation_result:references \
    rule_id:string! \
    domain:string! \
    description:text! \
    score:int! \
    --htmx && \
cargo loco generate scaffold validation_additional_flag \
    validation_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
