//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "wells_score_for_deep_vein_thrombosis_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub wells_score: Option<i32>,
    pub two_level_band: String,
    pub three_level_band: String,
    #[sea_orm(column_type = "Text")]
    pub recommended_pathway: String,
    pub graded_at: DateTimeWithTimeZone,
    pub wells_score_for_deep_vein_thrombosis_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wells_score_for_deep_vein_thromboses::Entity",
        from = "Column::WellsScoreForDeepVeinThrombosisId",
        to = "super::wells_score_for_deep_vein_thromboses::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    WellsScoreForDeepVeinThromboses,
    #[sea_orm(has_many = "super::wells_score_for_deep_vein_thrombosis_grade_flags::Entity")]
    WellsScoreForDeepVeinThrombosisGradeFlags,
    #[sea_orm(has_many = "super::wells_score_for_deep_vein_thrombosis_grade_rules::Entity")]
    WellsScoreForDeepVeinThrombosisGradeRules,
}

impl Related<super::wells_score_for_deep_vein_thromboses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WellsScoreForDeepVeinThromboses.def()
    }
}

impl Related<super::wells_score_for_deep_vein_thrombosis_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WellsScoreForDeepVeinThrombosisGradeFlags.def()
    }
}

impl Related<super::wells_score_for_deep_vein_thrombosis_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WellsScoreForDeepVeinThrombosisGradeRules.def()
    }
}
