import type { PatientRow } from './types.ts';

/** Sample patient data for the clinician dashboard */
export const patients: PatientRow[] = [
	{
		id: '1',
		nhsNumber: '943 476 5919',
		patientName: 'Smith, Eleanor',
		ecogStatus: 0,
		cancerType: 'Breast',
		stage: 'Stage I',
		treatmentStatus: 'Complete Response',
	},
	{
		id: '2',
		nhsNumber: '721 938 4102',
		patientName: 'Patel, Rajesh',
		ecogStatus: 1,
		cancerType: 'Lung',
		stage: 'Stage III',
		treatmentStatus: 'On Treatment',
	},
	{
		id: '3',
		nhsNumber: '384 615 7230',
		patientName: 'Jones, Margaret',
		ecogStatus: 2,
		cancerType: 'Colorectal',
		stage: 'Stage IV',
		treatmentStatus: 'Progressive Disease',
	},
	{
		id: '4',
		nhsNumber: '512 847 9063',
		patientName: 'Williams, David',
		ecogStatus: 1,
		cancerType: 'Prostate',
		stage: 'Stage II',
		treatmentStatus: 'Stable Disease',
	},
	{
		id: '5',
		nhsNumber: '167 293 8451',
		patientName: 'Brown, Sarah',
		ecogStatus: 3,
		cancerType: 'Pancreatic',
		stage: 'Stage IV',
		treatmentStatus: 'Palliative Care',
	},
	{
		id: '6',
		nhsNumber: '835 162 4097',
		patientName: 'Taylor, James',
		ecogStatus: 0,
		cancerType: 'Melanoma',
		stage: 'Stage I',
		treatmentStatus: 'Complete Response',
	},
	{
		id: '7',
		nhsNumber: '294 708 5316',
		patientName: 'Davies, Helen',
		ecogStatus: 2,
		cancerType: 'Ovarian',
		stage: 'Stage III',
		treatmentStatus: 'On Treatment',
	},
	{
		id: '8',
		nhsNumber: '608 341 2975',
		patientName: 'Wilson, Robert',
		ecogStatus: 1,
		cancerType: 'Lymphoma',
		stage: 'Stage II',
		treatmentStatus: 'Partial Response',
	},
	{
		id: '9',
		nhsNumber: '473 926 1084',
		patientName: 'Evans, Catherine',
		ecogStatus: 3,
		cancerType: 'Lung',
		stage: 'Stage IV',
		treatmentStatus: 'Progressive Disease',
	},
	{
		id: '10',
		nhsNumber: '159 684 7302',
		patientName: 'Thomas, Michael',
		ecogStatus: 0,
		cancerType: 'Thyroid',
		stage: 'Stage I',
		treatmentStatus: 'Complete Response',
	},
	{
		id: '11',
		nhsNumber: '742 051 3896',
		patientName: 'Robinson, Emma',
		ecogStatus: 1,
		cancerType: 'Breast',
		stage: 'Stage II',
		treatmentStatus: 'On Treatment',
	},
	{
		id: '12',
		nhsNumber: '386 219 5740',
		patientName: 'Clark, George',
		ecogStatus: 4,
		cancerType: 'Brain',
		stage: 'Stage IV',
		treatmentStatus: 'Palliative Care',
	},
	{
		id: '13',
		nhsNumber: '925 473 0168',
		patientName: 'Walker, Susan',
		ecogStatus: 1,
		cancerType: 'Renal',
		stage: 'Stage II',
		treatmentStatus: 'Stable Disease',
	},
	{
		id: '14',
		nhsNumber: '618 305 9247',
		patientName: 'Hall, Richard',
		ecogStatus: 2,
		cancerType: 'Gastric',
		stage: 'Stage III',
		treatmentStatus: 'On Treatment',
	},
	{
		id: '15',
		nhsNumber: '057 842 6139',
		patientName: 'Young, Elizabeth',
		ecogStatus: 0,
		cancerType: 'Cervical',
		stage: 'Stage I',
		treatmentStatus: 'Complete Response',
	},
];
