#!/bin/sh
# cargo-loco-generate/cargo-loco-generate.sh
#
# Generator script for Loco scaffolding.
#
# Run from inside a fresh Loco project (one created via
# `loco new --name <form-slug> --db postgres --bg async --assets serverside`)
# to scaffold every CRUD resource for this form. Tables are scaffolded in the
# same order as the form's sql-migrations/ so that FK targets already exist
# when referencing tables are created.
#
# Generated by bin/generate-cargo-loco-scaffold.py from sql-migrations/*.sql.
# Do not edit by hand — re-run the generator after changing the SQL migrations.

set -euf


echo "Scaffolding advance-decision-to-refuse-treatment (6 tables)..."

cargo loco generate scaffold patient \
    deleted_at:ts \
    name:string! \
    birth_date:date \
    united_kingdom_nhs_number:string^ \
    waist_as_cm:double \
    height_as_cm:double \
    weight_as_kg:double \
    body_mass_index:double \
    waist_height_ratio:double \
    vo2_max:double \
    --htmx && \
cargo loco generate scaffold clinician \
    deleted_at:ts \
    name:text! \
    role:text! \
    registration_body:text! \
    registration_number:text! \
    united_kingdom_nhs_number:string^ \
    --htmx && \
cargo loco generate scaffold assessment \
    patient:references \
    status:string! \
    full_name:string! \
    address:text! \
    postcode:string! \
    date_of_birth:date \
    nhs_number:string! \
    gp_name:string! \
    gp_practice:string! \
    gp_address:text! \
    gp_phone:string! \
    has_mental_capacity:string! \
    understands_consequences:string! \
    made_voluntarily:string! \
    capacity_assessment_date:date \
    capacity_assessor_name:string! \
    capacity_assessor_role:string! \
    capacity_notes:text! \
    circumstances_description:text! \
    specific_conditions:text! \
    applies_if_terminally_ill:string! \
    applies_if_permanently_unconscious:string! \
    applies_if_severely_brain_damaged:string! \
    applies_if_advanced_dementia:string! \
    other_circumstances:text! \
    refuses_cardiopulmonary_resuscitation:string! \
    refuses_mechanical_ventilation:string! \
    refuses_artificial_nutrition:string! \
    refuses_artificial_hydration:string! \
    refuses_antibiotics:string! \
    refuses_blood_transfusion:string! \
    refuses_dialysis:string! \
    other_treatments_refused:text! \
    treatment_refusal_details:text! \
    includes_life_sustaining_treatment:string! \
    understands_may_result_in_death:string! \
    life_sustaining_treatments_specified:text! \
    is_written_and_signed:string! \
    is_witnessed:string! \
    witness_confirmation:text! \
    has_exceptions:string! \
    exception_details:text! \
    pain_management_wishes:text! \
    comfort_care_wishes:text! \
    emergency_exception_details:text! \
    condition_specific_exceptions:text! \
    preferred_place_of_care:text! \
    preferred_place_of_death:text! \
    spiritual_or_religious_wishes:text! \
    organ_donation_wishes:string! \
    organ_donation_details:text! \
    other_wishes:text! \
    people_to_notify:text! \
    has_health_welfare_lpa:string! \
    lpa_registered_with_opg:string! \
    lpa_registration_date:date \
    attorney_name:string! \
    attorney_address:text! \
    attorney_phone:string! \
    replacement_attorney_name:string! \
    lpa_authority_scope:text! \
    lpa_conflicts_with_adrt:string! \
    lpa_conflict_details:text! \
    reviewed_by_healthcare_professional:string! \
    reviewer_name:string! \
    reviewer_role:string! \
    reviewer_registration_number:string! \
    review_date:date \
    reviewer_confirms_capacity:string! \
    reviewer_confirms_informed:string! \
    clinical_notes:text! \
    concerns_raised:text! \
    reviewer_signature_obtained:string! \
    maker_signature_obtained:string! \
    maker_signature_date:date \
    witness_name:string! \
    witness_address:text! \
    witness_signature_obtained:string! \
    witness_signature_date:date \
    second_witness_name:string! \
    second_witness_signature_obtained:string! \
    declaration_statement_agreed:string! \
    legal_notes:text! \
    --htmx && \
cargo loco generate scaffold grading_result \
    assessment:references \
    validity_level:string! \
    graded_at:ts! \
    --htmx && \
cargo loco generate scaffold grading_fired_rule \
    grading_result:references \
    rule_id:string! \
    category:string! \
    description:text! \
    validity_level:string! \
    --htmx && \
cargo loco generate scaffold grading_additional_flag \
    grading_result:references \
    flag_id:string! \
    category:string! \
    message:text! \
    priority:string! \
    --htmx

echo "Done."
