//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "clinicians")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub specialty: String,
    pub role: String,
    pub registration_body: String,
    #[sea_orm(column_type = "Text")]
    pub registration_number: String,
    #[sea_orm(column_type = "Text")]
    pub clinic_name: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    #[sea_orm(column_type = "Text")]
    pub phone: String,
    #[sea_orm(column_type = "Text")]
    pub postal_address_as_full_text: String,
    pub country_as_iso_3166_1_alpha_2: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub postcode: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::medical_information_form_for_air_travels::Entity")]
    MedicalInformationFormForAirTravels,
}

impl Related<super::medical_information_form_for_air_travels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalInformationFormForAirTravels.def()
    }
}
