//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "medical_information_form_for_air_travel_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub computed_fitness_band: String,
    pub final_fitness_band: String,
    pub override_reason: String,
    pub desk_recommendation: String,
    #[sea_orm(column_type = "Text")]
    pub physician_notes: String,
    pub valid_until: Option<Date>,
    pub signed_at: Option<DateTimeWithTimeZone>,
    pub graded_at: DateTimeWithTimeZone,
    pub medical_information_form_for_air_travel_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::medical_information_form_for_air_travel_grade_flags::Entity")]
    MedicalInformationFormForAirTravelGradeFlags,
    #[sea_orm(has_many = "super::medical_information_form_for_air_travel_grade_rules::Entity")]
    MedicalInformationFormForAirTravelGradeRules,
    #[sea_orm(
        belongs_to = "super::medical_information_form_for_air_travels::Entity",
        from = "Column::MedicalInformationFormForAirTravelId",
        to = "super::medical_information_form_for_air_travels::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MedicalInformationFormForAirTravels,
}

impl Related<super::medical_information_form_for_air_travel_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalInformationFormForAirTravelGradeFlags.def()
    }
}

impl Related<super::medical_information_form_for_air_travel_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalInformationFormForAirTravelGradeRules.def()
    }
}

impl Related<super::medical_information_form_for_air_travels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalInformationFormForAirTravels.def()
    }
}
