/** Sample patient allergy assessment records for the clinician dashboard */
export const patients = [
  { id: '1', nhsNumber: '943 476 5919', patientName: 'Smith, John', severityLevel: 'severe', allergenCount: 8, primaryAllergyType: 'Drug', hasAnaphylaxis: true, burdenScore: 14, flagCount: 3, status: 'urgent', submittedDate: '2026-03-01' },
  { id: '2', nhsNumber: '721 938 4102', patientName: 'Patel, Priya', severityLevel: 'moderate', allergenCount: 4, primaryAllergyType: 'Food', hasAnaphylaxis: false, burdenScore: 6, flagCount: 1, status: 'pending', submittedDate: '2026-03-05' },
  { id: '3', nhsNumber: '384 615 7230', patientName: 'Jones, Margaret', severityLevel: 'mild', allergenCount: 2, primaryAllergyType: 'Environmental', hasAnaphylaxis: false, burdenScore: 2, flagCount: 0, status: 'reviewed', submittedDate: '2026-02-20' },
  { id: '4', nhsNumber: '512 847 9063', patientName: 'Williams, David', severityLevel: 'severe', allergenCount: 6, primaryAllergyType: 'Drug', hasAnaphylaxis: true, burdenScore: 11, flagCount: 4, status: 'urgent', submittedDate: '2026-03-07' },
  { id: '5', nhsNumber: '167 293 8451', patientName: 'Brown, Sarah', severityLevel: 'moderate', allergenCount: 5, primaryAllergyType: 'Food', hasAnaphylaxis: false, burdenScore: 7, flagCount: 2, status: 'reviewed', submittedDate: '2026-02-15' },
  { id: '6', nhsNumber: '835 162 4097', patientName: 'Taylor, James', severityLevel: 'mild', allergenCount: 1, primaryAllergyType: 'Environmental', hasAnaphylaxis: false, burdenScore: 1, flagCount: 0, status: 'reviewed', submittedDate: '2026-03-08' },
  { id: '7', nhsNumber: '294 708 5316', patientName: 'Davies, Helen', severityLevel: 'severe', allergenCount: 7, primaryAllergyType: 'Food', hasAnaphylaxis: true, burdenScore: 12, flagCount: 5, status: 'pending', submittedDate: '2026-01-28' },
  { id: '8', nhsNumber: '608 341 2975', patientName: 'Wilson, Robert', severityLevel: 'moderate', allergenCount: 3, primaryAllergyType: 'Drug', hasAnaphylaxis: false, burdenScore: 5, flagCount: 1, status: 'reviewed', submittedDate: '2026-03-02' },
  { id: '9', nhsNumber: '473 926 1084', patientName: 'Evans, Catherine', severityLevel: 'moderate', allergenCount: 4, primaryAllergyType: 'Environmental', hasAnaphylaxis: false, burdenScore: 4, flagCount: 1, status: 'pending', submittedDate: '2026-02-28' },
  { id: '10', nhsNumber: '159 684 7302', patientName: 'Thomas, Michael', severityLevel: 'severe', allergenCount: 9, primaryAllergyType: 'Drug', hasAnaphylaxis: true, burdenScore: 16, flagCount: 6, status: 'urgent', submittedDate: '2026-03-10' },
  { id: '11', nhsNumber: '742 051 3896', patientName: 'Robinson, Emma', severityLevel: 'mild', allergenCount: 2, primaryAllergyType: 'Environmental', hasAnaphylaxis: false, burdenScore: 2, flagCount: 0, status: 'reviewed', submittedDate: '2026-03-09' },
  { id: '12', nhsNumber: '386 219 5740', patientName: 'Clark, George', severityLevel: 'moderate', allergenCount: 3, primaryAllergyType: 'Food', hasAnaphylaxis: false, burdenScore: 5, flagCount: 1, status: 'pending', submittedDate: '2026-02-10' },
  { id: '13', nhsNumber: '925 473 0168', patientName: 'Walker, Susan', severityLevel: 'severe', allergenCount: 5, primaryAllergyType: 'Drug', hasAnaphylaxis: true, burdenScore: 10, flagCount: 3, status: 'urgent', submittedDate: '2026-03-11' },
  { id: '14', nhsNumber: '618 305 9247', patientName: 'Hall, Richard', severityLevel: 'mild', allergenCount: 1, primaryAllergyType: 'Food', hasAnaphylaxis: false, burdenScore: 1, flagCount: 0, status: 'reviewed', submittedDate: '2026-03-04' },
  { id: '15', nhsNumber: '057 842 6139', patientName: 'Young, Elizabeth', severityLevel: 'moderate', allergenCount: 6, primaryAllergyType: 'Environmental', hasAnaphylaxis: false, burdenScore: 8, flagCount: 2, status: 'pending', submittedDate: '2026-02-01' },
];
