//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "clinical_reviews")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub post_vaccination_observation: Option<i32>,
    pub immediate_reaction: String,
    #[sea_orm(column_type = "Text")]
    pub reaction_details: String,
    pub next_dose_due: Option<Date>,
    pub catch_up_schedule_needed: String,
    pub referral_needed: String,
    #[sea_orm(column_type = "Text")]
    pub clinician_notes: String,
    pub reviewing_clinician: String,
    pub assessment_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assessments::Entity",
        from = "Column::AssessmentId",
        to = "super::assessments::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Assessments,
}

impl Related<super::assessments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assessments.def()
    }
}
