//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "prev_med_waiting_list_card_grade_flags")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub flag_id: String,
    pub category: String,
    pub priority: String,
    pub description: String,
    pub suggested_action: String,
    pub prev_med_waiting_list_card_grade_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prev_med_waiting_list_card_grades::Entity",
        from = "Column::PrevMedWaitingListCardGradeId",
        to = "super::prev_med_waiting_list_card_grades::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PrevMedWaitingListCardGrades,
}

impl Related<super::prev_med_waiting_list_card_grades::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrevMedWaitingListCardGrades.def()
    }
}
