//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "hypertension_review_grades")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i64,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub control_status: String,
    pub hypertension_stage: String,
    pub review_status: String,
    pub primary_source: String,
    pub target_group: String,
    pub clinic_target_systolic: Option<i32>,
    pub clinic_target_diastolic: Option<i32>,
    pub home_target_systolic: Option<i32>,
    pub home_target_diastolic: Option<i32>,
    pub graded_at: DateTimeWithTimeZone,
    pub hypertension_review_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::hypertension_review_grade_flags::Entity")]
    HypertensionReviewGradeFlags,
    #[sea_orm(has_many = "super::hypertension_review_grade_rules::Entity")]
    HypertensionReviewGradeRules,
    #[sea_orm(
        belongs_to = "super::hypertension_reviews::Entity",
        from = "Column::HypertensionReviewId",
        to = "super::hypertension_reviews::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    HypertensionReviews,
}

impl Related<super::hypertension_review_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HypertensionReviewGradeFlags.def()
    }
}

impl Related<super::hypertension_review_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HypertensionReviewGradeRules.def()
    }
}

impl Related<super::hypertension_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::HypertensionReviews.def()
    }
}
