//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Model.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "medical_operation_note_implants")]
pub struct Model {
    /// Created at.
    pub created_at: DateTimeWithTimeZone,
    /// Updated at.
    pub updated_at: DateTimeWithTimeZone,
    /// ID.
    #[sea_orm(primary_key)]
    pub id: i64,
    /// Deleted at.
    pub deleted_at: Option<DateTimeWithTimeZone>,
    /// Category.
    pub category: String,
    /// Name.
    pub name: String,
    /// Size or gauge.
    pub size_or_gauge: String,
    /// Quantity.
    pub quantity: i32,
    /// Manufacturer.
    pub manufacturer: String,
    /// Lot number.
    pub lot_number: String,
    /// Serial number.
    pub serial_number: String,
    /// Batch number.
    pub batch_number: String,
    /// Expiry date.
    pub expiry_date: Option<Date>,
    /// Udi di.
    pub udi_di: String,
    /// Implant site.
    pub implant_site: String,
    /// Registry required.
    pub registry_required: String,
    /// Registry submitted.
    pub registry_submitted: String,
    /// Notes.
    #[sea_orm(column_type = "Text")]
    pub notes: String,
    /// Medical operation note ID.
    pub medical_operation_note_id: i64,
}

/// Relation.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::medical_operation_notes::Entity",
        from = "Column::MedicalOperationNoteId",
        to = "super::medical_operation_notes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Medical operation notes.
    MedicalOperationNotes,
}

impl Related<super::medical_operation_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalOperationNotes.def()
    }
}
