//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Model.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
#[sea_orm(table_name = "medical_operation_note_grades")]
pub struct Model {
    /// Created at.
    pub created_at: DateTimeWithTimeZone,
    /// Updated at.
    pub updated_at: DateTimeWithTimeZone,
    /// ID.
    #[sea_orm(primary_key)]
    pub id: i64,
    /// Deleted at.
    pub deleted_at: Option<DateTimeWithTimeZone>,
    /// Computed composite risk.
    pub computed_composite_risk: String,
    /// Final composite risk.
    pub final_composite_risk: String,
    /// Override reason.
    pub override_reason: String,
    /// Worst clavien dindo grade.
    pub worst_clavien_dindo_grade: String,
    /// Asa physical status.
    pub asa_physical_status: String,
    /// Blood loss band.
    pub blood_loss_band: String,
    /// Counts agreed.
    pub counts_agreed: String,
    /// Never event suspected.
    pub never_event_suspected: String,
    /// Recommendation.
    pub recommendation: String,
    /// Surgeon notes.
    #[sea_orm(column_type = "Text")]
    pub surgeon_notes: String,
    /// Signed at.
    pub signed_at: Option<DateTimeWithTimeZone>,
    /// Graded at.
    pub graded_at: DateTimeWithTimeZone,
    /// Medical operation note ID.
    pub medical_operation_note_id: i64,
}

/// Relation.
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// Medical operation note grade flags.
    #[sea_orm(has_many = "super::medical_operation_note_grade_flags::Entity")]
    MedicalOperationNoteGradeFlags,
    /// Medical operation note grade rules.
    #[sea_orm(has_many = "super::medical_operation_note_grade_rules::Entity")]
    MedicalOperationNoteGradeRules,
    #[sea_orm(
        belongs_to = "super::medical_operation_notes::Entity",
        from = "Column::MedicalOperationNoteId",
        to = "super::medical_operation_notes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    /// Medical operation notes.
    MedicalOperationNotes,
}

impl Related<super::medical_operation_note_grade_flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalOperationNoteGradeFlags.def()
    }
}

impl Related<super::medical_operation_note_grade_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalOperationNoteGradeRules.def()
    }
}

impl Related<super::medical_operation_notes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MedicalOperationNotes.def()
    }
}
